Step2 - 수강신청(도메인 모델)
next-step/java-lms pull request #115
Opened 2023-05-28 08:59 UTC by jaewon0913

안녕하세요 준혁님!!!

일상 업무 때문에 너무 늦게나마 과제를 진행하여, 제대로 진행했는지도 잘 모르겠습니다.🙇🙇
도메인만 생성하면 되는 걸까요??

리뷰 부탁드립니다!

2023-05-28 21:33 UTC, javajigi requested changes
도메인 객체 분리, 도메인에 수강신청 관련 로직 구현, 단위 테스트 코드 구현 💯 
전체적으로 미션 의도에 맞게 구현을 너무 잘했네요.
단, SessionInfo의 이름과 SessionInfo가 수강생 목록을 가지는 구조로 설계하면 어떨지 피드백 남겼으니 한번 검토해 보면 좋겠네요.

2023-05-28 21:33 UTC, javajigi commented on src/main/java/nextstep/courses/domain/BaseEntity.java
> +public abstract class BaseEntity {
👍

2023-05-28 21:33 UTC, javajigi commented on src/main/java/nextstep/courses/domain/Course.java
> +    private Sessions sessions;
일급 콜렉션 추가 👍

2023-05-28 21:33 UTC, javajigi commented on src/main/java/nextstep/courses/domain/CoverImage.java
> +public class CoverImage {
원시값과 문자열을 포장하는 원칙을 지킨 것은 굿
하지만 이와 같이 아무런 로직도 가지지 않는 객체는 포장을 하는 것이 의미가 없지 않을까?
포장을 했다면 이미지 url 값이 유효한지의 여부등을 판단하는 로직을 가지는 것은 어떨까?

2023-05-28 21:33 UTC, javajigi commented on src/main/java/nextstep/courses/domain/SessionInfo.java
> +    private int currentStudentCount;
아직 db에 저장도 하지 않고 있다.
수강신청한 사용자 목록을 이 객체가 가지는 것은 어떨까?

2023-05-28 21:33 UTC, javajigi commented on src/main/java/nextstep/courses/domain/SessionInfo.java
> +public class SessionInfo {
이 객체가 수강 신청과 관련한 역할을 담당하고 있는데 객체 이름이 적합하지 않은 것 같다.
더 적합한 이름으로 변경하면 어떨까?

2023-05-28 21:33 UTC, javajigi commented on src/main/java/nextstep/courses/domain/SessionInfo.java
> +    public void registerSession(int studentCount) {
👍 

```suggestion
    public void registerSession(NsUser nsUser) {
```

2023-05-28 21:33 UTC, javajigi commented on src/test/java/nextstep/courses/domain/SessionInfoTest.java
> +}
정상적으로 수강신청 됐는지 여부도 테스트 가능하지 않을까?

2023-05-28 21:33 UTC, javajigi commented on src/test/java/nextstep/courses/domain/SessionsTest.java
> +                new Price(1000));
Session 객체와 같이 인스턴스 변수가 많은 객체를 테스트하려면 객체를 생성하는데 어려움이 있다.
중복 코드 또한 많이 발생한다.
https://www.arhohuttunen.com/test-data-builders/ 문서 참고해 Session과 같이 복잡한 객체의 테스트 데이터를 생성할 때 어떤 방법을 사용할 것인지 선택해 보면 좋겠다.
이번 기회에 내가 선호하는 방법을 적용해 보고 앞으로도 쭈욱 활용하는 방식이면 좋겠다.

2023-05-29 06:05 UTC, nooose requested changes
포비님이 남겨주신 코멘트가 있는데
한 번 리팩토링해보시면 좋을 것 같습니다!
수정해 보시고 재요청 부탁드립니다

2023-05-29 06:05 UTC, nooose commented on src/main/java/nextstep/courses/domain/Price.java
> +    public PriceType getPrice() {
`getPrice`는 가격을 가져오는 메서드로 착각할 수 있어보여요 😅

2023-05-29 23:35 UTC, javajigi approved these changes
피드백 반영 잘 했네요. 💯 
도메인 객체를 먼저 구현한 후 DB 매핑이 생각보다 쉽지 않을 수 있는데 한번 도전해 보세요.
빠른 미션 진행을 위해 제가 대신 merge해요.

2023-05-29 23:35 UTC, merged