step1 : 1단계 - 레거시 코드 리팩터링
next-step/java-lms pull request #147
Opened 2023-05-30 12:36 UTC by JerryK026

안녕하세요! 늦었지만 코드 리뷰 부탁드립니다!

과제를 수행하면서 고려했던 점, 궁금한 점들은 다음과 같습니다.

getter는 열어둔다 : JPA를 사용하면 getter를 사용하게 되고, delete 메서드가 command이기 때문에 상태에 대해 테스트하기 어려워 getter는 남기기로 결정했습니다. 단, 테스트에서만 사용한다고 팀에서 약속한다고 가정합니다.
=> 만약 getter가 적당하지 않다고 판단된다면 void를 리턴하는 command에서는 상태에 대해서 어떻게 테스트할 수 있을까요?

question의 delete 메서드에 대해서 테스트할 때, answer에 대해서도 테스트했는데 이게 옳은 방법인지 궁금합니다. delete 메서드가 기대하는 동작은 question / answer에 대해 deleted = true하는 동작과, deleteHistory를 더하는 동작이라 함께 테스트했습니다. 그러나, question의 테스트지만 answer에 대해서 의존하기 때문에 단위테스트지만 외부에 영향을 받는 게 맞는 것인가? 하는 생각이 들었습니다.

1단계에서 제시한 그림은 delete에서 DeleteHistories까지 처리하는 그림을 제시했는데, deleteHistories라는 메서드를 만들어서 delete=true하는 동작과 deleteHistories를 save하기 위해 원하는 List를 만드는 deleteHistories 메서드를 분리하는 것도 적절하지 않나? 라는 생각을 했습니다. 이 편이 메서드를 더 잘게 쪼개는 것 같기도 하고, deleteHistory에 대한 요구조건이 바뀌었을 때 더 쉽게 짐작할 수 있을 것이라는 생각이 들었습니다.

2023-05-30 23:52 UTC, serverwizard commented
```
getter는 열어둔다 : JPA를 사용하면 getter를 사용하게 되고, delete 메서드가 command이기 때문에 상태에 대해 테스트하기 어려워 getter는 남기기로 결정했습니다. 단, 테스트에서만 사용한다고 팀에서 약속한다고 가정합니다.
=> 만약 getter가 적당하지 않다고 판단된다면 void를 리턴하는 command에서는 상태에 대해서 어떻게 테스트할 수 있을까요?
```
이럴 땐, 객체대 객체 비교로 검증할 수 있을 것 같아요. (equals and hashCode)
```
question의 delete 메서드에 대해서 테스트할 때, answer에 대해서도 테스트했는데 이게 옳은 방법인지 궁금합니다. delete 메서드가 기대하는 동작은 question / answer에 대해 deleted = true하는 동작과, deleteHistory를 더하는 동작이라 함께 테스트했습니다. 그러나, question의 테스트지만 answer에 대해서 의존하기 때문에 단위테스트지만 외부에 영향을 받는 게 맞는 것인가? 하는 생각이 들었습니다.
```
저는 검증하지 않는 편이긴 한데요. 왜냐하면, Answer#delete( ) 메소드에 대해서 테스트 코드를 이미 작성했기 때문이에요~
그런데 Question#delete( ) 메소드 내에서 복잡한 로직 과정을 통해 Answer#delete( ) 메소드가 실행 여부가 판단된다면 이 땐  Answer#delete( ) 메소드가 호출되었는지를 검사하기 위한 verify 단계만 추가할 것 같아요. 😄 
```
1단계에서 제시한 그림은 delete에서 DeleteHistories까지 처리하는 그림을 제시했는데, deleteHistories라는 메서드를 만들어서 delete=true하는 동작과 deleteHistories를 save하기 위해 원하는 List를 만드는 deleteHistories 메서드를 분리하는 것도 적절하지 않나? 라는 생각을 했습니다. 이 편이 메서드를 더 잘게 쪼개는 것 같기도 하고, deleteHistory에 대한 요구조건이 바뀌었을 때 더 쉽게 짐작할 수 있을 것이라는 생각이 들었습니다.
```
좋은 고민을 하셨네요! 개인적으로 저는 delete=true는 삭제 로직인 것 같아서 delete( ) 메소드에 있는게 적합하지 않나라는 생각을 하는 편이예요! 😄 그리고 deleteHistories 메소드를 별도로 만들 수도 있지만, 현재 요구사항에서는 이력 생성에 대한 로직이 복잡하지 않아서 별도 메소드로 만들기 보단 delete( ) 메소드 내에서 DeleteHistory를 생성해서 반환하게 하는 편이랍니다. 이건 제 개인적인 의견이니(= 정답은 아니니) 참고만 부탁 드려요 😄

2023-05-30 23:57 UTC, serverwizard requested changes
1단계 레거시 코드 리팩토링 미션 잘해주셨네요 👍 

질문주신 부분과 함께 몇가지 코멘트 남겨뒀는데 확인 부탁 드릴게요 🙇 

그럼 오늘 하루도 좋은 하루 보내세요 😄

2023-05-30 23:57 UTC, serverwizard commented on src/main/java/nextstep/qna/domain/Answer.java
> +        if (loginUser != this.writer) {
현재 코드에서는 reference로 비교하는 것 같은데요. 값으로 비교하는 건 어떨까요?

2023-05-30 23:57 UTC, serverwizard commented on src/main/java/nextstep/qna/domain/Answer.java
> +    public void delete(NsUser loginUser, List<DeleteHistory> deleteHistories) throws CannotDeleteException {
List< DeleteHistory >를 메소드 인자로 받아서 처리할 수도 있지만, 메소드 내에서 DeleteHistory를 생성해서 반환하게 할수도 있을 것 같네요 :)

2023-05-30 23:57 UTC, serverwizard commented on src/main/java/nextstep/qna/domain/Question.java
> +        if (loginUser != writer) {
reference로 비교하고 있네요~ 값 비교로 변경하면 좋을 것 같아요 :)

2023-05-30 23:57 UTC, serverwizard commented on src/main/java/nextstep/qna/domain/Answer.java
> +        deleteHistories.add(new DeleteHistory(ContentType.ANSWER, this.id, this.writer, LocalDateTime.now()));
중요한 건 아니지만, LocalDateTime.now()를 인자로 받으면 질문과 답변 삭제 시간이 동일하게 남을 것 같네요! :)

2023-05-30 23:57 UTC, serverwizard requested changes
1단계 레거시 코드 리팩토링 미션 잘해주셨네요 👍 

질문주신 부분과 함께 몇가지 코멘트 남겨뒀는데 확인 부탁 드릴게요 🙇 

그럼 오늘 하루도 좋은 하루 보내세요 😄

2023-05-30 23:57 UTC, serverwizard commented
```
getter는 열어둔다 : JPA를 사용하면 getter를 사용하게 되고, delete 메서드가 command이기 때문에 상태에 대해 테스트하기 
어려워 getter는 남기기로 결정했습니다. 단, 테스트에서만 사용한다고 팀에서 약속한다고 가정합니다.
=> 만약 getter가 적당하지 않다고 판단된다면 void를 리턴하는 command에서는 상태에 대해서 어떻게 테스트할 수 있을까요?
```
이럴 땐, 객체대 객체 비교로 검증할 수 있을 것 같아요. (equals and hashCode)
```
question의 delete 메서드에 대해서 테스트할 때, answer에 대해서도 테스트했는데 이게 옳은 방법인지 궁금합니다. 
delete 메서드가 기대하는 동작은 question / answer에 대해 deleted = true하는 동작과, deleteHistory를 더하는 동작이라 
함께 테스트했습니다. 그러나, question의 테스트지만 answer에 대해서 의존하기 때문에 
단위테스트지만 외부에 영향을 받는 게 맞는 것인가? 하는 생각이 들었습니다.
```
저는 검증하지 않는 편이긴 한데요. 왜냐하면, Answer#delete( ) 메소드에 대해 테스트 코드를 이미 작성했기 때문이에요~
그런데 Question#delete( ) 메소드 내에서 복잡한 로직 과정을 통해 Answer#delete( ) 메소드의 실행 여부가 판단된다고 한다면 이럴 땐  Question#delete( ) 메소드 내에서 Answer#delete( ) 메소드가 호출되었는지 정도만 verify 단계로 검증할 것 같아요. 😄 
```
1단계에서 제시한 그림은 delete에서 DeleteHistories까지 처리하는 그림을 제시했는데, deleteHistories라는 메서드를 만들어서 
delete=true하는 동작과 deleteHistories를 save하기 위해 원하는 List를 만드는 deleteHistories 메서드를 분리하는 것도 적절하지 않나? 
라는 생각을 했습니다. 이 편이 메서드를 더 잘게 쪼개는 것 같기도 하고, deleteHistory에 대한 요구조건이 바뀌었을 때 더 쉽게 짐작할 수 있을 
것이라는 생각이 들었습니다.
```
좋은 고민을 하셨네요! 개인적으로 저는 delete=true는 삭제 로직인 것 같아서 delete( ) 메소드에 있는게 적합하지 않나라는 생각을 하는 편이예요! 😄 그리고 deleteHistories 메소드를 별도로 만들 수도 있지만, 현재 요구사항에서는 이력 생성에 대한 로직이 복잡하지 않아서 별도 메소드로 만들기 보단 delete( ) 메소드 내에서 DeleteHistory를 생성해서 반환하게 하는 편이랍니다. 이건 제 개인적인 의견이니(= 정답은 아니니) 참고만 부탁 드려요 😄

2023-06-01 13:00 UTC, JerryK026 commented on src/main/java/nextstep/qna/domain/Answer.java
> +        deleteHistories.add(new DeleteHistory(ContentType.ANSWER, this.id, this.writer, LocalDateTime.now()));
이 부분은 이해가 잘 되지 않습니다 ㅠㅠ 기존에 서비스 로직에 있던 걸 그대로 가져온 건데, 혹시 어떤 게 문제일까요? 질문과 답변 시간이 동일하게 남지 않으면 어떠한게 문제인지 잘 모르겠습니다

2023-06-01 13:01 UTC, JerryK026 commented
리뷰 감사드립니다!! 덕분에 평소 궁금했던 부분에 대해서 힌트를 얻은 것 같네요!! 특히 equals 부분은 도움이 많이 된 것 같아요 ㅎㅎㅎ

2023-06-02 04:23 UTC, javajigi approved these changes
피드백 반영 잘 했네요. 👍 
어제 마지막 강의가 끝났지만 이 미션의 남은 단계를 저와 함께 진행해 보시죠.
어제 강의 내용은 2, 3단계까지 진행한 후에 볼 것을 추천 드려요.

2023-06-02 04:23 UTC, merged