수강신청: 3단계 - 수강신청(DB 적용)
next-step/java-lms pull request #156
Opened 2023-05-30 17:51 UTC by wooklab

맞게 구현한것인지 모르겠네요 😅 
3단계 리뷰 요청드립니다..! 🙇

2023-05-31 13:51 UTC, sah3122 requested changes
3단계 미션 구현 잘해주셨습니다 👍 
이번 기회에 도메인 객체와 DB에 저장되는 Entity를 분리하여 정의해보는것도 좋을것 같습니다 😄 
몇가지 생각거리를 남겨두었는데 확인 부탁드려요 😄

2023-05-31 13:51 UTC, sah3122 commented on src/main/java/nextstep/courses/domain/session/Session.java
> +public class Session {
`과정(Course)은 기수 단위로 여러 개의 강의(Session)를 가질 수 있다.` 라는 요구사항을 만족할수 있는 도메인 모델을 정의해보는건 어떨까요 ?

2023-05-31 13:51 UTC, sah3122 commented on src/main/java/nextstep/courses/domain/student/Students.java
> +public class Students {
Student 도메인은 Session에 등록되는 순간 생성되는 도메인으로 볼수 있네요 😄 
Session 패키지 하위로 이동하고, 생성자에 대한 접근 제어자를 public 으로 정의하여 외부 클래스에서 생성하지 못하도록 정의해보는것도 좋을것 같습니다 😄

2023-05-31 13:51 UTC, sah3122 commented on src/main/java/nextstep/courses/service/SessionService.java
> +        userRepository.findByUserId(userId)
User가 존재하지 않는다면 UserNotFoundException과 같은 에러를 뱉는건 어떻게 생각하시나요 ?

2023-05-31 13:51 UTC, sah3122 commented on src/main/java/nextstep/courses/service/SessionService.java
> +public class SessionService {
수강신청이란 요구사항을 만족하기 위해 SessionService라고 정의해주셨는데, 실제 로직은 만들어진 Session에 수강생을 등록하는 로직입니다. 

개인적으로 Service 네이밍을 정의할땐 무의식적으로 도메인네이밍만 사용하곤 하였는데, 어떤 역할을 하는 서비스인지 조금더 명확하게 나타내는것도 가독성 및 서비스 레이어의 코드가 커지지 않도록 정의할수 있어서 좋더라구요 ㅎㅎ 
register 메서드를 위한 `SessionRegisterService`와 같이 행위를 기반으로 정의해보는건 어떻게 생각하시나요 ?

2023-05-31 13:51 UTC, sah3122 commented on src/main/java/nextstep/courses/exception/EnrolledStudentNotFoundException.java
> +package nextstep.courses.exception;
도메인을 기준으로 패키지를 나누어주신 김에 exception도 도메인 하위로 이동해보는건 어떨까요 ?

2023-05-31 13:51 UTC, sah3122 commented on src/main/java/nextstep/courses/service/SessionService.java
> +                );
람다식의 중첩은 오히려 가독성을 떨어트리는 경향이 있습니다. 
로직을 풀어서 정의해보는것도 좋을것 같아요 😄

2023-05-31 13:51 UTC, sah3122 commented on src/main/java/nextstep/courses/domain/student/Student.java
> +    public Student() {
기본생성자를 정의해주신 이유가 있을까요 ?

2023-05-31 14:29 UTC, wooklab commented on src/main/java/nextstep/courses/domain/session/Session.java
> +public class Session {
@sah3122 
해당 요구사항은 미션 시작시 이미 구현된것으로 이해하였는데요.
혹시 조금더 상세한 설명을 부탁드려도 될까요?

2023-05-31 14:51 UTC, wooklab commented on src/main/java/nextstep/courses/service/SessionService.java
> +        userRepository.findByUserId(userId)
applied cid: 0fbf702c4cd9b55e565e23dd65e560f0930df1d0

2023-05-31 14:51 UTC, wooklab commented on src/main/java/nextstep/courses/service/SessionService.java
> +                );
앞서 피드백 주신 부분(UserNotFoundException)과 함께 처리하였습니다. 🙇 

applied cid: 0fbf702c4cd9b55e565e23dd65e560f0930df1d0

2023-05-31 14:53 UTC, wooklab commented on src/main/java/nextstep/courses/domain/student/Student.java
> +    public Student() {
Course 기준으로 컨벤션을 맞추기 위해 추가하였습니다.
불필요한 부분은 추가하지 않는게 나을까요? 🤔

2023-05-31 15:13 UTC, wooklab commented on src/main/java/nextstep/courses/exception/EnrolledStudentNotFoundException.java
> +package nextstep.courses.exception;
확인하다보니 courses 하위로 도메인 기준 패키징이 조금 어색한거 같아
전체적으로 리패키징 하였습니다.
- as-is
  - nextstep.courses.domain.course
  - nextstep.courses.domain.session
  - nextstep.courses.domain.student
- to-be
  - nextstep.courses
  - nextstep.sessions
  - nextstep.students

applied cid: 76e77e3057c8b8bcd9f621afec020e201e935de5

2023-05-31 15:25 UTC, wooklab commented on src/main/java/nextstep/courses/service/SessionService.java
> +public class SessionService {
말씀해주신대로 추상적인 서비스명은 다양한 코드를 암묵적으로 허용하게 되는거 같습니다 🤔 
구체적인 서비스명을 사용한다면 정의된 이름에 맞는 역할만 수행하도록 암묵적인 가이드가 되는거 같네요 👍 
그리고 구체적인 서비스명을 정의하기 위한 기준으로 제시해 주신 행위 기반도 매우 좋은 방법인 것 같습니다. 😃 
놓치고 있던 부분인데 감사합니다. 🙇 

applied cid: edebc1464093520fae1cdec4750b64bf208d5163

2023-06-02 00:40 UTC, sah3122 commented on src/main/java/nextstep/courses/domain/session/Session.java
> +public class Session {
Course 도메인에는 List<Session>에 대한 참조가 존재하지만 DB Table 을 본다면 Session과 Course와의 연관 관계를 찾을수 없습니다. 
실제 비즈니스가 동작하는 경우 두 도메인간의 참조가 필요할것 같아 남겨두었습니다 😄

2023-06-02 01:04 UTC, sah3122 commented on src/main/java/nextstep/courses/domain/student/Student.java
> +    public Student() {
불필요한 코드는 제거하는것이 좋을것 같아요 😄

2023-06-02 04:47 UTC, sah3122 commented on src/main/java/nextstep/courses/domain/student/Students.java
> +public class Students {
infrastucture 에서 사용하는 객체를 분리하지 않으면 반영이 어렵겠네요 .. ! 
참고만 해주시면 됩니다 😄

2023-06-02 04:59 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
한가지 코멘트 남겨두었는데 다음 미션을 진행하며 확인 부탁드려요 !

2023-06-02 04:59 UTC, merged