3단계 - 수강신청(DB 적용)
next-step/java-lms pull request #158
Opened 2023-05-30 19:23 UTC by GangBean

## 2단계
- DB관리가 필요한 객체에만 id를 남겼습니다
- 필요한 validation 추가했습니다
- 중복 로직 메소드로 추출했습니다
- Name 객체는 DB 추가시에 DB 스키마와 일관성 유지를 위한 입력값 검증이 필요하지 않을까 싶어 분리해뒀는데, 필요가 없는 부분일까요?

## 3단계
- JDBC로 repository 구현체를 구현했습니다.
- N:N 관계 해소를 위한 매핑테이블을 만들었습니다 : sessions_users, cohort_sessions

## 질문드립니다
Q1. 매핑테이블은 애플리케이션 레이어에서, 연관 테이블의 도메인 객체와 분리되어 처리되는 경우가 없을것 같아서 따로 클래스를 만들지 않았는데, 별도 객체로 관리하는게 좋은 방법인지 궁금합니다.
Q2. 다른 도메인과 연관관계를 갖는 도메인의 경우, DB에서 데이터를 조회해올때 연관관계의 객체데이터를 추가로 조회해와야 할 것 같습니다. 이 때 다른 객체의 repository를 활용했는데, 해당 repository 들도 의존관계주입을 통해 처리하는게 좋은지 궁금합니다.

2023-05-31 16:42 UTC, parkeeseul requested changes
3단계 미션 열심히 진행해 주셨네요 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다 😄

2023-05-31 21:58 UTC, GangBean commented on src/main/java/nextstep/courses/domain/Cohort.java
> +    }
아 넵넵 순서가 안맞는 클래스가 많네요 ㅎㅎ 순서 조정했습니다!

2023-05-31 22:00 UTC, GangBean commented on src/main/java/nextstep/courses/domain/session/Duration.java
> +    public Duration(LocalDateTime startDate, LocalDateTime endDate) throws InvalidTimeRangeException {
아 아닙니다 제가 구현을 잘못했네요 try catch 로 반드시 에러처리해줘야 하는 오류가 아니라서 UncheckedException으로 수정했습니다.

2023-05-31 22:09 UTC, GangBean commented on src/main/java/nextstep/courses/domain/session/Duration.java
> +public class Duration {
넵 기본 제공 클래스 아닌 TimeRange로 변경했습니다!

2023-05-31 23:15 UTC, GangBean commented on src/main/java/nextstep/courses/infrastructure/JdbcCohortRepository.java
> +    public int update(Cohort cohort) {
넵 추가했습니다!

2023-06-01 00:55 UTC, GangBean commented on src/main/java/nextstep/courses/infrastructure/JdbcCohortRepository.java
> +        String cohortSessionsInsertSql = "insert into cohort_sessions(cohort_id, sessions_id) values(?, ?)";
넵 동작의 원자성을 간과했네요. @Transactional 을 추가했습니다.

2025-04-09 00:33 UTC, closed without merging