Step3 코드리뷰 요청드립니다.
next-step/java-lms pull request #173
Opened 2023-05-31 18:32 UTC by woorido

2023-06-01 04:36 UTC, nokchax requested changes
안녕하세요, 효정님!
DB와 맵핑도 전반적으로 잘 구현해 주셨어요 👍 
질문 주신 것에 대한 답변과 함께, 
몇가지 보완해야 할 부분에 대해 피드백 남겼으니 확인 부탁드립니다 🙇

2023-06-01 04:36 UTC, nokchax commented on src/main/resources/schema.sql
> +create table session
created_at, updated_at 도 추가되어야 할 것 같아요

2023-06-01 04:36 UTC, nokchax commented on src/main/resources/schema.sql
> +    id         bigint not null,
```
    id               bigint generated by default as identity,
```
이 누락된 것으로 보여 코멘트 남길게요

2023-06-01 04:36 UTC, nokchax commented on src/main/java/nextstep/sessions/domain/SessionType.java
> +package nextstep.sessions.domain;
SessionType과 같이 오해하기 쉬운 이름 보다는 유무료와 관련된 것임을 표현할 수 있는 이름이 좋을것 같아요

2023-06-01 04:36 UTC, nokchax commented on src/main/java/nextstep/sessions/domain/SessionPeriod.java
> +    }
period 쪽에 startDate < endDate 임을 검증할 필요가 있지 않을까요?

2023-06-01 04:36 UTC, nokchax commented on src/main/java/nextstep/sessions/domain/SessionStudents.java
> +public class SessionStudents {
최대 인원 수 만큼만 수강 등록을 할 수 있기 때문에 서로 연관있는
SessionCapacity 와 함께 묶여야 할 것 같아요

2023-06-01 04:36 UTC, nokchax commented on src/main/java/nextstep/sessions/domain/SessionStudents.java
> +    private Map<Long, NsUser> studentMap;
list와 map을 함께 쓰면 데이터의 중복이 발생하지 않을까요?
map을 제거하고 list 대신 set을 사용해 보는 건 어떨까요?

2023-06-01 04:36 UTC, nokchax commented on src/main/java/nextstep/sessions/domain/SessionStudents.java
> +    public void enrollStudent(NsUser nsUser) {
👍

2023-06-01 04:36 UTC, nokchax commented on README.md
> +* 앞 단계에서 구현한 도메인 모델을 DB 테이블과 매핑하고, 데이터를 저장한다
service 레이어도 한번 구현해 주시겠어요?
유저가 세션에 등록하는 기능을 구현한다고 생각하고 관련된 것을을 구현해주세요~!

2023-06-01 04:36 UTC, nokchax commented on src/main/java/nextstep/infrastructure/JdbcSessionRepository.java
> +                SessionStatus.valueOf(rs.getString("session_status")),
valueOf 대신 essionImageType에서 사용하는 것 처럼 정적 함수를 통해 enum을 찾아오면 어떨까요?

2023-06-01 04:36 UTC, nokchax commented on src/main/java/nextstep/infrastructure/JdbcSessionRepository.java
> +    public Session findById(Long id) {
session을 찾을때 수강 신청한 학생들에 대한 정보도 같이 가져와야 하지 않을까요?

2023-06-01 04:36 UTC, nokchax commented on src/main/java/nextstep/sessions/domain/Session.java
> +    private Course course;
https://github.com/next-step/java-lms/pull/173#issue-1734774189 에 대한 답변입니다.
`또 다른 방법으로는 Course에 List<Session> 를 넣어 Session 을 참조하는 로직도 생각했는데`라고 말씀 주셨는데,
현재 구현해 주신 방식과 위의 방식은 대안이 아니라 서로 별개의 사항이에요
session에서 course를 가지는 방식으로만 구현할 수도 있고
course에서 List<Session> 을 가지는 방식으로만 구현할 수 도 있으며
위의 두 방식을 합쳐서 구현할 수 도있죠.

결국 서비스에 필요한 방식에 따라 위의 세가지 방식을 선택하면 되는데요,
session에서 course를 참조할 일이 많지만, course에서 session을 참조할 일이 없다면 1번으로 충분 할 것이며,
session에서 course를 참조할 일은 없지만, course에서 session을 참조할 일이 많다면 2번으로 구현할 수 있고,
양 도메인에서 서로 서로를 참조할 일이 많다면 3번으로 구현할 수 있죠...

정답은 없어요, 필요에 따라 구현해 주시면 됩니다. :)

2023-06-01 04:36 UTC, nokchax commented on src/main/java/nextstep/sessions/domain/SessionStudents.java
> +public class SessionStudents {
https://github.com/next-step/java-lms/pull/173#issue-1734774189 SessionStudents에 대한 답변입니다.
수강 신청을 하게 되면, 그 정보를 db 어딘가에 저장을 해야하는데, 현재는 저장할 테이블이 보이지 않아요.
NsUser와 정보가 겹치지 않고, 수강 정보를 저장하기 위해서,
session 의 id와 user의 id 정보를 저장하는 session_students 테이블을 만들면 되지 않을까요?

2023-06-01 04:36 UTC, nokchax requested changes
안녕하세요, 효정님!
DB와 맵핑도 전반적으로 잘 구현해 주셨어요 👍 
질문 주신 것에 대한 답변과 함께, 
몇가지 보완해야 할 부분에 대해 피드백 남겼으니 확인 부탁드립니다 🙇

2023-06-01 09:58 UTC, woorido commented on src/main/java/nextstep/infrastructure/JdbcSessionRepository.java
> +                SessionStatus.valueOf(rs.getString("session_status")),
이렇게 피드백 주신 이유가 of() 를 추가하여 사용할 경우 예외 메세지를 명확히 설정할 수 있어서일까요?

2023-06-01 16:45 UTC, woorido commented
안녕하세요. 피효정입니다.
service 레이어 구현 제외하고 코드리뷰 주신 내용들 적용해봤습니다.
오늘까지 리뷰 요청이라 일단 코드리뷰 요청 드립니다. 

말씀 주신 의도가 궁금해서 질문도 두 개 달았는데 확인 부탁드립니다.
세심한 코드리뷰 진심으로 감사드립니다. 잘 부탁드립니다!

2023-06-01 17:22 UTC, nokchax commented on src/main/java/nextstep/infrastructure/JdbcSessionRepository.java
> +                SessionStatus.valueOf(rs.getString("session_status")),
매칭되는 값이 없을 경우 예외 메세지를 정의할 수 있는 점도 있고,
매칭되는 값이 없을 경우 기본값을 리턴할 수 도 있는 장점이 있어요

2023-06-01 17:31 UTC, nokchax commented on src/main/java/nextstep/infrastructure/JdbcSessionRepository.java
> +    public Session findById(Long id) {
join 쿼리를 사용하지 않고, 객체를 생성할 때 쿼리를 두번 날려서, 맵핑하는 방식도 있어요

2023-06-01 17:36 UTC, nokchax requested changes
안녕하세요, 효정님~!
피드백 적용 잘 해주셨는데, 아직 추가 해야 할 부분이 있어 추가 피드백 드렸습니다. 
다음 단계는 우선 피드백에 대해 정리한 뒤에 진행하도록 하시죠 :)

2023-06-01 17:36 UTC, nokchax commented on src/main/java/nextstep/infrastructure/JdbcSessionRepository.java
> +                SessionPaymentType.of(rs.getString("session_type")),
👍

2023-06-01 17:36 UTC, nokchax commented on src/main/java/nextstep/sessions/domain/SessionStudent.java
> +    private Long nsUserId;
현재는 DB에 있는 정보를 그대로 가져왔는데요,
이렇게 보면 객체지향 이라기 보다는 단순 데이터 덩어리를 다루는 것으로 보이네요
SessionStudents 클래스 내부에 Set<SessionStudent> students 로 저장을 하고 있는데
Set<NsUser> students 로 표현하면 어떨까요? 현재와 어떤 차이가 있을까요?

테이블은 그대로 둔 상태를 가정하고 말씀 드린거예요

2023-06-01 17:36 UTC, nokchax commented on src/main/resources/schema.sql
> +create table session_student
👍

2023-06-01 17:37 UTC, nokchax commented on src/main/java/nextstep/BaseTime.java
> +package nextstep;
lms 단계 마무리 까지는 피드백 드릴게요, 천천히 하셔도 상관없으니 꼭 구현해 보세요

2023-06-02 05:11 UTC, woorido commented on src/main/java/nextstep/BaseTime.java
> +package nextstep;
감사합니다!!

2023-06-11 07:17 UTC, woorido commented
안녕하세요. 피효정입니다. 리뷰 요청이 늦어 진심으로 죄송합니다.

`Set<NsUser>` 와 `Set<SessionStudent>` 로 표현하는 방법에 대해 생각해 봤습니다.
`Set<NsUser>` students 로 표현하면 NsUser 객체 집합을 저장하게 되어, 세션 조회 시 세션 참여 학생들의 정보까지 조회가 가능합니다. 
`Set<SessionStudent>` students 로 표현하면, 세션과 학생의 관계만을 저장하여 세선에 참여하는 학생들의 목록을 확인할 수 있어 학생들의 정보에 접근하기 위해서는 추가적인 조회 과정이 필요합니다.

사용 목적에 따라 선택하여 사용하면 되는데, 사용자 정보를 모두 얻고 싶어 `Set<NsUser>` 로 수정했습니다.

그리고 말씀처럼 DB 에 있는 정보를 그냥 가져다 쓰고 있어 해당 부분도 수정했습니다.

제가 잘 이해했는지 모르겠습니다. 확인 부탁드립니다. 항상 감사합니다.

2023-06-11 23:54 UTC, nokchax approved these changes
안녕하세요 효정님~!
오랜만에 인사드리네요, 피드백 잘 적용해 주셨고 👍 
소소한 코멘트 남겨봤는데, 다음 단계 진행하시면서 고민해 주세요~!

2023-06-11 23:54 UTC, nokchax commented on src/main/java/nextstep/sessions/service/SessionService.java
> +        sessionRepository.saveUser(newSession.getId(), nsUser);
session을 가져올 때 수강 정보까지 함께 읽어와 객체를 리턴 해보면 어떨까요?

2023-06-11 23:54 UTC, nokchax commented on src/main/java/nextstep/sessions/infrastructure/JdbcSessionRepository.java
> +    public int saveUser(Long sessionId, NsUser nsUser) {
saveUser 보다 enrollUser 와 같은 함수명은 어떨까요?

2023-06-11 23:54 UTC, nokchax commented on src/main/java/nextstep/sessions/service/SessionService.java
> +        newSession.enrollStudent(nsUser);
👍

2023-06-11 23:54 UTC, nokchax commented on src/main/java/nextstep/sessions/domain/SessionStudents.java
> +        return students.stream().filter(value -> value.getId().equals(nsUserId)).findFirst().isPresent();
set이라면 set이 제공하는 contains를 활용하면 되지 않을까요?

2023-06-12 01:27 UTC, merged