# 수강신청 - Step1  미션 진행 완료입니다.
next-step/java-lms pull request #18
Opened 2023-05-19 14:13 UTC by juno-junho

2023-05-22 07:16 UTC, mskangg requested changes
안녕하세요!
이번 미션 리뷰를 맡은 강민수입니다 🙇 
전체적으로 깔끔하게 잘 구현해주셨네요!
체크리스트도 꼼꼼히 작성주시고 👏 
소소한 피드백 남겨드렸으니 확인하시고 반영 부탁드려용 😄

2023-05-22 07:16 UTC, mskangg commented on README.md
> +  - [x] answer을 add 하면 question에 대한 DeleteHistory를 만들어 리스트에 추가한다.
체크리스트 👍

2023-05-22 07:16 UTC, mskangg commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(deleteHistories.getDeleteHistories());
DeleteHistories 를 서비스가 생성할 필요가 있을까요? 🤔 

```suggestion
        DeleteHistories deleteHistories = question.delete(loginUser);
        deleteHistoryService.saveAll(deleteHistories.getDeleteHistories());
```

이렇게 객체에게 메세지를 보낸 후 메세지에 대한 결과를 받는 방식은 어떠신가요?

2023-05-22 08:33 UTC, mskangg commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(deleteHistories.getDeleteHistories());
> 서비스에 제가 생성 한 이유는 delete() 메서드를 호출한 반환타입이 DeleteHistories 인것이 부자연 스러워 그랬는데 return type과 메서드 이름에는 연관관계가 없어도 되는건가요?

부자연스러운 이유가 어떤것이었을까요??
매개변수로 DeleteHistories 를 받는것이 좀더 자연스러우셨을까요?
이유가 궁금합니다!

2023-05-22 08:37 UTC, juno-junho commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(deleteHistories.getDeleteHistories());
사실 메서드 사용시 파라미터 개수가 적으면 적을수록 이해하기 쉽고 명확도는 올라가는것 같습니다.

그렇다 보니 민수님이 말하신 방식을 사용하는 것이 더 나은 선택 같네요 ㅎㅎ

감사합니다!

2023-05-22 08:40 UTC, juno-junho commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(deleteHistories.getDeleteHistories());
저도 사실 어떻게 deleteHistories를 생성해서 넘길까 고민이 많았는데, 앞으로 파라미터로 넘기는 대신 반환타입을 사용하는 방식 쪽으로 작성해보갰습니다.

그것 보다 해당 deleteHistories 객체를 어디서 생성해야 할지가 애매하긴 한 것 같습니다.
상태값으로 가지는 것은 아닌것 같고, 메서드 파라미터로 넘겨 줘야 하는데, 위치를 선정하는데 있어서 애매한것 같아요.

2023-05-22 08:45 UTC, juno-junho commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(deleteHistories.getDeleteHistories());
아니면 answer 쪽 가장 depth의 끝 부분에서 생성하여 반환타입으로 넘겨주는게 맞을까요?

2023-05-22 09:44 UTC, mskangg commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(deleteHistories.getDeleteHistories());
@juno-junho

```java
// Answer.java
public DeleteHistory delete() {
    return DeleteHistory.createAnswer(this.id, this.writer);
}

// Question.java
public DeleteHistories delete() {
    DeleteHistories deleteHistories = new DeleteHistories();
    for(Answer answer : answers) {
        deleteHistories.add(answer.delete());
    }
    deleteHistories.add(DeleteHistory.createQuestion(this.id, this.writer);
    return deleteHistories;
}

// DeleteHistory.java
public static DeleteHistory createQuestion(String id, NsUser writer){
    return new DeleteHistory(ContentType.Question, id, writer);
}

public static DeleteHistory createAnswer(String id, NsUser writer){
    return new DeleteHistory(ContentType.Answer, id, writer);
}
```

이렇게 할수 있을것 같아요! (IDE 아니고 깃허브에서 코딩하니 문법이 틀릴 수 있어요 😢  양해바랍니다)

그러면 서비스에선

```java
DeleteHistories deleteHistories = question.delete();
```

이렇게 되겠고, 코드를 한글로 읽는다 생각하면
질문을 삭제하면? 삭제 이력이 나온다. 로 바로 해석될 수 있지 않을까요??

2023-05-22 09:44 UTC, mskangg requested changes
추가적으로 코멘트 남겨드렸습니다!
확인해주세요 https://github.com/next-step/java-lms/pull/18#discussion_r1200266148

그리고 의미없는 게터와 세터를 전부 삭제해주시고! 메서드 네이밍에 신경써주시면 좋을 것 같아요 😄

2023-05-22 10:23 UTC, juno-junho commented
말하신 대로 deleteHistory를 매개변수로 넘기지 않으니 가독성이 더 좋아진 것을 확인했습니다.

말씀하신 구조로 변경 해 보았습니다!

DeleteHistory를 생성하는 것을 static 메서드로 DeleteHistory에서 하는 것이 더 깔끔하고 책임을 잘 부여한 것이라고 생각이 되네요 :)

2023-05-22 10:26 UTC, juno-junho commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(deleteHistories.getDeleteHistories());
이런 설계는 가독성, 전체적 논리적 흐름을 고려해서 어느 클래스에 어떤 책임을 부여할지 결정하는 것인가요?

2023-05-23 06:22 UTC, mskangg approved these changes
> 이런 설계는 가독성, 전체적 논리적 흐름을 고려해서 어느 클래스에 어떤 책임을 부여할지 결정하는 것인가요?

넵 맞습니다! 😄 
`객체의 상태를 꺼내지 않고 메세지를 보내어 비즈니스를 구현한다` 를 항상 생각하고 구현한다면 도움이 되실거에요 👍 

피드백 반영 고생하셨습니다.
다음 단계 진행해주세요! 😄

2023-05-23 06:22 UTC, merged