Lms step3
next-step/java-lms pull request #183
Opened 2023-06-03 07:57 UTC by Highjune

- 첫 커밋(step2 코드 다시) 은 step2까지 코드를 다시 작성한 것입니다. 이전에 step1 작성 이후에 upstream/highjune 을 rebase 하지 않고, 이번 step2 에서 highjune 에서 rebase 하니 충돌이 많이 나더라구요. 

- 두 번째 커밋(session과 student 테이블 생성 ddl sql 작성) 부터 봐주시면 감사하겠습니다.

2023-06-04 04:01 UTC, javajigi requested changes
도메인 객체로 구현한 후 DB 적용하는 과정 어떤가요?
생각보다 쉽지 않죠?
그럼에도 불구하고 DB 적용하기 위해 노력한 흔적이 보이네요. 👍 
단, Student는 Session과 NsUser의 m:n 관계를 매핑하기 위한 테이블로 보여지는데요.
이 부분을 잘못 구현한 것은 아닌지 확인차 피드백 남겼어요.

2023-06-11 05:59 UTC, Highjune commented on src/main/java/nextstep/courses/service/SessionService.java
> +    public Session registerStudent(Long sessionId, Long studentId) {
@javajigi 아, NsUser 를 반드시 활용해야 하는 객체인지 몰랐습니다...! 반영하겠습니다.

2023-06-11 08:05 UTC, Highjune commented
@javajigi 

3단계 피드백 반영했습니다. 확인 부탁드립니다!^^

2023-06-12 01:31 UTC, javajigi approved these changes
피드백 반영하느라 수고했어요. 💯 
마지막 단계 진행하고 미션 마무리하시죠.

2023-06-12 01:31 UTC, merged