Step1 - 레거시 코드 리팩터링
next-step/java-lms pull request #2
Opened 2023-05-14 08:24 UTC by oneny

안녕하세요! 마지막 미션을 수행하는 허재원이라고 합니다!

미숙하지만 이번 미션 피드백 잘 부탁드리겠습니다! 감사합니다! :)

2023-05-15 05:19 UTC, mskangg requested changes
안녕하세요!
이번 미션 리뷰를 맡은 강민수입니다. 🙇 
전체적으로 깔끔하고 구조도 잘 잡아주셨습니다 👏 👏 
다만, 도메인 객체의 getter, setter를 다 남겨주셨더라구요!
전부 삭제한 뒤 필요한 메세지들을 작성하면서 추가하는 방식으로 하는것을 추천드립니다!
몇가지 피드백 남겨드렸으니 확인 부탁드려요 🙇

2023-05-15 05:19 UTC, mskangg commented on README.md
> +  - QnaService의 `deleteQuestion()` 메서드에 대한 단위 테스트는 `src/test/java` 폴더의 `next.qna.service.QnaServiceTest`이다.
👍

2023-05-15 05:19 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Answer.java
> +  private NsUser writer;
NsUser의 Ns는 무엇인가용? 🤔

2023-05-15 05:19 UTC, mskangg commented on src/test/java/nextstep/qna/service/QnaServiceTest.java
> +  @Mock
QnaServiceTest 는 수정된부분이 없는거죵? 👏 
요구사항이 바뀌지 않은 리팩토링이니 테스트코드는 온전히 같아야하거든용

2023-05-15 05:19 UTC, mskangg commented on src/main/java/nextstep/qna/service/QnAService.java
> +  }
비즈니스를 도메인객체로 잘 할당해주셨군요 💯 💯 
`DeleteHistories` 일급컬렉션까지 👍

2023-05-15 05:19 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Question.java
> +  }
getter 와 setter를 전부 삭제하고 필요한 메서드를 따로 할당해보시는건 어떠신가요? 🤔

2023-05-15 05:19 UTC, mskangg commented on src/main/java/nextstep/qna/domain/DeleteHistories.java
> +    deleteHistories.add(new DeleteHistory(ContentType.QUESTION, question.getId(), question.getWriter(), LocalDateTime.now()));
`question.delete()` 로 메세지화하는건 어떠신가용

그리고 `question.getId(), question.getWriter(), LocalDateTime.now()`이처럼 값을 꺼내서 사용하지 않고
`DeleteHistory deleteHistory = question.delete()` 로 리턴받는건 어떠신가요?

질문을 삭제했더니, 삭제이력이 나온다. 라는 의도가 보여할 것 같아요!

2023-05-15 10:39 UTC, oneny commented on src/main/java/nextstep/qna/domain/Answer.java
> +  private NsUser writer;
아하 축약 금지인데,,, 너무 자연스럽게 사용하고 있었네요..ㅠㅠ 수정하겠습니다!

2023-05-15 10:40 UTC, oneny commented on src/test/java/nextstep/qna/service/QnaServiceTest.java
> +  @Mock
아이고 원래대로 고쳐놓겠습니다!

2023-05-15 10:41 UTC, oneny commented on src/main/java/nextstep/qna/domain/DeleteHistories.java
> +    deleteHistories.add(new DeleteHistory(ContentType.QUESTION, question.getId(), question.getWriter(), LocalDateTime.now()));
아하 그렇네요... 다시 수정해보겠습니다!!ㅎㅎㅎ

2023-05-16 04:40 UTC, mskangg approved these changes
피드백 반영 잘해주셨습니다 👍 
소소한 피드백 남겨드렸으니 확인 부탁드립니다 🙇 
그럼 다음 단계 진행해주세요! 🔥

2023-05-16 04:40 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Answer.java
> +  private NextStepUser writer;
NextStepUser 였군요 ㅎㅎ

2023-05-16 04:40 UTC, mskangg commented on src/main/java/nextstep/qna/domain/DeleteHistories.java
> +  }
unmodifiableList 로 하셨네용 👍 
잘아시겠지만 실질적으로 컬렉션의 불변이 이뤄지고 있진 않습니다!
관련된 링크 남겨드릴게용~ 😄 

https://hudi.blog/ways-to-copy-collection/

2023-05-16 04:40 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Question.java
> +  }
👍

2023-05-16 04:40 UTC, merged