Step1 - 레거시 코드 리팩터링
next-step/java-lms pull request #255
Opened 2023-11-28 15:28 UTC by jikimee64

용주님 안녕하세요. 😁
1단계 - 레거시 코드 리팩터링 미션 완료 하였습니다.

이전 콘솔 기반 미션과는 많이 다르고 Base 코드도 있다보니 코드를 어디까지 수정해도 되는지 감이 잘 안 잡히네요..
ex) Answer과 Question이 양방향 관계인데 Answer에서 question 필드를 제거해도 되는지 등

피드백 부탁 드립니다. 감사합니다~!

※ 혹시 제가 코드 수정 한 방향성이 많이 다르다면 올바른 방향으로 갈 수 있도록 조언 부탁드립니다..!

2023-11-28 22:57 UTC, testrace requested changes
안녕하세요 우철님
1단계 깔끔하게 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겼두었는데 확인해 주시고 다시 리뷰 요청 부탁드려요

2023-11-28 22:57 UTC, testrace commented on README.md
> +* [X] 질문과 답변 삭제 이력에 대한 정보를 DeleteHistory를 활용해 남긴다.
기능 목록 작성👍 
객체별로 기능을 정리해 보셔도 좋을 것 같아요
```markdown
- [ ] 질문
  - [ ] soft delete
  - [ ] 작성자만 삭제 가능
  - [ ] ...
- [ ] 답변
  - [ ] soft delete
  - [ ] ...
```

2023-11-28 22:57 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answer.java
> +    }
테스트에서만 사용되는 생성자네요
생성자를 추가하는 것도 좋지만 해당 테스트 클래스 내에서 기존 생성자를 활용한 메서드를 추가해 보셔도 좋을 것 같아요
```java

@Test
void test() {
    Answer answer = javajigiAnswer(Q1);
    ...
}

public Answer javajigiAnswer(Question question) {
    return new Answer(JAVAJIGI, question, null);
}
```

2023-11-28 22:57 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answer.java
>      public Answer(NsUser writer, Question question, String contents) {
> Q. 이전 콘솔 기반 미션과는 많이 다르고 Base 코드도 있다보니 코드를 어디까지 수정해도 되는지 감이 잘 안 잡히네요..
ex) Answer과 Question이 양방향 관계인데 Answer에서 question 필드를 제거해도 되는지 등

A. 요구사항이 리팩터링이니 구현된 기능 변경없이 구조 변경해 주시면 될 것 같아요

2023-11-28 22:57 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answer.java
> +    }
답변 삭제에 대한 테스트가 없네요 😢 
답변은 작성자와 일치하지 않아도 삭제 가능한가요?

2023-11-28 22:57 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answers.java
> +    }
일급 컬렉션 👍 
질문을 삭제할 때에만 사용된다는 보장은 없으니 인자의 이름을 writer 로 변경하면 어떨까요?

2023-11-28 22:57 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answers.java
> +    }
답변 삭제와 마찬가지인데요
질문 삭제를 거치지 않고 답변들만 삭제하는 경우도 고려해 보시면 좋을 것 같아요

2023-11-28 22:57 UTC, testrace commented on src/main/java/nextstep/qna/domain/Question.java
> +        }
단위 테스트가 없네요 😢 
서로 다른 답변 작성자가 있는 질문을 삭제하는 테스트도 추가하면 어떨까요?

2023-11-28 22:57 UTC, testrace commented on src/main/java/nextstep/qna/domain/Question.java
> +    }
Question#delete 메서드를 호출하지 않고 이 메서드를 호출하면 실제 삭제 일시와 상관없는 DeleteHistory 객체가 생성됩니다
혹은 삭제 상태가 아니더라도 DeleteHistory 를 반환할 수 있는데요
삭제와 동시에 삭제 이력을 반환하면 어떨까요?

2023-11-28 22:57 UTC, testrace commented on src/test/java/nextstep/qna/domain/QuestionTest.java
> +    }
검증이 누락되었네요 😢

2023-11-28 22:57 UTC, testrace commented on src/test/java/nextstep/qna/domain/QuestionTest.java
> +    }
DisplayNam에는 `삭제 시 ~ 히스토리가 생성된다` 인데 delete 메서드를 호출하는 코드가 없네요 😢

2023-11-29 07:07 UTC, jikimee64 commented on src/main/java/nextstep/qna/domain/Answers.java
> +    }
답변이 한 개라도 일치하지 않을 경우 answer의 delete() 메소드에서 예외를 던지도록 구현했습니다!

2023-11-29 08:09 UTC, jikimee64 commented
아이고.. 😪 

다른 컴퓨터에서 clone 받고 수정 하다보니 git conifg username을 신경 못썼네요 ㅠㅠ
괜찮을까요..? 아니면 다시 브랜치 생성 후 MR 날려야 하나요 ㅠㅠ

2023-11-29 09:36 UTC, testrace approved these changes
안녕하세요 우철님
피드백 반영 잘해주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다음 단계 진행해 주세요

2023-11-29 09:36 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answer.java
> +    }
Answer 입장에서 다른 사람이 쓴 답변에 대해 알 수 없을 것 같은데요
예외 메시지가 적절한지 고려해 보시면 좋을 것 같아요

2023-11-29 09:36 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answers.java
> +            deleteHistories.add(new DeleteHistory(ContentType.ANSWER, answer.getId(), answer.getWriter(), LocalDateTime.now()));
Question 처럼 답변 삭제 이력은 Answer가 반환해주면 어떨까요?
```suggestion
            DeleteHistory deleteHistory = answer.delete(writer);
            deleteHistories.add(deleteHistory);
```

2023-11-29 09:36 UTC, testrace commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(question.delete(loginUser));
지역 변수를 선언하면 삭제 이력을 남긴다는 의도가 잘 드러날 것 같은데 어떠신가요?
디버깅에도 용이할 것 같아요
```suggestion
        final List<DeleteHistory> deleteHistories = question.delete(loginUser);
        deleteHistoryService.saveAll(deleteHistories);
```

2023-11-29 09:36 UTC, testrace commented on src/test/java/nextstep/qna/domain/AnswerTest.java
> +    }
DisplayName과 예외 메시지가 일치 하지 않아서 혼동이 생길 수 있을 것 같아요
기능의 의도와 맞는 메시지로 변경하면 좋을 것 같아요

2023-11-29 09:37 UTC, testrace commented
> 아이고.. 😪
> 
> 다른 컴퓨터에서 clone 받고 수정 하다보니 git conifg username을 신경 못썼네요 ㅠㅠ 괜찮을까요..? 아니면 다시 브랜치 생성 후 MR 날려야 하나요 ㅠㅠ

아무 지장 없으니 걱정 하지 않으셔도 됩니다 😃

2023-11-29 09:37 UTC, merged