수강신청 - 2) 도메인 모델
next-step/java-lms pull request #283
Opened 2023-12-01 09:16 UTC by gilbertlim

도메인 재설계를 두 번 경험했습니다..
1) Sessions와 Registration 도메인 의존 관계 변경
2) Registrations 도메인 삭제 및 관련 로직 Sessions로 이관

2023-12-01 14:37 UTC, testrace requested changes
안녕하세요 성진님
2단계 구현 잘해주셨네요 👍 
코드를 보니 많은 고민을 하신게 느껴지네요
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청 부탁드려요

2023-12-01 14:37 UTC, testrace commented on docs/step2.md
> +### 1. 과정(Courses)
기능 목록 작성 👍

2023-12-01 14:37 UTC, testrace commented on src/main/java/nextstep/sessions/domain/data/Session.java
> +    private Registrations registrations;
> 규칙 6: 모든 엔티티를 작게 유지한다.
> 규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

위 규칙을 지킬 수 있도록 도전해 보시면 좋을 것 같아요

2023-12-01 14:37 UTC, testrace commented on src/main/java/nextstep/sessions/domain/data/Session.java
> +    }
모든 생성자가 동일한 책임을 수행한다고 보기 어려울 것 같은데요
주 생성자와 부 생성자를 나누고 부 생성자는 this() 메서드를 활용해 보시면 어떨까요?

2023-12-01 14:37 UTC, testrace commented on src/main/java/nextstep/sessions/domain/data/Session.java
> +    }
중복 신청에 대한 검증을 추가하면 어떨까요?

2023-12-01 14:37 UTC, testrace commented on src/main/java/nextstep/sessions/domain/data/vo/Registrations.java
> +    List<Registration> registrations;
이 변수만 접근 범위가 다르네요 🤔

2023-12-01 14:37 UTC, testrace commented on src/main/java/nextstep/sessions/domain/data/vo/Registrations.java
> +    }
Registrations 클래스는 수강생 목록이라고 볼 수 있을 것 같은데요
인원제한에 대한 책임을 수행하면 응집도를 높일 수 있을 것 같은데 어떻게 생각하시나요?
```java
    public void enroll(Registration registration) {
        if (isFull()) {
            throw new IllegalArgumentException("...");
        }
        registrations.add(registration);
    }
```

2023-12-01 14:37 UTC, testrace commented on src/test/java/nextstep/sessions/domain/data/SessionTest.java
> +        Session s = new Session(new SessionType(PayType.PAID, 800000, 2), SessionState.RECRUITING);
> 규칙 5: 줄여쓰지 않는다(축약 금지).

변수명은 줄이지 않고 작성해 주시면 좋을 것 같아요

2023-12-01 14:37 UTC, testrace commented on src/test/java/nextstep/sessions/domain/data/SessionTest.java
> +        Session s = new Session(new SessionType(PayType.PAID, 800000L, 2), SessionState.RECRUITING);
테스트를 위한 생성자가 필요하다면 테스트 클래스 내부에서 메서드를 하나 만들어두고 사용해 보시면 좋을 것 같아요
중복 코드도 줄일 수 잇겠네요
테스트만을 위한 프로덕션 코드는 추천드리지 않습니다
```java
void test() {
    Session paidSession = paidSession(800000L, 2, RECRUITING);
    ...
}

private Session paidSession(long fee, int capacity, SessionState sessionState) {
    return new Session(...);
}

2023-12-01 14:37 UTC, testrace commented on src/test/java/nextstep/sessions/domain/data/SessionTest.java
> +    void 무료_강의() {
테스트의 의도를 조금 더 명확하게 표현해 주시면 좋을 것 같아요

2023-12-01 14:37 UTC, testrace commented on src/test/java/nextstep/sessions/domain/data/type/PayTypeTest.java
> +    }
isPaid 메서드의 결과는 두 가지이니 모두 검증하면 어떨까요?
isPaid 메서드의 내부를 아래처럼 변경해도 테스트는 성공을 할 것 같은데요
테스트를 신뢰할 수 있을지 고민해 보시면 좋을 것 같아요
```java
    public boolean isPaid() {
        return true;
    }
```

2023-12-01 14:37 UTC, testrace commented on src/test/java/nextstep/sessions/domain/data/vo/SessionTypeTest.java
> +    }
메서드명과 테스트 내용이 서로 반대네요 😢 
SessionTest에 중복 테스트가 있는 것 같은데 제거하면 어떨까요?

2023-12-01 14:37 UTC, testrace commented on src/test/java/nextstep/sessions/domain/data/vo/RegistrationsTest.java
> +    }
무엇을 검증하고자 하는지 이해하기 어려운데요
테스트의 의도를 명확하게 드러내면 어떨까요?
테스트가 애매하다면 객체의 책임으로 적절한지 고민해봐야하는 신호일 것 같아요

2023-12-01 14:37 UTC, testrace commented on src/main/java/nextstep/sessions/domain/data/Session.java
> +package nextstep.sessions.domain.data;
패키지명에 data는 어떤 의미인가요? (단순 질문입니다 😃 )

2023-12-02 06:08 UTC, gilbertlim commented on src/main/java/nextstep/sessions/domain/data/Session.java
> +    private Registrations registrations;
클래스를 분리하니 사용되는 인스턴스 변수에 따라 로직과 테스트코드가 분리되네요.
네이밍은 참 어렵습니다..

2023-12-02 06:15 UTC, gilbertlim commented on src/main/java/nextstep/sessions/domain/data/Session.java
> +    }
생성자에 의해 초기화되는 멤버변수가 1개일 경우에도 주 생성자에 null을 넣어 호출해야할까요?
우선은 멤버변수 1개인 경우는 주 생성자호출을 하지 않았습니다.

```java
    public Session(SessionType sessionType, CoverImage coverImage, LocalDateTime startDate, LocalDateTime endDate) {
        this.sessionInfo = new SessionInfo(
            new EnrollmentInfo(sessionType, SessionState.PREPARING),
            new OpenInfo(coverImage, new Duration(startDate, endDate))
        );
    }

    public Session(SessionInfo sessionInfo, Registrations registrations) {
        this.sessionInfo = sessionInfo;
        this.registrations = registrations;
    }
```

2023-12-02 06:51 UTC, gilbertlim commented on src/main/java/nextstep/sessions/domain/data/Session.java
> +    }
중복 체크는 유저+결제 정보 모두 일치하는 경우로 생각했으나,
검증 범위를 넓혀 Registration에 동일한 유저가 있으면 예외가 발생하도록 처리했습니다.

2023-12-02 06:52 UTC, gilbertlim commented on src/main/java/nextstep/sessions/domain/data/vo/Registrations.java
> +    List<Registration> registrations;
수정했습니다!

2023-12-02 07:03 UTC, gilbertlim commented on src/test/java/nextstep/sessions/domain/data/SessionTest.java
> +        Session s = new Session(new SessionType(PayType.PAID, 800000, 2), SessionState.RECRUITING);
수정했습니다!

2023-12-02 07:33 UTC, gilbertlim commented on src/test/java/nextstep/sessions/domain/data/SessionTest.java
> +        Session s = new Session(new SessionType(PayType.PAID, 800000L, 2), SessionState.RECRUITING);
수정했습니다!

2023-12-02 07:36 UTC, gilbertlim commented on src/test/java/nextstep/sessions/domain/data/SessionTest.java
> +    void 무료_강의() {
수정했습니다!

2023-12-02 07:38 UTC, gilbertlim commented on src/test/java/nextstep/sessions/domain/data/type/PayTypeTest.java
> +    }
놓치고 있던 부분이었네요! 수정했습니다.

2023-12-02 07:41 UTC, gilbertlim commented on src/test/java/nextstep/sessions/domain/data/vo/SessionTypeTest.java
> +    }
작업하면서 누락된 부분인 것 같습니다...
수정했습니다.

2023-12-02 07:46 UTC, gilbertlim commented on src/main/java/nextstep/sessions/domain/data/Session.java
> +package nextstep.sessions.domain.data;
도메인 exception과 분리하려고 생긴 패키지 입니다!
회사 프로젝트에는 event, exception, service가 있어서 습관적으로 data로 나눴었네요.

2023-12-02 07:56 UTC, gilbertlim commented on src/main/java/nextstep/sessions/domain/data/vo/Registrations.java
> +    }
위에 적어주신 내용은 동의합니만
아쉽게도, 인원 제한과 관련된 수강인원 최대 정보, 유료강의 여부 정보가 Session에 있습니다.
Registration에서는 Session에 메시지를 보내거나 getter를 사용해야 합니다.
반대로, Sessions에서 처리하게되면 현재 수강 신청 목록의 크기만 Session으로 전달하면 됩니다.
그래서 Session에서 처리하게되었습니다.

또, 위에 코드와 관련하여 질문이 있습니다.
Registrations.add() 메서드를 통해 기존 수강생 목록에 신규로 내역을 추가하는 것처럼 보이는데,
이런 경우 데이터를 영속화 할 때 신규로 추가된 값만 insert되나요?
JPA에서 연관관계가 맺어진 경우 달라진 상태에 대해서만 데이터가 변경되었던 것 같긴합니다...

2023-12-02 08:03 UTC, gilbertlim commented on src/test/java/nextstep/sessions/domain/data/vo/RegistrationsTest.java
> +    }
프로덕션 코드에 registrations의 사이즈를 반환하는 메서드가 있어 테스트하는 부분입니다.
```java
  public int size() {
        return registrations.size();
    }
```

테스트 메서드 명을 구체화 했습니다.

2023-12-02 08:06 UTC, gilbertlim commented on src/test/java/nextstep/sessions/domain/data/vo/RegistrationsTest.java
> +    }
비즈니스 로직과 관계된 테스트인 경우는 한글로 명시하고 있고,
collection의 기본 기능을 활용하는 메서드, enum 타입에서 상수값 비교를 하는 메서드는 영문 메서드명 그대로 사용하고 있습니다.

getter는 만약 사용하게되면 테스트는 생략하고 있고,
by pass 되는 메서드도 생략하고, 최종 node의 클래스에서 테스트를 진행하고 있습니다.

어떻게 생각하시나요?

2023-12-03 05:07 UTC, testrace commented on src/main/java/nextstep/sessions/domain/data/Session.java
> +    private final Registrations registrations;
인스턴스 변수의 수를 줄이셨네요 👍

2023-12-03 05:07 UTC, testrace commented on src/main/java/nextstep/sessions/domain/data/Session.java
> +    }
>생성자에 의해 초기화되는 멤버변수가 1개일 경우에도 주 생성자에 null을 넣어 호출해야할까요? 

자동차 미션에서 이름으로만 객체를 생성하는 경우 위치 값을 기본 값을 할당한 것처럼
주 생성자에 null을 주입하기 보다 각 필드의 기본 값을 할당할 수 있을 것 같아요

2023-12-03 05:11 UTC, testrace commented on src/main/java/nextstep/sessions/domain/data/vo/Registrations.java
> +    }
> 위에 적어주신 내용은 동의합니만 아쉽게도, 인원 제한과 관련된 수강인원 최대 정보, 유료강의 여부 정보가 Session에 있습니다. Registration에서는 Session에 메시지를 보내거나 getter를 사용해야 합니다. 반대로, Sessions에서 처리하게되면 현재 수강 신청 목록의 크기만 Session으로 전달하면 됩니다. 그래서 Session에서 처리하게되었습니다.

`인원 제한과 관련된 수강인원 최대 정보, 유료강의 여부 정보` 에 대해 알고 있는 수강신청 객체가 있다면 Session 은 직접 로직을 수행하지 않고 해당 객체에게 위임할 수 있을 것 같아 의견 드렸습니다.
수강신청 객체는 수강신청에 필요한 것을 알고 있으니 Session 에게 메시지를 보내거나 getter를 호출할 일도 없을 것 같아요

> 또, 위에 코드와 관련하여 질문이 있습니다. Registrations.add() 메서드를 통해 기존 수강생 목록에 신규로 내역을 추가하는 것처럼 보이는데, registrations를 db에 영속화하려는 의도였을까요?

영속관련 의도는 없습니다.
수강생 목록이 객체라면 메시지를 보내 수강생을 추가할 수 있을 것 같아 의견 드렸습니다

> 이런 경우 데이터를 영속화 할 때 신규로 추가된 값만 insert되는지 궁금합니다. JPA에서 연관관계가 맺어진 경우 달라진 상태에 대해서만 데이터가 변경되었던 것 같긴합니다... 

이건 직접 테스트해 보시면 더 좋을 것 같아요

> 지금은 new Registration()하여 DB에 insert할 생각을 하고 있었습니다.

이번 단계는 `DB를 고려하지 않고 도메인 모델 설계`하는 것인데요
이 코멘트를 보니 다음 단계(DB 적용)에 관점을 두고 구현하신 것이라 생각이 듭니다


> 이 코멘트는 확인해 주시면 다음 리뷰때 반영하도록 하겠습니다:)

피드백 반영은 강제사항이 아니니 지금처럼 의견을 공유해 주시면 좋을 것 같아요 😃

2023-12-03 05:11 UTC, testrace commented on src/test/java/nextstep/sessions/domain/data/vo/RegistrationsTest.java
> +    }
좋은 기준을 가지고 계시니 지금처럼 작성해주시면 될 것 같아요 👍

2023-12-03 05:13 UTC, testrace approved these changes
안녕하세요 성진님
피드백 반영 잘해주셨네요 👍 
소소하게 코멘트 남겼는데 확인해 주시고 다음 단계 진행해 주세요!

2023-12-03 05:13 UTC, merged