🚀 3단계 - 수강신청(DB 적용)
next-step/java-lms pull request #298
Opened 2023-12-03 12:59 UTC by beyondorder

2023-12-03 13:03 UTC, beyondorder commented
리뷰 내용 반영 후 도메인 모델 관계 정의하였습니다.
도메인 객체에 외래키 속성을 넣어 결합하는 방향을 피하고 싶어서
모든 객체의 참조를 우선은 가져가지 않기로하고, 
브릿지 테이블을 두어 연관관계를 설정하였습니다.

2023-12-03 17:15 UTC, wooobo requested changes
안녕하세요 석현님!

3단계 잘 진행해주셨습니다.
브릿지 테이블이 인상깊네요.
질문 하나 남겨 놓았는데 확인 부탁드려요~ 🙏

2023-12-03 17:15 UTC, wooobo commented on src/main/java/nextstep/courses/domain/Price.java
> +        return this.equals(price);
```suggestion
    public boolean samePrice(Price other){
        return price == other.price
```

이렇게는 어떨까요?
`equals` 도 좋지만, `equals`는 공통함수로 많이 쓰이기 때문에 `samePrice`를 도출했다면 직접 상태를 검증하는것도 좋을것 같아서요 🤔

2023-12-03 17:15 UTC, wooobo commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionWithNsUserRepository.java
> +    }
```suggestion
    @Override
    public boolean save(SessionWithNsUser sessionWithNsUser) {
        String sql = "insert into session_ns_user (session_id, ns_user_id) values(? , ?)";
        return jdbcTemplate.update(sql, sessionWithNsUser.getSessionId(), sessionWithNsUser.getNsUserId()) > 0;
    }
```

도메인을 받지 않고 진행하신 이유가 궁금해요~

2023-12-03 17:15 UTC, wooobo commented on src/main/java/nextstep/courses/domain/repository/SessionWithNsUser.java
> +public class SessionWithNsUser {
```suggestion
public class SessionNsUser {
```
`with`를 붙여야 할까요?

2023-12-03 17:15 UTC, wooobo commented on src/main/resources/schema.sql
> +create table session_image(
### 코멘트
> 도메인 객체에 외래키 속성을 넣어 결합하는 방향을 피하고 싶어서
모든 객체의 참조를 우선은 가져가지 않기로하고,
브릿지 테이블을 두어 연관관계를 설정하였습니다.

`요구사항 : 강의는 강의 커버 이미지 정보를 가진다.`
서비스 레이어에서 재조합을 하는 관점으로 구현하신걸까요?
이렇게 할 경우 비즈니스 요구사항이 도메인으로 응집되는것이 아닌 서비스레이어로 파편화 될수 있을것 같은데 
이부분은 어떻게 생각하시나요~?
_(수정을 위한 코멘트는 아니구 석현님의 생각이 궁금해서요~)_

2023-12-04 00:57 UTC, beyondorder commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionWithNsUserRepository.java
> +    }
브릿지 테이블에서 필요한 것은 해당 도메인의 식별자만 있으면 되기 때문에 가볍게 받으려고 하였습니다.
객체를 받고 꺼내는 방법이 더 좋을까요?

2023-12-04 01:23 UTC, beyondorder commented on src/main/resources/schema.sql
> +create table session_image(
요구사항이 강의 커버를 무조건(100%) 갖는다는 의미였다면, Session이 Image를 속성으로 갖도록 하고 Session을 save하는 시점에 Image는 내부적으로 DB에 저장되도록 구현할 수 있을 것 같습니다. (+ 연관관계 브릿지 테이블 처리 포함)

`요구사항 : 강의는 강의 커버 이미지 정보를 가진다`
'가질 수 있다', 와 '가진다'를 놓고 봤을때는 선택과 의무의 요구사항으로 볼 수 있긴 할 것 같습니다.
우선적으로 세션이 존재할 수 있지만 강의 커버 이미지는 세션 존재 후에 등록될 수 도 있는 케이스를 고려하여 구현한 상태입니다.
요구사항의 표현에 대한 이해의 차이에 대해서는 논의를 통해서 더 명확한 요구사항을 도출하고자 함입니다.

2023-12-05 07:18 UTC, wooobo approved these changes
안녕하세요 석현님!

우선 리뷰가 늦어진점 죄송합니다! ㅜ
추가적으로 코멘트 남겨놓았어요~
다음 미션 진행전에 한번 확인 부탁드려요~

그럼 다음 단계도 화이팅입니다!

2023-12-05 07:18 UTC, wooobo commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionNsUserRepository.java
> +    public boolean save(Long sessionId, Long nsUserId) {
> 브릿지 테이블에서 필요한 것은 해당 도메인의 식별자만 있으면 되기 때문에 가볍게 받으려고 하였습니다.
객체를 받고 꺼내는 방법이 더 좋을까요?

더 좋고 안좋고의 문제는 아니었어요~
말씀하신대로 브릿지 테이블이니 식별자만 보내는 것도 좋아보입니다!

저는 이렇게 생각해보았어요.
첫번째 인자는 sessionId이고 두번째 인자는 nsUserId라는 순서가 지켜져야 한다는 부분에서 사용하는 측변에서 오용하면 어떻게하지? 라는 생각이 했었어요.
```
sessionId = 1L
nsUserId = 2L

JdbcCourseSessionRepository.save(nsUserId, sessionId);
```

다른 동료 개발자나 혹은 유지보수 하면서 이러한 휴먼에러가 발생할수 있지 않을까? 생각했기 때문이에요.
사용하는 입장에서 `JdbcCourseSessionRepository.save(courseSession);` 이라고 정의해주면 사용하기 좀 더 편하지 않을까? 혹은 잘못 사용하기 쉽지 않지 않을을까? 라고 생각해보았어요~
(맞고 틀린것에 대한 이야기는 아닙니다~ 이렇게 바라볼수도 있구나 정도로 봐주세요~)

2023-12-05 07:18 UTC, wooobo commented on src/main/resources/schema.sql
> +create table session_image(
아하! 코멘트 감사합니다!

2023-12-05 07:18 UTC, wooobo commented on src/main/java/nextstep/courses/domain/Session.java
>      private final SessionStatus sessionStatus;
> ### 핵심 학습 목표
> - 2단계에서 구현한 객체 구조(도메인 구조)를 가능한 유지하면서 DB 테이블과 매핑한다.
> - 성능보다 도메인 객체에 로직 구현하는 것을 목표로 연습한다.
>    - 객체 구조를 유지하기 위해 여러 번의 DB 쿼리를 실행해도 괜찮다.

`private Image coverImage;` 삭제된 부분에 대해서는 조금 아쉬운것 같아요 😂

2023-12-05 07:18 UTC, wooobo commented on src/main/java/nextstep/courses/domain/Session.java
>      private final SessionStatus sessionStatus;
[[Comment](https://github.com/next-step/java-lms/pull/298/files#r1413280908)] 

> '가질 수 있다', 와 '가진다'를 놓고 봤을때는 선택과 의무의 요구사항으로 볼 수 있긴 할 것 같습니다.


선택, 의무의 요구사항이 명확하지 않다고 판단되더라도 도메인이 가지고 있다면 좀 더 도메인(객체) 중심으로 미션을 진행할 수 있지 않을까? 라는 관점입니다~ 😄 

> 우선적으로 세션이 존재할 수 있지만 강의 커버 이미지는 세션 존재 후에 등록될 수 도 있는 케이스를 고려하여 구현한 상태입니다.

DB관점이 아닌 도메인(객체) 관점으로 바라 보았을때, 도메인응집에 대한 부분이 궁금했습니다!

2023-12-05 07:18 UTC, merged

2023-12-05 10:39 UTC, beyondorder commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionNsUserRepository.java
> +    public boolean save(Long sessionId, Long nsUserId) {
협업에 좋은 방향인 것 같습니다. 감사합니다.