2단계 - 수강신청(도메인 모델)
next-step/java-lms pull request #314
Opened 2023-12-05 04:46 UTC by hyoin11

석홍님 안녕하세요!

2단계 리뷰 요청드립니다~!
1단계 반영안됐던 내용도 추가 반영하였습니다~

2단계 진행하면서 도메인만 구현하려고하니 조금 어렵네요..
먼저 과정을 생성하고 거기에 강의를 추가할 수 있도록 구현해보았습니다.
그런데 수강생이 결제한 금액에 관해 조건을 추가하려고 수강생 도메인을 수정하면 schema.sql도 수정을 해야 이미 작성된 테스트 코드가 에러가 발생하지 않는데 이미 생성된 데이터베이스에 관해서는 수정을 해도 괜찮은건가요??
아니면 데이터베이스에 관련해서는 아예 수정하지 않도록 해야하는 걸까요? 강의를 추가할때 금액만 받아서 검증하도록?

그리고 과정 서비스도 생성하거나 강의를 추가하거나 할 때 과정을 전달하거나 전달받아서 구현해야하는지 조금 어렵네요..
그래서 일단 메서드만 만들었습니다..

2023-12-05 11:58 UTC, seokhong requested changes
효인님 2단계 미션 잘 구현하셨습니다. 👍 
코드에 코멘트 남겼습니다. 코멘트 확인 부탁드립니다. 🙂

2023-12-05 11:58 UTC, seokhong commented on src/main/java/nextstep/qna/domain/Answers.java
> +        if (!isAnswerOwner(loginUser)) {
작성자를 검증하는 부분을 `Answer#delete` 메서드 내부에서 수행해보면 어떨까요? :)
* 관련 코멘트: https://github.com/next-step/java-lms/pull/275/files#r1410621836

`Answer#delete` 메서드도 개별적으로 호출될 수 있는 메서드이므로, 요청한 사람 정보를 받아서 작성한 사람과 일치하는 경우에만 삭제하는 것이 더 안정적일 수 있겠네요!

2023-12-05 11:58 UTC, seokhong commented on README.md
효인님, 질문 남겨주신 부분에 대해 여기에 먼저 답변 드려요!

> 먼저 과정을 생성하고 거기에 강의를 추가할 수 있도록 구현해보았습니다.
그런데 수강생이 결제한 금액에 관해 조건을 추가하려고 수강생 도메인을 수정하면 schema.sql도 수정을 해야 이미 작성된 테스트 코드가 에러가 발생하지 않는데 이미 생성된 데이터베이스에 관해서는 수정을 해도 괜찮은건가요??
아니면 데이터베이스에 관련해서는 아예 수정하지 않도록 해야하는 걸까요? 강의를 추가할때 금액만 받아서 검증하도록?

이번 단계에서는 DB의 변경 없이 `Session`을 추가하고, 수강 신청 기능에 대해서만 구현해보시면 좋겠습니다.
결제 금액, 수강 신청과 관련해서 수강생 도메인에서 어떤 부분을 수정하시고자 하는지 정확히 몰라서,다음 단계에까지 진행하면서 같이 의견 나눠보면 좋겠습니다.

> 그리고 과정 서비스도 생성하거나 강의를 추가하거나 할 때 과정을 전달하거나 전달받아서 구현해야하는지 조금 어렵네요..
그래서 일단 메서드만 만들었습니다..

요구사항, 구현해야 할 범위가 명확하지 않아 고민되셨을 것 같아요. 다음 단계까지 걸쳐서 함께 고민해보면 좋겠습니다. :)

2023-12-05 11:58 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/Session.java
> +    private LocalDate startAt;
기간을 관리하는 클래스도 추가해보면 어떨까요? 기간의 특성(시작일이 종료일 이전)도 검증해볼 수 있겠네요!

2023-12-05 11:58 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/Session.java
> +    public void check() {
수강 신청이 가능한 상태인지 검증하는 메서드이니, 이를 나타낼 수 있도록 메서드 이름을 구체적으로 작성해보면 어떨까요?
수강 신청과 관련된 모든 검증을 한다면, 수강 신청 과정에서 하는 밸리데이션임을 설명하는 이름을 사용해보셔도 좋겠습니다.

2023-12-05 11:58 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/SessionCharge.java
> +    private int studentsCount;
`SessionCharge` 클래스는 비용과 관련된 내용을 관리할 것처럼 보이는데, 수강 신청을 한 인원도 함께 관리하네요.
수강 신청을 한 인원은 `Session` 클래스에서 관리해보면 어떨까요?
비용을 결제하지 않는 무료 강의더라도, 이 강의를 몇 명의 학생이 수강하는지는 관리해야 할 정보처럼 보이네요!

2023-12-05 11:58 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/SessionImage.java
> +        if (width < 300 || height < 200) {
300, 200과 같은 값도 상수로 관리해보면 어떨까요?

2023-12-05 11:58 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/SessionImage.java
> +        if (width / height != 1.5) {
부동소수점은 정확한 값을 나타내지 않는 문제가 발생할 수 있습니다.
나눈 비율을 비교하기 보다는, `width`, `height`에 비율을 곱해서 비교를 해보는 것은 어떨까요?

2023-12-05 11:58 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/ImageType.java
> +                .orElseThrow(IllegalArgumentException::new);
예외 메시지에 예외가 발생하게 된 구체적인 사유, 입력 값(`type`)도 포함하면 어떨까요?
예외 메시지만 보고도 무슨 문제가 있는지 쉽게 확인할 수 있다는 장점이 있습니다.

2023-12-05 11:58 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/Sessions.java
> +        checkSession(sessions);
`Sessions`를 만드는 과정에서 각 세션을 검증할 필요가 있을까요? 이렇게 하는 경우 `모집중`인 상태의 세션으로만 구성된 `Sessions`만 만들 수 있을 것으로 보이네요.

2023-12-05 11:58 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/Sessions.java
> +        session.addStudent();
과정에 강의를 추가할 때 사용될 메서드로 보이는데, 학생수를 증가시키는 이유가 있을까요?

2023-12-05 11:58 UTC, seokhong commented on src/test/java/nextstep/courses/domain/CourseTest.java
> +class CourseTest {
도메인에 대한 꼼꼼한 단위 테스트 작성 좋습니다. 👍

2023-12-05 11:58 UTC, seokhong commented on src/main/java/nextstep/courses/domain/Course.java
> +    public Payments pay() {
* 과정(Course)은 기수 단위로 운영하며, 여러 개의 강의(Session)를 가질 수 있다.
* 강의는 시작일과 종료일을 가진다.

과정과 강의를 현재 넥스트스텝에서 수강중이신 "TDD, 클린 코드 with Java"로 설명드리면 다음과 같습니다.
* 과정: TDD, 클린 코드 with Java
  * 과정 소개 페이지: https://edu.nextstep.camp/c/8fWRxNWU
* 강의: TDD, 클린 코드 with Java 17기
  * 과정 소개 페이지 하단에 보시면 강의 진행 목록을 확인하실 수 있습니다.

위 내용을 참고해보시면, `sessions.pay`와 같이 모든 강의를 일괄로 결제하는 일은 발생하지 않을 것 같아요. :)

2023-12-07 01:37 UTC, hyoin11 commented
석홍님!
피드백 주신 내용 반영하였습니다~!

고민하다가 혼자서 해결이 안될것 같아서 리뷰요청드렸는데 상세한 답변 너무 감사합니다!
그리고 도메인 분리는 나름 같은 역할을 하는 것 같아서 분리했었는데 아직은 분리 후에도 한번 더 의심해보고 생각해봐야할것같아요!

그럼 수정 내용도 리뷰 잘 부탁드립니다!😊

2023-12-07 10:52 UTC, seokhong approved these changes
효인님, 2단계 미션 코멘트 잘 반영하셨습니다. 👍 
2단계 PR 머지하겠습니다. 코멘트 남긴 내용은 다음 단계 미션 진행하시며 참고해보시면 좋겠습니다.
3단계 미션에서 뵙겠습니다. 🙂

2023-12-07 10:52 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/SessionDate.java
> +public class SessionDate {
이 클래스는 세션뿐만 아니라 다른 곳에서도 기간 개념이 필요하면 사용할 수 있을 것 같네요. :)
`Period` 와 같이 도메인에 종속적이지 않은 이름을 사용하면, 추후 재사용이 더 용이할 것으로 보입니다.

2023-12-07 10:52 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/SessionStudent.java
> +    private int limitCount;
최대 인원은 유료 여부와 관련이 있고, 함께 사용될 것으로 보입니다.
유료 강의에 따른 제한은 `SessionCharge`에서 관리하고, 현재 수강중인 인원만 `SessionStudent` 또는 `Session`에서 관리해보면 어떨까요?

2023-12-07 10:52 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/SessionImage.java
> +        if (width * HEIGHT_RATIO != height * WIDTH_RATIO) {
처음 코드를 보면 왜 `width`에 `HEIGHT_RATIO`를 곱하는지 바로 이해되지 않고 생각하는 과정을 거쳐야 할 수도 있겠네요.
메서드로 분리하고 `isCorrectRatio()`와 같이 이름을 지으면 비율을 검사하는지 알 수 있을 것 같아요. 필요하면 주석을 통해 3:2 비율이 맞는지 확인하기 위해 곱해서 검증한다는 내용을 추가해 볼 수도 있겠네요. :)

2023-12-07 10:52 UTC, seokhong commented on src/main/java/nextstep/courses/domain/Course.java
> +    public Payments pay() {
이 코멘트와 [다른 코멘트](https://github.com/next-step/java-lms/pull/314#discussion_r1415473435)의 내용은 다음 단계 미션 진행하시면서 참고해서 수정해보시면 좋겠습니다. :)

2023-12-07 10:52 UTC, merged