Step3
next-step/java-lms pull request #323
Opened 2023-12-05 16:24 UTC by Jane096

리뷰어님 안녕하세요!

2단계 리뷰보다가 한가지 궁금한게 있어서 남깁니다!
보통 자바 책을 읽다보면 상속을 추천하지 않는 글이 많았습니다. 대체로 안티 패턴으로 정의하는 경우도 많은 것처럼 느꼈구요.
저 또한 그런 점을 참고하여 추상화하고 상속을 사용하지 않은 이유도 있었습니다.

물론 jpa에서 엔티티를 만들 때 BaseEntity 처럼 완전 고정되고 변할일이 없는 경우에는 extends 해서 많이 사용하지만
Session처럼 추상화하여 상속하여 사용하는 방식이 실제 실무 코드에서는 유지보수 측면에서 과연 좋은 것인지, 자바 서적에서 정의하는 것처럼 안티패턴은 아닌지 궁금합니다!!

2023-12-06 10:14 UTC, shared-moon commented
지은님 안녕하세요!
일단 한가지 잘못 알고 계신게, 상속과 추상화는 다른 개념입니다.
상속은 클래스의 기능을 확장하는 것으로 `extends` 라는 예약어를 쓰구요, 추상화는 명시되지 않은 껍데기만 있는 기능을 구현하는 것으로 `implements` 라는 예약어를 씁니다.

물론 추상 클래스를 상속하는것도 추상화이긴 하지만, 근본적으로는 클래스의 기능을 확장 하는것이라 인터페이스와는 개념이 조금 달라요

그래서 인터페이스를 두고 각각의 역할에 맞게 클래스의 구현부를 가져가는건 아무런 위험이 없습니다. 지금은 추상화를 하는게 더 맞는 상황일 것 같아요. 안그러면 Session 내부에서 조건문으로 분기를 계속 해야하는데, 이건 변경에 닫힌 구조를 만드는거라서요..!

추가로, 상속이 지양되는 이유는 정말 상속을 해도 괜찮은 경우가 잘 없어서 그렇습니다. 지금은 상속 대상으로 보여도, 개발 하다 보면 혹은 요구사항이 변하면 상속 대상이 아니게 되면서 오히려 변경하는데 리소스가 많이 드는 경우가 빈번하거든요. 예로 드신 BaseEntity도 정말 고정되고 변할일이 없다고 단언할 수 있을까요 ?

그렇다고 상속이 안티패턴이냐고 하면 그건 동의하지 않습니다. 잘 판단해서 필요한 곳에 쓴다면 추상화와 마찬가지로 코드 중복을 줄이고 타입에 의한 처리가 가능하기 때문에 잘 판단해서 쓰는게 좋다고 생각합니다.

하나 잔소리를 드리자면, 실제 실무에서 어떻게 쓰이는지, 책에서 어떻게 쓰이는지보다 지은님이 지은님의 근거를 가지고 판단해서 사용하셨으면 합니다. 책에선 그렇게 써있었다. 실무에선 그렇게 한다고 하더라 같은 근거는 지은님 실력 향상에 아무런 도움이 되지 않아요. 책 내용에 근거할 순 있지만, 그 내용을 토대로 (틀리더라도) 지은님의 생각을 근거로 들 수 있는 방향으로 학습을 하시면 좋을 것 같습니다..!

2023-12-06 10:22 UTC, shared-moon requested changes
지은님 안녕하세요!
3단계 미션 잘 진행 해 주셨네요 :)
코멘트를 좀 남겨 두었는데, 확인 후 리뷰 재요청 부탁드려요!
고생 많으셨습니다 :)

2023-12-06 10:22 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/CostMoneySession.java
> +public class CostMoneySession extends Session {
코멘트에도 남겼지만, 요기가 이제 인터페이스를 받도록 바뀌면 좋을 것 같네요!

2023-12-06 10:22 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/CostMoneySession.java
> +        super(id, courseId, title, sessionImages, sessionType, sessionStatus, startAt, endAt);
요것도 약간 상속의 단점인데, 상속을 하면 필드들이 한눈에 안보여서 어떤 필드들을 가지고 있는지 계속 왔다갔다 해야되는 문제도 있죠..!

2023-12-06 10:22 UTC, shared-moon commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionImageRepository.java
> +        return jdbcTemplate.update(sql,
이미지는 url만 수정할 수 있는걸까요 ~?
다른 값들이 수정되려면 각각의 update 메서드를 전부 만들어줘야 하는데, 이것보단 전체를 업데이트 하는 메서드 하나를 만들어두는게 낫지 않을까요 ?
+ updatedAt도 같이 바꿔줘야되지 않을까 합니다!

2023-12-07 14:33 UTC, Jane096 commented on src/main/java/nextstep/courses/domain/CostMoneySession.java
> +        super(id, courseId, title, sessionImages, sessionType, sessionStatus, startAt, endAt);
네 맞습니다!! 저도 필드를 맞추느라 시간을 많이 쏟게 되어서 똑같이 느꼈던 것 같습니다 😅

2023-12-07 14:34 UTC, Jane096 commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionImageRepository.java
> +        return jdbcTemplate.update(sql,
네! 테스트 목적으로만 만들다보니 한개만 수정하게 되었네요..! 전체 수정으로 바꿔보겠습니다!

2023-12-07 14:44 UTC, Jane096 commented
안녕하세요 리뷰어님!

따끔한 지적과 조언을 해주셔서 너무나 감사드립니다. 
리뷰어님 답변을 보고 나니 제 질문의 부족함이 많이 느껴졌습니다. 늘 변할 수 있고 상황에 맞게 적절히 사용하는 것이 중요한데 그 점을 간과하고 있었던 것 같아요.

리뷰에는 인터페이스를 사용하라고 하시긴 했지만, 추상클래스로 만들어서 작업을 해보았습니다! 
공통된 로직은 있지만 구현이 다른 경우와 공통 부분이 섞여있다 보니 추상클래스를 선택하게 되었습니다! 
이번에도 좋은 리뷰 부탁드리겠습니다. 감사합니다!!! 🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️

2023-12-08 15:09 UTC, shared-moon approved these changes
지은님 안녕하세요!
피드백 반영 잘 진행 해 주셨네요 :)
코멘트를 남겨 뒀는데, 다음 미션 진행 전 확인 부탁드려요!
고생 많으셨습니다 :)

2023-12-08 15:09 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/FreeSession.java
> +        validateRegister(payment);
요거 약간 무료강의와 유료강의 둘다 호출하고 있는 것 같은데, 템플릿 메서드 패턴에 대해서 찾아보시면 좀 더 좋은 구조가 될 것 같아요! 뭔가 상속의 개념이 된다면 강의 종류 별로 꼭 해야 하는 유효성 검사 같은것도 있지 않을까 해서요..!

2023-12-08 15:09 UTC, merged