🚀 3단계 - 수강신청(DB 적용)
next-step/java-lms pull request #327
Opened 2023-12-05 17:34 UTC by kimgwanghoon

안녕하세요. 이번 리뷰도 잘부탁드립니다.

이번 미션 진행하면서 강의와 참가자의 N:M 매핑 테이블을 구현하려고 했었습니다.
하지만 요구사항에 기존구조를 유지하면서 매핑한다고 되어있어서 이전 미션에서 누락한 session의 courseId, image의 sessionId만 추가하였습니다.

목표에 구조를 유지하기위해 여러번의 쿼리 호출이 가능하다고 되어있어서
SessionService의 강의 조회를 진행하다 이미지를 join으로 호출 하지 않고 따로 호출하는 형태로 구현할 경우 따로 조회한 이미지를 set을 진행 해야 하는데 해당 경우 어떤형태로 가야하는지 의문이 드네요..
아래 처럼set을 쓰지 않아야하니 `Session.of(session, Image)`형태로 구현하는것이 맞을까요?
`Session session =  sessionRepository.findById(id);`
`session.setImage(imageRepository.findBySessionId(id));`

2023-12-06 15:38 UTC, mskangg requested changes
3단계 구현도 잘해주셨네요!
테스트코드 꼼꼼히 잘 작성해주셨네요 👍 
몇가지 코멘트 드렸으니, 확인부탁드려요! 🙇

2023-12-06 15:38 UTC, mskangg commented on src/main/java/nextstep/courses/service/SessionService.java
> +    }
session 의 비즈니스를 처리하고 저장을 하고있지 않네요 🤔

리턴타입을 Session으로 한뒤, saveSession 메서드를 호출하는 방식으로 생각하신걸까요?

2023-12-06 15:38 UTC, mskangg commented on src/main/java/nextstep/courses/service/SessionService.java
> +        return sessionRepository.findById(id);
> 목표에 구조를 유지하기위해 여러번의 쿼리 호출이 가능하다고 되어있어서
SessionService의 강의 조회를 진행하다 이미지를 join으로 호출 하지 않고 따로 호출하는 형태로 구현할 경우 따로 조회한 이미지를 set을 진행 해야 하는데 해당 경우 어떤형태로 가야하는지 의문이 드네요..
아래 처럼set을 쓰지 않아야하니 Session.of(session, Image)형태로 구현하는것이 맞을까요?
Session session =  sessionRepository.findById(id);
session.setImage(imageRepository.findBySessionId(id));

session id 로 조회시 image 를 같이 가져오고 싶은 경우일까요? 🤔
조인해서 가져오지 않는 경우 관계를 매핑해줘야하는 부분은 반드시 필요합니다. (join 자체가 관계를 매핑해주는 것이니)

`setter 를 지양하라는것`은 무의미한 setter 를 지양하라는 말이에요! 😄 
이런 경우 무의미한 set 보단 의미를 만들어 메서드로 구현해야합니다.

```java
session.mappedBy(image);
```

```java
// Session.class
public void mappedBy(Image image) {
     // mapping
}
```

이렇게 관계를 명시적으로 매핑하여 처리할 수 있을것 같아요. :)

2023-12-06 15:38 UTC, mskangg commented on src/main/java/nextstep/courses/service/SessionService.java
> +    @Autowired
생성자 주입으로 받는게 좋을것 같아요 :)

관련 링크 남겨드릴게요

https://madplay.github.io/post/why-constructor-injection-is-better-than-field-injection

2023-12-06 15:38 UTC, mskangg commented on src/main/java/nextstep/courses/domain/session/ParticipantManager.java
> +public class ParticipantManager {
👍

2023-12-06 15:38 UTC, mskangg commented on src/main/java/nextstep/courses/domain/session/Price.java
> +        this.participantManager = null;
이부분은 주,부생성자를 사용하지 않은 이유가 궁금합니다 🤔

2023-12-06 15:38 UTC, mskangg commented on src/main/java/nextstep/courses/domain/session/Price.java
> +    private final ParticipantManager participantManager;
보다보니 가격이 수강생관리자를 상태로 관리하고 있는게 어색해보여요 🤔
어떻게 구조를 변경하는게 좋을까요?
고민해주세요!

2023-12-06 15:38 UTC, mskangg commented on src/test/java/nextstep/courses/domain/session/SessionTest.java
> +        Price price = new Price(false, 10000, new ParticipantManager(10));
Price를 반복적으로 생성중이네요!
이런 부분은 테스트 픽스쳐를 만들어 관리하는 것도 하나의 방법입니다.

```java
Price 무료_10000 = 무료가격_생성됨(10000);
Price 유료_20000 = 유료가격_생성됨(20000);
```

이렇게 표현하기도 합니다 :)

2023-12-06 15:57 UTC, mskangg commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionRepository.java
> +    private JdbcOperations jdbcTemplate;
repository 구현체에서 이미지를 같이 조회해서 매핑해서 주는 방법도 있습니다.

```suggestion
    private JdbcOperations jdbcTemplate;
    private ImageRepository imageRepository;
```

인터페이스를 의존한 뒤, find 시에 가져와서 mapping 하는 방법도 있어요 :)
다만, 이렇게하면 repository 간의 의존관계가 생기기 때문에 이부분도 고민이 필요해요 🤔
그리고 커플링이 높아지는 단점이 생기고, 훗날 요구사항이 추가되면서 유지보수하기 힘들어질 수 있습니다 🫠
충분한 고민해보시길 바랄게요!

2023-12-07 11:39 UTC, kimgwanghoon commented on src/main/java/nextstep/courses/service/SessionService.java
> +    }
save를 적용했다고 생각했는데 빠졌네요.😅

2023-12-07 11:41 UTC, kimgwanghoon commented on src/main/java/nextstep/courses/domain/session/Price.java
> +        this.participantManager = null;
놓치고있었네요. 수정해두겠습니다.🤕

2023-12-07 12:07 UTC, kimgwanghoon commented on src/main/java/nextstep/courses/domain/session/Price.java
> +    private final ParticipantManager participantManager;
Enrolment를 만들어서 여기에서 같은선상에서 가격과 수강관리자를 두는게 좋겠네요.😀

2023-12-07 12:14 UTC, kimgwanghoon commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionRepository.java
> +    private JdbcOperations jdbcTemplate;
미션을 하는것에선 service에서 강의와 이미지를 각각 조회해서 가지도록 했습니다. 
의존성을 높여서 쿼리를 줄이냐, 의존성을 줄여서 쿼리를 늘리냐 어디까지 허용해야할지 역시 고민이네요 ㅎㅎ😂

2023-12-08 12:15 UTC, mskangg approved these changes
피드백 반영 잘해주셨습니다! 👏 👏 
소소한 코멘트 확인해주시고 다음단계 진행해주세요!
그럼 마지막까지 화이팅 🔥

2023-12-08 12:15 UTC, mskangg commented on src/main/java/nextstep/courses/domain/session/Enrolment.java
> +public class Enrolment {
👍

2023-12-08 12:15 UTC, mskangg commented on src/main/java/nextstep/courses/domain/session/Price.java
> +    public static Price of(boolean isFree, int money) {
수강생관리자를 덜어내니 책임이 많이 사라졌네요 🤔
변수로 isFree 를 관리하기보단, 메서드로 isFree를 구현해보시는건 어떠신가요? 
비즈니스상 `가격이 0원이면 무료로 본다` 에 기반하면 될것 같아요

```java
public boolean isFree() {
    return money == 0;
}
```

훗날 `100원 미만의 강의는 무료로 본다` 와 같이 요구사항이 추가되면 저 메서드만 수정하면 되겠군요!

2023-12-08 12:15 UTC, mskangg commented on src/test/java/nextstep/courses/domain/session/SessionTest.java
> +    private static Session createSession(ParticipantManager participantManager, boolean isFree, SessionStatus ready) {
👍

2023-12-08 12:15 UTC, merged