Step3 수강신청(DB 적용)
next-step/java-lms pull request #335
Opened 2023-12-06 16:27 UTC by pilming44

이전에 아파치 라이브러리 말씀 해주셨을때 그걸 사용하라고 하시는줄알고
라이브러리를 추가해서 했네요 ㅎㅎㅎ
말씀하신대로 문서 참고해서 간단하게만 구현해서 사용했습니다!
그리고 이번 미션도 열심히 구현해봤어요!
db에 반영하려고하다보니 무한 getter생성이 됐는데요.. 이렇게 하는게 맞겠죠...?

2023-12-07 15:05 UTC, testrace requested changes
안녕하세요 재현님
3단계도 깔끔하게 잘 구현해주셨네요
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청 부탁드려요

2023-12-07 15:05 UTC, testrace commented on src/main/java/nextstep/lms/domain/CoverImage.java
> +    }
테스트에서만 사용되는 생성자네요
테스트 클래스 내부에서 메서드를 추가해 기존의 생성자를 활용하면 어떨까요?
```java
private CoverImage coverImage() {
    return new CoverImage(...);
}
```

2023-12-07 15:05 UTC, testrace commented on src/main/java/nextstep/lms/domain/Session.java
> +    }
이 생성자는 사용되고 있지 않네요

2023-12-07 15:05 UTC, testrace commented on src/main/java/nextstep/lms/domain/SessionEnrollmentManagement.java
> +        if (pricingPolicy.canEnroll(enrollApplicationDTO.getTuitionFee())) {
도메인이 dto에 의존하지 않는 방향으로 개선해 보셔도 좋을 것 같아요

2023-12-07 15:05 UTC, testrace commented on src/main/java/nextstep/lms/domain/SessionInfo.java
> +        sessionDetail.sessionStatusCheck();
강의 상태는 SessionEnrollmentManagement 내부에서 검증하면 어떨까요?

2023-12-07 15:05 UTC, testrace commented on src/main/java/nextstep/lms/domain/SessionManagement.java
더 이상 사용하지 않는 클래스는 제거해 주시면 좋을 것 같아요

2023-12-07 15:05 UTC, testrace commented on src/main/java/nextstep/lms/domain/SessionPeriod.java
> +    }
요구사항에 명시되어 있지 않은 제약을 추가하셨군요 👍 
전달 받은 now 파라미터를 사용하면 어떨까요?
if 조건문의 부정 연산을 제거하고 긍정문으로 작성하면 가독성에도 도움이 될 것 같아요

2023-12-07 15:05 UTC, testrace commented on src/main/java/nextstep/lms/domain/Students.java
> +    private final List<Long> students;
식별 값을 관리하도록 변경하셨군요 👍

2023-12-07 15:05 UTC, testrace commented on src/main/java/nextstep/lms/enums/PricingTypeEnum.java
> +    }
단위 테스트를 추가해 보셔도 좋을 것 같아요

2023-12-07 15:05 UTC, testrace commented on src/main/java/nextstep/lms/infrastructure/JdbcSessionRepository.java
> +        System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>id : " + id);
```suggestion
```

2023-12-07 15:05 UTC, testrace commented on src/main/resources/schema.sql
> +    tuition_fee	int	NULL,
int 타입의 컬럼들은 기본 값을 지정해줘도 좋을 것 같아요

2023-12-07 15:05 UTC, testrace commented on src/test/java/nextstep/lms/domain/FileMetadataTest.java
> +    public static FileMetadata NORMAL_FILE_METADATA = new FileMetadata(1024 * 1024l, FileSizeTest.NORMAL_FILE_SIZE);
자료타입을 표시하는 문자에도 [컨벤션](https://google.github.io/styleguide/javaguide.html#s4.8.8-numeric-literals)이 있으니 참고해 주세요

2023-12-07 15:05 UTC, testrace commented on src/main/java/nextstep/lms/repository/SessionRepository.java
이전 단계에서 LmsService를 만들어주셔서 구현을 하실거라 생각했는데 구현되지 않았네요
repository 구현이 되었으니 service까지 구현해 보시면 좋을 것 같아요

2023-12-07 19:03 UTC, pilming44 commented
항상 리뷰요청하기전에 한번 더 확인해보고 요청하는데도 놓치는게 있네요.. 죄송합니다!!
리뷰내용 반영해서 리팩토링 해봤습니다!!
하다보니 변경이 꽤나 있었습니다 ^^;;
이번에도 리뷰 잘부탁드립니다!

2023-12-08 06:47 UTC, testrace approved these changes
안녕하세요 재현님
피드백 반영 잘해주셨네요 👍 
몇 가지 코멘트 남겼는데 확인해 주시고 다음 단계 진행해 주세요

2023-12-08 06:47 UTC, testrace commented on src/main/java/nextstep/lms/domain/Session.java
> +        this(0l, new SessionInfo(coverImage, pricingType, tuitionFee, sessionStatus, capacity, startDate, endDate), new Students(new ArrayList<>()), LocalDateTime.now(), null);
```suggestion
        this(0L, new SessionInfo(coverImage, pricingType, tuitionFee, sessionStatus, capacity, startDate, endDate), new Students(new ArrayList<>()), LocalDateTime.now(), null);
```

2023-12-08 06:47 UTC, testrace commented on src/main/java/nextstep/lms/service/LmsService.java
> +        }
session에 수강 신청자 목록을 가지고 있어야 중복 신청을 막을 수 있지 않을까요?
sessionRepository.findById 메서드는 신청자 목록이 비어있는 상태로 초기화하는 생성자를 사용하는데요
비즈니스 로직에 적합한지 고려해 보시면 좋을 것 같아요

나아가서 enroll 메서드에서 수강 신청이 완료되었다면 DB에 저장할 수 있는 객체를 반환하면 어떨까요?
```suggestion
        final Session session = sessionRepository.findById(payment.getSessionId());
        final Student student = session.enroll(payment);
        studentsRepository.save(student);
```

2023-12-08 06:47 UTC, testrace commented on src/main/java/nextstep/lms/domain/SessionEnrollmentManagement.java
> +    }
메서드 내부에 분기가 있다면 모든 경우를 테스트해서 분기 처리가 잘 되는지 검증하면 어떨까요?

PricingPolicy#canEnroll 메서드는 validate 성격의 기능이라 if 분기처리 하는게 적절한지 고민해 보시면 좋을 것 같아요

2023-12-08 06:47 UTC, testrace commented on src/test/java/nextstep/lms/domain/SessionEnrollmentManagementTest.java
> +                .hasMessage("모집중이 아닙니다.");
예외 검증시 테스트하고자 하는 메서드만 호출하면 좋을 것 같아요
```suggestion
        final Students students = new Students(Collections.emptyList());
        final Payment payment = new Payment("1", 1L, 1L, 0L);
        
        assertThatThrownBy(() -> completedSession.enroll(students, payment))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessage("모집중이 아닙니다.");
```

2023-12-08 06:48 UTC, merged

2023-12-09 00:00 UTC, pilming44 commented on src/main/java/nextstep/lms/domain/Session.java
> +        this(0l, new SessionInfo(coverImage, pricingType, tuitionFee, sessionStatus, capacity, startDate, endDate), new Students(new ArrayList<>()), LocalDateTime.now(), null);
이걸 놓치다니..ㅠㅠ