3단계 - 수강신청(DB 적용)
next-step/java-lms pull request #354
Opened 2023-12-08 18:20 UTC by namuhuchutong

안녕하세요. 찬인님 😁
3단계 미션을 완료해서 리뷰요청 드립니다. 이번에도 잘 부탁드립니다. 🙇‍♂️

2023-12-09 12:14 UTC, pci2676 requested changes
조금 더 고민해볼만한 부분에 리뷰를 남겨두었습니다.

확인 부탁드립니다. 😄

2023-12-09 12:14 UTC, pci2676 commented on src/main/java/nextstep/courses/domain/attendee/AttendeeRepository.java
> +    List<Attendee> findAllBySeesionId(Long sessionId);
오타가 있는것 같습니다 😄

2023-12-09 12:14 UTC, pci2676 commented on src/main/java/nextstep/courses/domain/session/PaidEnrollment.java
> +        attendees.checkParticipateIn(attendee);
enroll이 등록을 하는 메서드로 보이는군요. attendees에 새로운 attendee를 추가하지는 않아도 되나요?

추가하는 과정에서 check를 해보면 어떨까요?

2023-12-09 12:14 UTC, pci2676 commented on src/main/java/nextstep/courses/domain/session/SessionStatus.java
> +    FINISHED("FINISHED"),
혹시 DB에 저장하기 위해 추가하신 것이라면

enum의 name 프로퍼티는 이미 존재하니 참고하시면 좋을것 같습니다.

2023-12-09 12:14 UTC, pci2676 commented on src/main/java/nextstep/courses/domain/session/EnrollmentSession.java
> +    private final Enrollment enrollment;
information이 알려줄 수 있는 정보와 enrollment에서 알려줄 수 있는 정보가 겹치는 부분이 있을것 같습니다.

적절히 객체의 정보를 도출하여 EnrollmentSession가 알고 있어야 하는 객체의 정보를 최소한으로 줄여보면 좋을것 같습니다.

지금 당장 보이는 부분은 enrollment와 information 둘다 paid인지 free인지에 대해 알고 있는것 같아보입니다.

다른 부분도 찾아보시고 위임할 수 있는 부분은 위임해보시면 좋을것 같습니다.

2023-12-09 12:14 UTC, pci2676 commented on src/main/java/nextstep/courses/domain/attendee/PaidAttendees.java
> +            throw new NegativeOrZeroNumberException();
exception 메세지가 정확히 어떠한 상태 때문에 발생한지 알수 있다면 더 좋지 않을까 싶습니다.

메세지를 다른 메세지와 같이 템플릿 형태로 제공할 수 있으면 좋을것 같습니다.

2023-12-10 11:07 UTC, namuhuchutong commented
상세한 피드백 감사합니다. 👍
피드백 반영하고 다시 리뷰요청 드립니다. 잘 부탁드립니다. 🙇‍♂️

2023-12-10 14:20 UTC, pci2676 approved these changes
이번 단계 요구사항은 기존 코드를 잘 작성해주신 덕에 크게 무리없이 구현하신것 같습니다.

머지하겠습니다 😄

2023-12-10 14:20 UTC, merged