🚀 4단계 - 수강신청(요구사항 변경)
next-step/java-lms pull request #356
Opened 2023-12-09 16:55 UTC by qwe5507

4단계 리뷰요청 드립니다!

강의와 이미지가 1:n관계가 되면서 fk를 이미지가 가지게 되었는데요. 
세션이 이미지 정보를 조회할 일이 많을 것 같아. 세션 객체에서 List<Image>를 갖고있는데
이 과정에서 세션 정보를 저장할때 세션이 가지고 있는 이미지 객체를 각각 저장하는데 조금 어려움이있었습니다.
이부분 검토부탁드립니다!

Enrollment에 승인 여부를 추가하여 승인/취소를 판단하게 하였습니다. 

감사합니다!

2023-12-10 09:23 UTC, bingbingpa requested changes
마지막 미션 잘 구현해주셨는데요.
몇 가지 확인해봤으면 하는 부분이 있어서 리뷰 남겨드렸어요.
확인해보시고 마지막으로 다시 한번만 리뷰 요청 부탁드려요.

2023-12-10 09:23 UTC, bingbingpa commented on src/main/resources/schema.sql
> +     `type` varchar(10) not null,
sql 에서 type 은 예약어이기 때문에 앞에 prefix 를 붙여주는게 더 좋을것 같습니다.

2023-12-10 09:23 UTC, bingbingpa commented on src/main/resources/schema.sql
> +   session_id bigint not null,
이부분에서 디비의 fk 와 실제 객체 조회시 관계 때문에 고민을 많이 하신것 같은데요. 
저는 질문에 적어주신 것처럼 session 이 이미지 리스트를 가지고 있는건 자연스럽다고 생각해요.
저장할때는 데이터의 무결성을 위해 image 테이블이 session_id 를 가지고 있는게 좋겠지만
조회할때는 seesion 이 이미지 목록을 가지고 있는게 더 유연하다고 생각해요.

2023-12-10 09:23 UTC, bingbingpa commented on src/main/java/nextstep/courses/domain/enrollment/Enrollment.java
> +    }
메소드명은 뭔가 판별후에 boolean 값을 리턴할 것 같은데 그냥 approved 라는 값을 리턴하고 있네요. 
getXXX 같은 이름이 개인적으로는 더 낫다고 생각해요.

2023-12-10 09:23 UTC, bingbingpa commented on src/main/java/nextstep/courses/infrastructure/JdbcEnrollmentRepository.java
> +    private boolean toApproved(int intApproved) {
Enrollment 클래스에서는 boolean 값을 사용하고, 디비에서는 int 값을 사용하는 특별한 이유가 있을까요?
클래스와 디비의 타입이 다르기 때문에 불필요하게 이걸 변환해주는 로직이 필요한건 아닌가 싶어서 질문드려요.

2023-12-10 10:09 UTC, qwe5507 commented on src/main/resources/schema.sql
> +   session_id bigint not null,
넵! session_id는 이미지 테이블에, 
세션객체가 이미지 객체 리스트를 갖게 했습니다!

2023-12-10 10:30 UTC, qwe5507 commented on src/main/resources/schema.sql
> +     `type` varchar(10) not null,
예약어를 사용하고 있는 image테이블과 session테이블 컬럼명 변경했습니다!

2023-12-10 10:32 UTC, qwe5507 commented on src/main/java/nextstep/courses/domain/enrollment/Enrollment.java
> +    }
넵 애매할수있는 이름보다는 getApproved()로 변경하였습니다!

2023-12-10 10:35 UTC, qwe5507 commented on src/main/java/nextstep/courses/infrastructure/JdbcEnrollmentRepository.java
> +    private boolean toApproved(int intApproved) {
mysql이 boolean타입을 지원안하는 걸로 알고있었는데, h2는 지원을하네요!
그래서 불필요한 변환로직을 없애고, h2 db의 데이터타입을 boolean타입으로 변경하였습니다!

2023-12-11 01:52 UTC, bingbingpa approved these changes
리뷰 반영 잘해주셨네요! 👍
마지막 미션 머지하도록 하겠습니다. 
미션 진행 하시느라 수고하셨습니다! 🚀

2023-12-11 01:52 UTC, merged