🚀 3단계 - 수강신청(DB 적용)
next-step/java-lms pull request #357
Opened 2023-12-09 17:20 UTC by hoon25

안녕하세요 리뷰어님 3단계에서 변경내용이 많네요! 
리뷰 잘부탁드립니다🙇‍♂️🙇‍♂️🙇‍♂️

## 작업내용 & 궁금한내용
### Session의 Interface 추가
`Sessionable`이라고 interface명을 지었는데, 적절한지 궁금하네요.
### Session, FreeSession, PaidSession
데이터베이스 구조를 `SingleTableStrategy` vs `JoinedStrategy`로 고민하였는데,
다른필드가 존재하기도하고, 추후 달라지는 점이 많을 것 같다는 생각에 `JoinedStrategy`를 선택했습니다.

JPA에서 제공해주던 `@Inheritance(strategy = InheritanceType.JOINED)`가 아닌 직접 JDBC로 구현하는게 꽤나 힘든 작업이였네요..😭😭😭

### Enrollment
Enrollment에 생성자에 repository계층을 위한 생성자가 많이 추가되어서, DAO의 도입을 고려하였는데, 감이 잘 오지 않아서 우선 패스했습니다.!!

2023-12-10 14:44 UTC, shared-moon requested changes
창훈님 안녕하세요!
3단계 미션 잘 진행 해 주셨네요 :)
코멘트를 좀 남겨 두었는데, 확인 후 리뷰 재요청 부탁드려요!
고생 많으셨습니다 :)

2023-12-10 14:44 UTC, shared-moon commented on src/main/java/nextstep/common/domain/BaseDomain.java
> +    private Long id;
id는 베이스로 빼기 좀 애매한 것 같아요!
모든 entity에 primary key가 필요한 건 맞지만, 모든 primary key가 long 타입의 시퀀셜한 아이디는 아니라서요..!

2023-12-10 14:44 UTC, shared-moon commented on src/main/java/nextstep/common/domain/utils/JdbcConvertUtils.java
> +public class JdbcConvertUtils {
요건 혹시 왜 필요했던걸까요 ? 시간을 관리하는 클래스를 여러개 쓰는 이유가 궁금하네요 ~

2023-12-10 14:44 UTC, shared-moon commented on src/main/java/nextstep/session/domain/Session.java
> +    protected void validateCommonEnroll(NsUser nsUser) {
자식 클래스가 무조건 구현하게 하려면 abstract를 붙여주는게 좋을 것 같아요 ~

2023-12-10 14:44 UTC, shared-moon commented on src/main/java/nextstep/session/domain/Session.java
> +public abstract class Session extends BaseDomain implements Sessionable {
추상 클래스와 인터페이스를 다 사용하고 계신데, 하나만 사용해도 되지 않을까요 ?
추상화 말씀드릴 때, 생각했던건 도메인 레벨에서 세션을 정의하고, 값을 가져왔을 때 별도의 팩토리 클래스 등으로 타입에 따라 다른 세션 클래스를 만들어서 가지고 다니는걸 생각하긴 했었는데, 테이블과 매칭이 좀 어려우시다면, Session이 아니라 SessionType만 추상화해서 유효성 검사의 책임만 들고 가보는 건 어떨까요 ? 그러면 인터페이스가 아니라 enum을 이용해서 추상화를 하고, DB에서는 enum의 이름을 문자열로만 가지고 있으면 되니 맵핑도 좀 쉽게 하실 수 있을 것 같아서요 ~

2023-12-10 14:44 UTC, shared-moon commented on src/main/java/nextstep/session/domain/Session.java
> +public abstract class Session extends BaseDomain implements Sessionable {
그리고 요기가 상속관계를 고민하신 것 같은데 .. 제 생각엔 필드의 확장이 아니라 테이블의 상속 관계는 고려 대상이 아니지 않나 싶어요! 저희가 타입에 따라 분기되는건 유효성검사 뿐이라서요..!

2023-12-12 10:51 UTC, hoon25 commented on src/main/java/nextstep/common/domain/utils/JdbcConvertUtils.java
> +public class JdbcConvertUtils {
rs.getTImestamp(*).toLocalDate()을 사용하면  NPE가 발생하고, 이를 위한 처리 코드가 반복되는 것 같아서 utils로 두었습니다.!

2023-12-12 10:56 UTC, hoon25 commented on src/main/java/nextstep/common/domain/BaseDomain.java
> +    private Long id;
그럴 수 있겠네요.!  각 구현체로 옮겼어요

2023-12-12 11:06 UTC, hoon25 commented on src/main/java/nextstep/session/domain/Session.java
> +public abstract class Session extends BaseDomain implements Sessionable {
타입에따라 필드도 실제로 변경되지 않나요? 유료 강의의 경우 price랑, capacity가 추가될 것 같아요.

혹시 제가 코멘트를 잘못 이해한걸까요?

2023-12-12 11:10 UTC, hoon25 commented on src/main/java/nextstep/session/domain/Session.java
> +public abstract class Session extends BaseDomain implements Sessionable {
> 테이블과 매칭이 좀 어려우시다면, Session이 아니라 SessionType만 추상화해서 유효성 검사의 책임만 들고 가보는 건 어떨까요 ? 그러면 인터페이스가 아니라 enum을 이용해서 추상화를 하고, DB에서는 enum의 이름을 문자열로만 가지고 있으면 되니 맵핑도 좀 쉽게 하실 수 있을 것 같아서요 ~

여기서 부터 잘 이해가 가지 않는데, 죄송하지만 추가적으로 설명해 주실 수 있나요?

2023-12-12 11:12 UTC, hoon25 commented on src/main/java/nextstep/session/domain/Session.java
> +public abstract class Session extends BaseDomain implements Sessionable {
+)현재 유료강의와 무료강의가 거의 유사하여서 Session테이블 하나에 두어도 무관함을 인지하고 있지만, 학습의 목적에서 테이블을 3개로 분리하는 방식으로 구현을 진행했습니다.ㅠ

2023-12-12 16:03 UTC, shared-moon commented on src/main/java/nextstep/common/domain/utils/JdbcConvertUtils.java
> +public class JdbcConvertUtils {
toLocalDateTime 만 있으면 되는게 아닌건가요 ? 밑에 다른 클래스에 대해서도 만들어두신 것 같아서 여쭤봅니다 ~

2023-12-12 16:03 UTC, shared-moon commented on src/main/java/nextstep/session/domain/Session.java
> +public abstract class Session extends BaseDomain implements Sessionable {
price랑 capacity가 무료강의엔 없어야 될 필요성이 없어 보여서 말씀 드렸었어요 ~ 위에 코멘트 하신 내용으로 이런 구조로 만들어보고 싶어서 사용하신걸로 인지했습니다!

2023-12-12 16:13 UTC, shared-moon commented on src/main/java/nextstep/session/domain/Session.java
> +public abstract class Session extends BaseDomain implements Sessionable {
저는 `강의 등록 검증` 부분만 추상화 대상으로 빼면 어떨까 하는 생각이었는데, 창훈님은 세션 테이블을 상속받아서 테이블의 역할을 확장하고 싶어하시는 것 같네요 ~

말 그대로 테이블에 데이터가 들어가려면 컬럼이 되어야 하니 타입을 문자열로 가져가고 그걸 enum과 매핑 시키자는 얘기였어요 ~ 그럼 enum에서 유효성검사만 분리하면 나머진 다 똑같이 쓸 수 있을 것 같아서요!

지금 방식은 추상화라기보다는 상속을 구현하시는 것 같고, 개인적으로는 강의 종류가 늘어날 떄마다 테이블도 추가해야되는 구조라 애매해 보이긴 하는데, 의도하신거라고 하니 그렇게 하셔도 상관 없을 것 같습니다 ~

2023-12-12 16:15 UTC, shared-moon approved these changes
창훈님 안녕하세요!
피드백 반영 잘 진행 해 주셨네요 :)
코멘트를 좀 남겨 두었는데, 다음 미션 진행 전 확인 부탁드려요!
고생 많으셨습니다 :)

2023-12-12 16:15 UTC, merged