3단계 - 수강신청(DB 적용)
next-step/java-lms pull request #362
Opened 2023-12-10 06:45 UTC by hyoin11

석홍님 안녕하세요~!

2단계 피드백 주셨던 내용도 추가하였습니다!
처음에는 과정에 강의를 추가하면서 모집인원을 검증하는 방식으로 설계를 하고 구현을 하였는데, 두번의 피드백에 동일한 내용을 이야기해주셔서 설계가 잘못되었다고 생각하고 결제할 때 모집인원을 검증하도록 로직을 이동하였습니다. 제가 다시 생각해볼 수 있도록 기다려주셔서 감사합니다👍

이번 강의 테이블만 추가하였고, 일단 하나의 테이블에 전체 데이터를 넣도록하였습니다. 여기서 테이블을 분리한다면 이미지에 관련된 정보들을 따로 테이블을 분리할까 생각하였는데 컬럼수가 많지 않다고 생각되서 일단은 하나의 테이블만 생성하였습니다.
그리고 현재는 학생수의 상태값만을 변경할 수 있도록 구현하여서 데이터베이스에도 학생수의 상태값만을 update하도록 구현하였습니다.

그럼 3단계 피드백도 잘 부탁드립니다!☺️

2023-12-11 00:40 UTC, seokhong requested changes
효인님, 3단계 미션 잘 구현하셨습니다! 👍 
코드에 코멘트 조금 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2023-12-11 00:40 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/Session.java
> +        int limitCount = this.charge.getLimitCount();
`this.charge.getLimitCount()`로 값을 꺼내서 확인하기보다는, `this.charge.isFull(this.studentCount)`와 같이 물어보는 형태로 구현하면 어떨까요?

2023-12-11 00:40 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/Session.java
> +        checkStudentCount();
모집중인 상태의 강의만 수강신청이 가능하므로, `checkSessionStatus`도 호출해서 상태를 검증해야 할 것으로 보이네요!

2023-12-11 00:40 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/SessionImage.java
> +        if (!isCorrectRatio(width, height)) {
`!isCorrectRatio` 처럼 반환 값을 부정으로 사용해야 하는 경우 `isNotCorrectRatio` 메서드를 제공해보면 어떨까요? `!`의 경우 코드를 읽을 때 상대적으로 눈에 잘 안 들어와서 헷갈리는 경우가 있더라고요.

2023-12-11 00:40 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/Sessions.java
>      public Payments pay(Long creatorId) {
이전 단계에서 남긴 [코멘트](https://github.com/next-step/java-lms/pull/314#discussion_r1415478865)에도 있지만, 한 과정에 포함된 여러 강의를 동시에 결제하는 일은 없을 것으로 보입니다.
현재 구현에 따르면 "TDD, 클린 코드 with Java" 과정을 수강하면 "TDD, 클린 코드 with Java 1기 - 17기" 강의를 모두 수강 신청하는 것처럼 보이네요.
수강 신청은 강의 단위로만 발생하므로, `Sessions`에 대한 결제나 수강 신청 기능은 없어도 될 것으로 보입니다.

2023-12-11 00:40 UTC, seokhong commented on src/main/java/nextstep/sessions/infrastructure/JdbcSessionRepository.java
> +        return jdbcTemplate.update(sql, session.getName(), session.getDate().getStartAt(), session.getDate().getEndAt(), session.getImage().getSize(), session.getImage().getWidth(), session.getImage(
객체를 저장한 후 값을 반환한다면, 아이디를 반환해보는 건 어떨까요?
`update` 메서드의 기본 반환 값은 변경된 로우의 개수로 알고 있습니다. `KeyHolder`를 이용해 아이디를 반환해보면 어떨까요? `save` 이후에 반환된 값이 저장된 행의 개수라고 생각하기는 어려울 것 같아요.

2023-12-11 00:40 UTC, seokhong commented on src/main/java/nextstep/sessions/infrastructure/JdbcSessionRepository.java
> +    public int update(Session session) {
> 그리고 현재는 학생수의 상태값만을 변경할 수 있도록 구현하여서 데이터베이스에도 학생수의 상태값만을 update하도록 구현하였습니다.

메서드의 이름을 수강 인원을 변경하는 것을 나타내도록 명시적으로 작성해보면 어떨까요? :)

2023-12-11 00:40 UTC, seokhong commented on src/main/java/nextstep/sessions/infrastructure/SessionRepository.java
> +public interface SessionRepository {
`SessionRepository` 구현이 완료되었으니, 이를 활용해서 수강 신청을 하는 기능을 서비스로 구현도 해보시면 좋겠습니다. :)

2023-12-12 15:11 UTC, hyoin11 commented
석홍님 안녕하세요~!

피드백 주신 내용 반영하였습니다!

요구사항 중 '과정(Course)은 기수 단위로 운영하며, 여러 개의 강의(Session)를 가질 수 있다.' 이 요구사항에 대해 제가 잘못 이해했었습니다. 저는 과정의 한 기수안에 여러개의 강의를 가질 수 있다고 생각해서 Sessions를 만들고 그에관해 수강신청이나 결제에 대한 구현을 하려고 했었습니다. 석홍님이 주셨던 예시로 다시 이해하였습니다 ㅎㅎ 감사합니다!

그리고 addStudent 메서드를 수강신청으로 변경하였습니다. 기능은 같으나 이 메서드의 역할이 수강신청인것 같아서 수정하였습니다!

2023-12-13 10:01 UTC, seokhong requested changes
효인님, 3단계 미션 코멘트 잘 반영하셨습니다. 👍 
4단계 미션으로 넘어가기 전에 추가로 반영하시면 좋을 것 같은 내용이 있어 코멘트 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2023-12-13 10:01 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/Session.java
> +    public void enroll() {
어떤 학생이 수강 신청 했는지에 대한 정보도 알 수 있으려면 어떻게 하면 좋을까요?
4단계 미션을 진행하기 전에, 수강 신청을 한 학생 목록도 볼 수 있도록 추가해보시면 4단계 미션을 통해 더 많이 학습하실 수 있을 것 같아요.

2023-12-13 10:01 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/SessionCharge.java
> +    public void isFull(int studentCount) {
`is` prefix는 boolean 값을 반환할 때 주로 사용합니다. 예를 들어 `String#isEmpty`와 같은 메서드가 있습니다.
인원을 검증하고 예외를 발생시키므로, 다른 검증 메서드와 동일하게 `check` prefix를 사용하면 어떨까요?

2023-12-14 09:24 UTC, hyoin11 commented
석홍님 안녕하세요~!

수강신청자들에 관한 도메인 추가하였습니다!
수강신청에 관한 repository까지 수정하였는데 아직은 수강신청생들 목록을 가져올 경우가 있을까 싶어 수강신청생들에 관련된 목록은 private으로 진행하였습니다. 추후에 필요하다면 변경해서 사용해보겠습니다!

이번이 석홍님께 요청드리는 마지막 요청일듯한데, 지금까지 상세한 설명과 피드백 감사했습니다! 참고할만한 내용들까지 같이 피드백 주셔서 더 이해하기 쉬웠습니다 ㅎㅎ
지금까지 감사했습니다~!!😊👍

2023-12-14 11:03 UTC, seokhong approved these changes
효인님, 3단계 미션 코멘트 잘 반영하셨습니다. 👍 
3단계 PR 머지하겠습니다.
추후 미션 진행 일정이 어떻게 될지 몰라서, 추가로 코멘트를 조금 남겼습니다. 다음 단계 미션 진행하실 때 참고해보시면 좋겠습니다.
이제 마지막 단계 미션만 남았네요. 다음 단계 미션에서 뵙겠습니다. 🙂

2023-12-14 11:03 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/SessionStudents.java
> +            checkStudent(students.get(i), students.get(i+1));
`i`와 `+` 사이, `+`와 `1` 사이에 공백이 누락됐네요.
```suggestion
            checkStudent(students.get(i), students.get(i + 1));
```
IDE의 자동 줄맞춤 단축키를 사용하시거나, 파일을 저장할 때마다 자동으로 줄맞춤이 되도록 설정해보시면 좋겠습니다.
intellij를 사용하신다면 Preferences > Tools > Actions on Save 에서 자바 코드도 Reformat Code, Optimize Imports를 설정해서 수정하는 코드를 자동 줄맞춤, 임포트 최적화를 실행하도록 하실 수 있습니다. :)

2023-12-14 11:03 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/SessionStudents.java
> +        students.stream().forEach(student -> addStudent(student));
```suggestion
        this.students = new HashSet<>(students);
```
생성자를 이용해서 바로 `Set` 구조로 변경해보는 건 어떨까요?

중복에 대한 검증은 `NsUser`의 equals, hashCode까지 구현하면(`SessionStudent`에서 `NsUser`를 이용해 equals를 구현하셨네요), `this.students`와 `students`의 크기가 동일한지 여부로도 확인이 가능할 것으로 보입니다.

2023-12-14 11:03 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/SessionStudent.java
> +    private LocalDateTime registrationAt;
`Course`에 있는 `createdAt`, `updatedAt`과 같이 `registeredAt`으로 변경해보는 건 어떨까요?

2023-12-14 11:03 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/Session.java
>  public class Session {
`Course`와 마찬가지로 `Session`과 같은 엔티티는 DB에서 관리할 때 생성일시, 수정일시를 함께 관리하시는 것이 좋습니다.
`createdAt`, `updatedAt`과 같은 필드는 모든 엔티티에 추가해서 관리해보시면 좋겠습니다. :)

2023-12-14 11:03 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/Session.java
>  public class Session {
엔티티의 equals, hashCode 구현에 대한 여러 방법이 있으니, 여러 방법을 비교해보신 후 장단점과 주의점을 참고하여 선택하고 구현해보시면 좋겠습니다. :)

2023-12-14 11:03 UTC, seokhong commented on src/main/java/nextstep/sessions/domain/Session.java
>      // id
엔티티의 각 필드에는 지금과 같이 주석을 남기시는 것이 좋은데요. 단순히 이름만 남기는 것이 아니라, 주석을 보고 무슨 역할을 하는지 이해할 수 있도록 설명해주시면 좋습니다. 예를 들면, `SessionCharge`의 경우 "강의의 결제와 관련된 내용을 관리한다. 유료 강의의 경우 수강 인원에 제한이 있다." 와 같은 내용이 추가될 수 있겠네요.

주석을 남기지 않고 코드만 보고도 이해할 수 있도록 작성하는 것이 중요하지만, 도메인에 대한 내용이나 정책은 코드로 모두 표현할 수 없는 경우가 있습니다. 이러한 내용을 클래스에 대한 주석(위에 예로 남긴 내용을 `SessionCharge` 클래스의 주석으로 관리하는 방법도 가능하겠네요!)이나 필드에 대한 주석을 통해 관리하면, 추후 코드를 보고 이해할 때 도움이 됩니다. 다만, 주석이 여러 곳에 분산되어 있으면 동일한 내용으로 관리하기 어려우므로, 필드에 남길 것인지 클래스에 남길 것인지도 고민해보신 후 작성하시면 좋겠습니다.

2023-12-14 11:03 UTC, merged