🚀 1단계 - 레거시 코드 리팩터링
next-step/java-lms pull request #413
Opened 2024-03-31 05:06 UTC by hellonayeon

안녕하세요 용주님,
수강신청 미션 리뷰를 받게된 나연입니다. 😃
잘 부탁드립니다!

(1단계 미션은 모짝미에서 만난 다른 수강생분과 함께 진행했습니다.)

2024-03-31 09:41 UTC, testrace reviewed
안녕하세요 나연님 😃
마지막 미션을 함께 하게 된 송용주입니다. 잘 부탁드려요!
1단계 잘 구현해 주셨네요 👍
몇 가지 코멘트 남겨두었는데요. 확인해 주시고 다시 리뷰 요청 부탁드려요

2024-03-31 09:41 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answer.java
> +            throw new CannotDeleteException("다른 사람이 쓴 답변이 있어 삭제할 수 없습니다.");
Answer는 1개의 답변인데요
예외 메시지에서 '다른 사람이~' 라는 표현은 어색한 것 같습니다.
답변 작성자가 아닌 경우에 예외가 발생하니 상황에 맞는 예외메시지로 변경하면 어떨까요?

일급 컬렉션 Answers에서는 다른 사람이 작성한 답변이 있는지 검증해도 좋을 것 같아요

2024-03-31 09:41 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answer.java
> +    }
삭제하지 않고 이 메서드를 호출하면 의도한대로 동작했다고 볼 수 있을까요?

2024-03-31 09:41 UTC, testrace commented on src/main/java/nextstep/qna/domain/Question.java
> +    public DeleteHistories addDeleteHistory() {
(참고만 해주세요)
Question 에 DeleteHistory를 추가하는데 DeleteHistories 는 조금 어색한 것 같아요 
코드 내용은 삭제 이력을 만들어서 반환하니 '변환' 이라는 표현이 있으면 어떨까 싶어요

2024-03-31 09:41 UTC, testrace commented on src/main/java/nextstep/qna/service/QnAService.java
> +        DeleteHistories deleteHistories = deleteQuestion.addDeleteHistory();
삭제를 수행하지 않고 addDeleteHistory 메서드를 호출하면 삭제 여부와 상관없이 삭제 이력 객체가 생성되는데요
실제로 삭제 되지 않는 내용을 저장하면 의도한대로 동작한다고 보기 어려울 것 같아요
삭제와 동시에 삭제 이력을 생성하면 어떨까요?
```suggestion
        DeleteHistories deleteHistories = question.delete(loginUser);
```

2024-03-31 09:41 UTC, testrace commented on src/test/java/nextstep/qna/domain/AnswerTest.java
> +    }
CannotDeleteException 의 메시지는 '다른 사람이 쓴 답변이 있어 삭제할 수 없습니다' 라고 나올텐데요.
DisplayName의 테스트 의도와 동일한 메시지가 아니더라도 테스트가 성공을 합니다.
테스트의 의도대로 검증되는지 예외 메시지까지 함께 검증하면 어떨까요?

2024-03-31 09:41 UTC, testrace commented on src/test/java/nextstep/qna/domain/QuestionTest.java
> +    }
테스트가 실패하네요 😢 
<img width="383" alt="image" src="https://github.com/next-step/java-lms/assets/8064743/35359ba0-9ecf-4419-bd26-cd64d0a85f8e">

2024-03-31 09:42 UTC, testrace requested changes
안녕하세요 나연님 😃
마지막 미션을 함께 하게 된 송용주입니다. 잘 부탁드려요!
1단계 잘 구현해 주셨네요 👍
몇 가지 코멘트 남겨두었는데요. 확인해 주시고 다시 리뷰 요청 부탁드려요

2024-04-01 12:11 UTC, hellonayeon commented on src/main/java/nextstep/qna/domain/Answer.java
> +            throw new CannotDeleteException("다른 사람이 쓴 답변이 있어 삭제할 수 없습니다.");
실습 뼈대 코드를 그대로 사용하면서 
예외 메시지들이 의도를 명확하게 전달하고 있는지는 고민해보지 못한 것 같아요 🥹

`Answer` 는 자신의 `writer(owner)` 의 정보를 알고있고, 자신과 비교하는 로직이니
`"답변의 작성자가 아닌 경우~"` 가 더 좋을 것 같네요.

의견 공유주셔서 감사합니다 !

2024-04-01 12:29 UTC, hellonayeon commented on src/main/java/nextstep/qna/domain/Question.java
> +    public DeleteHistories addDeleteHistory() {
안그래도 메서드명 분위기가 마음에 들지 않았는데, 
메서드명을 `convertToDeleteHistory(ies)` 로 수정하고 `DeleteHistory` 를 리턴하도록 리팩토링하니 훨씬 좋네요!

의견 공유주셔서 감사합니다!

2024-04-01 12:30 UTC, hellonayeon commented on src/test/java/nextstep/qna/domain/QuestionTest.java
> +    }
😱😱😱 테스트 데이터를 잘못 주입하고 있었네요 😱😱😱
놓쳤습니다 ㅠㅠ 확인해주셔서 감사해요 !!

2024-04-01 12:42 UTC, hellonayeon commented on src/main/java/nextstep/qna/service/QnAService.java
> +        DeleteHistories deleteHistories = deleteQuestion.addDeleteHistory();
위에 피드백 주신 내용도 그렇고 동의합니다.
> 삭제하지 않고 이 메서드를 호출하면 의도한대로 동작했다고 볼 수 있을까요?

삭제가 되었을때만 수행될 수 있도록 외부에 메서들 공개하지 않고, `delete` 호출 시 같이 수행되도록 수정하는게 좋을 것 같아요!

---

원래는 피드백 주신 구조처럼 `delete + addDeleteHistory` 두 로직을 하나의 메서드에서 처리했었는데요. ([commit ac8f59f](https://github.com/next-step/java-lms/pull/413/commits/ac8f59f171f754ba9176fc8bfa162485e5621598))

아래의 고민을 거쳐 결과적으로 현재의 코드로 수정하게 됐습니다.
* `delete` 메서드에서 `delete` 외에 `addHistory` 를 하고 있다.
* 그러면 메서드 명이 `delete` 가 아니라 `deleteAndAddHistory` 가 되는게 좋지 않을까?
* 메서드명이 2가지의 행위를 표현한다면 하나의 메서드가 여러 책임을 하고 있다고 볼 수 있을 것 같다.
* 그렇다면 분리해서 메서드의 재사용성을 높이는게 좋겠다.

근데 피드백을 통해 제가 놓쳤던 부분을 깨달았네요 🥹
> 삭제하지 않고 이 메서드를 호출하면 의도한대로 동작했다고 볼 수 있을까요?

> 실제로 삭제 되지 않는 내용을 저장하면 의도한대로 동작한다고 보기 어려울 것 같아요
삭제와 동시에 삭제 이력을 생성하면 어떨까요?

메서드의 재사용성을 높이는 것도 중요하지만, 
요구사항을 생각했을 때 외부에서 의도치 않게 호출되지 않도록, 적절한 호출 시점에 대한 고민이 선행되어야 할 것 같아요.

2024-04-01 13:03 UTC, hellonayeon commented
안녕하세요 용주님,
리뷰 재요청 드립니다 😃

메서드 네이밍이나 로직 위치 관련해서 고민했던 부분에 대해 꼼꼼하게 리뷰해주셔서 좋은 인사이트 얻을 수 있었습니다. 👍🏻
피드백 주시면 또 고민하고 반영해보도록 하겠습니다!

2024-04-01 13:04 UTC, hellonayeon commented
참고로 반영한 피드백은 리뷰어님 댓글에 🚀 표시하면서 미션 진행하고 있습니다!

2024-04-01 13:06 UTC, hellonayeon commented on src/test/java/nextstep/qna/domain/AnswerTest.java
> +    }
`CannotDeleteExceptionMessage enum` 을 정의해서 
정의된 예외 메시지를 던지고, 단위 테스트에서도 검증할 수 있도록 수정했습니다!

2024-04-01 13:09 UTC, hellonayeon commented on src/main/java/nextstep/qna/service/QnAService.java
> +        DeleteHistories deleteHistories = deleteQuestion.addDeleteHistory();
[commit d5d382b](https://github.com/next-step/java-lms/pull/413/commits/d5d382b68b69479e48efb23675029564e55eaaa5) 으로 작업해서 반영했는데요.

`Commit suggestion` 에서 리뷰어님께서 제안해주신대로 바로 `commit` 하는 기능이 있네요!
다음번엔 해당 기능 사용해서 반영해볼게요 🙊

2024-04-02 03:59 UTC, testrace requested changes
안녕하세요 나연님 😃 
피드백 반영 잘해주셨네요 👍 
핵심 미션인 만큼 조금 더 수정되면 좋을 것 같아 코멘트 남겨두었습니다
확인해 주시고 다시 리뷰 요청 부탁드려요

2024-04-02 03:59 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answer.java
> +    public DeleteHistory convertToDeleteHistory() {
요구사항엔 구체적으로 명시되어 있지 않지만,
1개의 답변만 삭제하는 경우도 존재할 수 있을 것 같은데요.
Question 처럼 접근 제한자를 private으로 변경하면 어떨까요?

2024-04-02 03:59 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answers.java
> +    public List<DeleteHistory> convertToDeleteHistories() {
여기서도 public으로 열어두기 보다 delete 메서드의 리턴으로 삭제 이력을 넘겨주면 어떨까요?

2024-04-02 03:59 UTC, testrace commented on src/main/java/nextstep/qna/domain/Question.java
> +    private DeleteHistories addDeleteHistories() {
private으로 외부에서 직접 호출하지 못하도록 막아주셨군요 👍 
Answer에서처럼 메서드명에서 add를 제거하면 좋을 것 같아요

2024-04-02 03:59 UTC, testrace commented on src/test/java/nextstep/qna/domain/AnswersTest.java
> +                .withMessageContaining(CAN_DELETE_ONLY_ANSWER_OWNER.getMessage());
AnswerTest에도 동일한 구문이 있는데 포맷팅이 다르네요
코드의 일관성을 위해 포맷팅을 맞춰 주시면 좋을 것 같아요

2024-04-02 03:59 UTC, testrace commented on src/main/java/nextstep/qna/domain/Question.java
> +        return addDeleteHistories();
삭제와 동시에 이력을 만들어 리턴해도 좋을 것 같은데요
이력을 생성하는 메서드를 별도로 분리하도록 해주신 이유가 궁금합니다 🤔 
```java
final DeleteHistory questionHistory = deleteQuestion(user);
final List<DeleteHistory> answerHistories = deleteAnswers(user);

return DeleteHistories.of(questionHistory, answerHistories);
```

2024-04-02 11:33 UTC, hellonayeon commented on src/test/java/nextstep/qna/domain/AnswersTest.java
> +                .withMessageContaining(CAN_DELETE_ONLY_ANSWER_OWNER.getMessage());
몇 군데 일관성이 깨진 부분이 있네요 🥹
놓치지 않고 확인해주셔서 감사해요!

2024-04-02 12:46 UTC, hellonayeon commented on src/main/java/nextstep/qna/domain/Question.java
> +        return addDeleteHistories();
`삭제` 하는 것과 `히스토리 추가` 하는 행위는 구분된 행위라 생각해서 나눴어요!

하지만 맨 처음 의견주신 것과 같이, 삭제와 히스토리 로직이 구분되어 있어서 
외부에서 히스토리 추가에 대한 메서드가 공개되어 있어 의도치 않게 히스토리 데이터가 생성될 위험이 있을 것 같아요!
> 요구사항엔 구체적으로 명시되어 있지 않지만,
1개의 답변만 삭제하는 경우도 존재할 수 있을 것 같은데요.
Question 처럼 접근 제한자를 private으로 변경하면 어떨까요?

또한 현재 요구사항이 자세히 나와있지 않지만 미션 기반으로 제공된 `QnAService`에 따르면 
삭제와 동시에 삭제에 따른 `DeleteHistory` 를 반환해서 저장하는 로직만 있어서, 

의견 주신 것 처럼 `삭제와 동시에 이력을 만들어서 반환`하도록 수정했습니다 😃

요구사항이나 접근제어에 대해 깊이 생각하지 못한 것 같네요 ..
질문 주셔서 감사합니다!

2024-04-02 12:53 UTC, hellonayeon commented
안녕하세요 용주님, 
리뷰 재요청 드립니다!

첫 단계에서 놓치지 않고 리뷰주신 덕분에 
메서드 접근제어와 요구사항에 따른 하나의 메서드 내부 구현 범위에 대해 고민해볼 수 있었어요 👍🏻
이후 단계에서도 관련해서 신경써서 구현해보겠습니다!

단위테스트 포맷팅 일관성이나 접근지정자 일괄로 확인하긴 했는데, 
혹시 또 놓친 부분 공유주시면 수정해서 리뷰 재요청 하겠습니다!

2024-04-02 22:58 UTC, testrace approved these changes
안녕하세요 나연님 😃 
피드백 반영 잘해주셨네요 👍 
소소하게 코멘트 남겨두었는데 참고만 해주세요
다음 단계도 화이팅입니다!

2024-04-02 22:58 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answer.java
>          return new DeleteHistory(ContentType.ANSWER, id, writer, LocalDateTime.now());
(참고만 해주세요)
답변의 convertToDeleteHistory, 질문의 convertToDeleteHistory 메서드 모두 DeleteHistory를 생성할 때 createdDate 필드의 값을 LocalDateTIme.now 를 활용해 주고 계신데요
질문과 답변 삭제는 순차적으로 진행되기에 생성된 삭제 이력의 생성일시는 작지만 차이가 있습니다
질문과 답변은 '동시'에 삭제가 되었지만 삭제 이력의 생성일시는 모두 다른 값을 가지게 됩니다
이후 로그 추적등을 위해서 동일한 생성일시를 가지도록 개선해 보시는 것도 좋을 것 같아요

2024-04-02 22:59 UTC, merged