feat : 🚀 2단계 - 수강신청(도메인 모델)
next-step/java-lms pull request #426
Opened 2024-04-03 16:04 UTC by gutenLEE

안녕하세요. 

도메인 레이어만 작업하여 리뷰 요청드립니다. 

감사합니다!

2024-04-04 11:15 UTC, csh0034 requested changes
2단계 구현하시느라 수고많으셨습니다.
구현시에 추가하려는 기능 단위로 커밋을 분리해보시면
더 좋을것 같아요!
몇가지 코멘트 남겨두었는데 확인 부탁드립니다.

2024-04-04 11:15 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/Course.java
> +    private List<Session> sessions;
일급컬렉션을 적용해보는건 어떨까요?

2024-04-04 11:15 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/SessionStateful.java
> +public interface SessionStateful {
해당 인터페이스가 필요한걸까요? 🤔

2024-04-04 11:15 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/Session.java
> +abstract class Session implements SessionStateful {
중복제거를 위해 상속을 사용해주신것 같아요. 상속은 신중하게 사용해야합니다.
컴포지션을 사용하지 않으신 이유가 있으실까요?

- [이펙티브 자바, 아이템18  - 상속보다는 조합(컴포지션)을 사용하라](https://velog.io/@alkwen0996/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-%EC%95%84%EC%9D%B4%ED%85%9C17-%EC%83%81%EC%86%8D%EB%B3%B4%EB%8B%A4%EB%8A%94-%EC%BB%B4%ED%8F%AC%EC%A7%80%EC%85%98%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC)

2024-04-04 11:15 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/PaySession.java
> +class PaySession extends Session {
Session 구현체에만 public 키워드가 없는 없네요! 
다른 이유가 있으실까요? 🤔

2024-04-04 11:15 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/vo/Period.java
> +    public Period(LocalDate start, LocalDate end) {
검증까지 잘 추가 해주셨네요.
그런데 Period 를 누가 사용하는지 알 수 없을것 같은데 접두사가 추가되어야 하지 않을까요?

2024-04-04 11:15 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/vo/ImageSize.java
> +    private int width;
변경되지 않는다면 final 을 추가해주는것도 좋을것 같습니다.

2024-04-04 11:15 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/vo/CoverImage.java
> +public class CoverImage {
각 조건 검증은 관리하고 있는 인스턴스 변수 안에서 해보는건 어떨까요?
추가로 조건에 대해선 상수로 표현해보시면 좋을것 같습니다.

2024-04-04 11:15 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/Attendees.java
> +public class Attendees {
Attendees 가 강의 수강 인원을 가지고 있어야 하는걸까요? 🤔

2024-04-04 11:15 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/Session.java
> +    private Long id;
해당 Session 이 어떤 Course 에 속하는지도 알아야하지 않을까요? 🤔

2024-04-04 14:08 UTC, gutenLEE commented on src/main/java/nextstep/courses/domain/PaySession.java
> +class PaySession extends Session {
위 상속을 그나마 안전하게 사용하기 위함입니다!

Session 과 PaySession, FreeSession이 is kind of 관계를 만족한다.
Session에 추상 메서드만 두어 구현체에서 행위를 구현하게 했으며, 
무분별한 상속을 막기 위해서였습니다..

컴포지션을 사용한여 유료강의, 무료강의를 구분한다면 
유료와 무료일때 달라지는 행위들을 전략 패턴으로 도메인에서 분리하는 방법이 있을까요?

2024-04-04 14:09 UTC, gutenLEE commented on src/main/java/nextstep/courses/domain/Session.java
> +    private Long id;
아 그렇네요 감사합니당

2024-04-04 14:09 UTC, gutenLEE commented on src/main/java/nextstep/courses/domain/SessionStateful.java
> +public interface SessionStateful {
이펙티브 자바에서 얼핏 객체에 이넘으로 태깅하지 말라는 내용을 본거같은데 
잘 소화하지 못하고 적용했네요 ㅎㅎ

2024-04-04 15:51 UTC, gutenLEE commented on src/main/java/nextstep/courses/domain/EnrollCommand.java
Session 상속 구조를 제거해보려고 다시 고민하고 요구사항을 다시 분석해봤습니다. 

`enroll` 행위의 조건이 변경될 수 있다
- 유료
    - 최대 수강 인원 제한 O
    - 결제 금액
- 무료
    - 최대 수강 인원 제한 X

이렇게 `enroll` 행위의 조건이 변경될 수 있다는 것을 파악했고,
enroll 조건을 추상화하였습니다.

2024-04-04 15:52 UTC, gutenLEE commented on src/main/java/nextstep/courses/domain/Attendees.java
> +public class Attendees {
수강 인원은 Session이 알아야할 정보였네요! 수정하겠습니다

2024-04-05 09:41 UTC, csh0034 approved these changes
리뷰 반영 잘해주셨네요 👍 
3단계에서 뵙겠습니다!

2024-04-05 09:41 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/vo/ImageFile.java
> +    private static final Extension[] ALLOWED_EXTENSION = {Extension.PNG, Extension.GIF, Extension.JPG, Extension.JPEG, Extension.SVG};
별도로 정의하지 않고 `Extension` 을 활용해보시면 좋을것 같아요!

2024-04-05 09:41 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/vo/CoverImage.java
> +    public CoverImage(Capacity capacity) {
커버이미지는 3가지의 인스턴스 변수가 모두 정상적으로 존재할때만 
사용 가능해야하지 않을까요? 🤔

2024-04-05 09:41 UTC, csh0034 commented on src/test/java/nextstep/courses/domain/SessionFixture.java
> +public class SessionFixture {
도메인 패키지에 두기보단 별도 fixture 패키지를 분리해보는것도 좋을것 같습니다 🙂

2024-04-05 09:41 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/Session.java
> +class Session {
상속을 제거하였으므로 무료 강의인지 유료강의인지구분하는 타입을 두는것도
고려해볼수 있을것 같습니다.

2024-04-05 09:41 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/EnrollCommand.java
> +public interface EnrollCommand {
강의 타입에 따라 처리해야하는 행위를 잘 분리해주셨네요 👍

2024-04-05 09:41 UTC, merged

2024-04-05 09:48 UTC, csh0034 commented on src/main/java/nextstep/courses/domain/PaySession.java
> +class PaySession extends Session {
EnrollCommand 를 사용하여 잘 분리해주셨네요 👍 

구현을 할때 상태에 따라 행위를 다르게 할 경우 고민이 되는것 같아요.
저의 경우엔 다르게 처리되는 비지니스로직이 복잡한 경우엔 별도로 분리를 하며 
그렇지 않다면 우선 한 메서드에 분기처리를 하는 방식을 선택합니다.

이는 실무에선 요구사항에 따라 판단해야하기 때문에 해당 과정 중엔 적용해주신 방법과 같이
전략으로서 분리를 해보는것도 좋을것 같아요 😄