🚀 2단계 - 수강신청(도메인 모델)
next-step/java-lms pull request #450
Opened 2024-04-08 13:19 UTC by leeedohyun

안녕하세요. 선동님! 2단계를 너무 늦게 제출하네요😭 
현재 단계에서는 테이블을 신경쓰지 않고(연관 관계를 신경쓰지 않고) 설계를 해봤습니다! 부족한 부분 많이 지적 부탁드립니다ㅎㅎ
2단계도 잘 부탁드립니다🙇‍♂️

# 궁금한 점
## 다음과 같이 생성된 Question은 둘 다 아이디가 0L이 아닌가요?
2단계를 진행하면서 처음에 작성되어 있던 코드에 의심을 가지게 되었습니다.

```java
public static final Question Q1 = new Question(NsUserTest.JAVAJIGI, "title1", "contents1");
public static final Question Q2 = new Question(NsUserTest.SANJIGI, "title2", "contents2");
``

`QuestionTest`에 있는 Question 상수입니다. 이 상수는 아이디를 파라미터로 가지지 않는 생성자로 생성하는데요. 그래서 이 생성자를 살펴보면 다음과 같습니다.

```java
public Question(NsUser writer, String title, String contents) {
    this(0L, writer, title, contents);
}
```

아이디를 기본 0L로 사용하고 있다는 것을 알 수 있는데요. 그렇다면 Q1과 Q2는 둘 다 아이디가 0L이 되는거 아닌가요? 서비스 테스트에서는 Q1만 사용하고 있어서 문제가 되지 않을 것 같지만, 이렇게 생성하는 것이 옳은 방식인지 궁금합니다!

## 패키지 명명규칙에 관한 질문입니다.
위의 질문과 같이 기존의 패키지명을 보면 courses, payments 등과 같이 복수로 되어 있습니다. 패키지명은 단순하게 소문자만을 허용한다고 알고 있는데요. 복수 형태로도 많이 짓는 편인지 궁금합니다!

2024-04-09 08:06 UTC, seondongpyo requested changes
2단계 미션도 잘 구현해주셨네요 👍 
몇 가지 코멘트 드렸는데 확인 후 다시 리뷰 요청을 부탁 드리겠습니다 🔥

2024-04-09 08:06 UTC, seondongpyo commented on src/main/java/nextstep/images/domain/CoverImage.java
> +    private void validate(final double size, final int width, final int height) {
다음 요구사항대로 width와 height의 비율에 대한 검증 로직도 추가해보면 어떨까요?
> 이미지의 width는 300픽셀, height는 200픽셀 이상이어야 하며, **width와 height의 비율은 3:2여야 한다.**

2024-04-09 08:06 UTC, seondongpyo commented on src/main/java/nextstep/images/domain/CoverImage.java
> +            throw new IllegalArgumentException("이미지 크기는 1MB를 넘을 수 없습니다.");
- 예외 메시지에 숫자 리터럴을 하드 코딩하는 대신에 `MAX_SIZE` 상수를 활용해보면 어떨까요?
나중에 최대 이미지 크기를 변경해야 한다면, 예외 메시지도 함께 변경해야 하는 번거로움이 생길 것 같아요.
- 예외 메시지에 실제로 전달된 이미지의 크기도 함께 출력해보면 디버깅에 도움이 될 것 같습니다.

2024-04-09 08:06 UTC, seondongpyo commented on src/main/java/nextstep/images/domain/Type.java
> +public enum Type {
`Type`이라는 이름만 보면 무엇에 대한 열거 타입인지 직관적으로 알기 어려울 것 같아요.
`CoverImageType` 또는 `ImageType` 정도로 이름을 지어보는 건 어떨까요?

2024-04-09 08:06 UTC, seondongpyo commented on src/main/java/nextstep/images/domain/Type.java
> +            .filter(value -> value.type.equals(type))
확장자가 대문자로 전달되는 경우도 정상적으로 처리되도록 편의성을 제공해보면 어떨까요?

2024-04-09 08:06 UTC, seondongpyo commented on src/main/java/nextstep/images/domain/Type.java
> +            .orElseThrow(() -> new IllegalArgumentException("지원하지 않는 이미지 타입입니다."));
여기 예외 메시지에도 실제로 전달된 파일의 확장자를 포함시키면 예외 원인 파악이 수월해질 것 같아요.

2024-04-09 08:06 UTC, seondongpyo commented on src/main/java/nextstep/sessions/domain/Status.java
> +public enum Status {
해당 열거 타입도 이름을 `SessionStatus` 정도로 지어보면 무엇애 대한 상태인지 직관적으로 알 수 있을 것 같아요.

2024-04-09 08:06 UTC, seondongpyo commented on src/main/java/nextstep/sessions/domain/Session.java
> +    private List<NsUser> attendees = new ArrayList<>();
멤버 변수가 상당히 많은데, 관련된 멤버 변수들을 묶어서 새로운 도메인을 추출해보면 어떨까요?
예를 들어 강의 시작일과 종료일을 하나로 묶어본다면, Session 생성 시 시작일과 종료일에 대한 유효성 검증(ex. 시작일보다 종료일이 더 이전 날짜인 경우) 로직을 내부로 옮겨볼 수 있을 것 같아요.

2024-04-09 08:06 UTC, seondongpyo commented on src/main/java/nextstep/sessions/domain/Session.java
> +    public Session(final Status status) {
Nit: 해당 생성자는 무료 강의를 생성하기 위해 추가하신 걸로 보입니다만, 생성자를 호출했을 때 생성되는 Session이 무료인지 유료인지 쉽게 구분이 되진 않을 것 같습니다.
아래와 같이 정적 팩토리 메서드를 추가해보면 이름을 통해 무료 Session을 생성한다는 것을 쉽게 알 수 있도록 편의성을 제공해볼 수도 있겠습니다. 개인적인 의견이니 참고만 해주세요.
```java
Session session = new Session(Status.PREPARING); // 생성자 호출
Session session = Session.free(Status.PREPARING); // 정적 팩토리 메서드 호출
```

2024-04-09 08:06 UTC, seondongpyo commented on src/main/java/nextstep/sessions/domain/Session.java
> +    private void validate(final long price) {
사용자가 이미 수강신청을 했는지에 대한 여부도 검증을 해보면 어떨까요?

2024-04-09 08:06 UTC, seondongpyo commented on src/main/java/nextstep/sessions/domain/Session.java
> +        if (status != Status.RECRUITING) {
메시지를 보내서 처리해보면 어떨까요?
```suggestion
        if (status.isRecruiting()) {
```

2024-04-09 08:09 UTC, seondongpyo commented
> 아이디를 기본 0L로 사용하고 있다는 것을 알 수 있는데요. 그렇다면 Q1과 Q2는 둘 다 아이디가 0L이 되는거 아닌가요? 서비스 테스트에서는 Q1만 사용하고 있어서 문제가 되지 않을 것 같지만, 이렇게 생성하는 것이 옳은 방식인지 궁금합니다!

실제 데이터베이스와 연동해야 하는 테스트라면 문제가 될 수 있겠지만, 지금은 그것보다는 도메인의 핵심 비즈니스 로직과 관련된 부분에 더 집중한다고 보시면 될 것 같습니다.

> 위의 질문과 같이 기존의 패키지명을 보면 courses, payments 등과 같이 복수로 되어 있습니다. 패키지명은 단순하게 소문자만을 허용한다고 알고 있는데요. 복수 형태로도 많이 짓는 편인지 궁금합니다!

이 부분은 물론 개발 조직마다 다를텐데, 저희는 주로 단수형으로 작성하고 있습니다.

2024-04-09 08:31 UTC, leeedohyun commented on src/main/java/nextstep/images/domain/CoverImage.java
> +    private void validate(final double size, final int width, final int height) {
추가한다는게 놓쳐버렸네요😅 추가하겠습니다!

2024-04-09 08:45 UTC, leeedohyun commented on src/main/java/nextstep/images/domain/Type.java
> +public enum Type {
고민하다가 `CoverImage`가 가지고 있기 때문에 알기 쉽다고 생각했는데, `Type`만 봤을 때는 구체적이지 못하네요. 변경하겠습니다!

2024-04-09 11:58 UTC, leeedohyun commented on src/main/java/nextstep/sessions/domain/Session.java
> +    public Session(final Status status) {
저도 강의가 생성될 때 무료인지 유료인지 구분하고 싶다는 생각을 가지긴 했어서 구분하는게 더 좋을 것 같네요!

2024-04-09 11:58 UTC, leeedohyun commented on src/main/java/nextstep/sessions/domain/Session.java
> +    private void validate(final long price) {
반영했습니다!

2024-04-09 11:59 UTC, leeedohyun commented on src/main/java/nextstep/sessions/domain/Session.java
> +        if (status != Status.RECRUITING) {
이게 더 객체 지향적인 설계겠네요!

2024-04-09 12:04 UTC, leeedohyun reviewed
안녕하세요 선동님! 피드백 반영 완료했습니다.
추가적으로 조금 과하다 싶을 정도로 `Session`의 인스턴스 변수들을 포장해봤는데요. 부족한 점이 있다면 다시 피드백 부탁드리겠습니다!🙇‍♂️

# 수정한 부분
- `Session`의 시작일과 종료일을 `SessionPeriod`로 포장했습니다.
- `Session`의 참여자 리스트를 `Users` 일급 컬렉션으로 포장했습니다.
-  `Session`의 가격을 `SessionPrice`로 포장했습니다.

2024-04-10 08:20 UTC, seondongpyo approved these changes
피드백 반영 잘해주셨네요 👍 
이번 단계는 여기서 merge 하겠습니다.
다음 단계에서 뵐게요 🔥

2024-04-10 08:20 UTC, seondongpyo commented on src/main/java/nextstep/images/domain/CoverImage.java
> +    }
숫자 리터럴 `300`, `200`도 위에 선언된 상수로 표현해보면 어떨까요?

2024-04-10 08:20 UTC, merged

2024-04-10 08:30 UTC, leeedohyun commented on src/main/java/nextstep/images/domain/CoverImage.java
> +    }
이 부분 놓쳤네요😅 다음 단계에서 반영하겠습니다!!