🚀 3단계 - 수강신청(DB 적용)
next-step/java-lms pull request #467
Opened 2024-04-11 09:00 UTC by leeedohyun

안녕하세요. 선동님!
2단계까지 설계한 도메인 모델을 테이블과 매핑하는 것이 어색했습니다😢 부족한 부분이 있다면 많은 지적 부탁드립니다!!
3단계도 잘 부탁드려요🙇‍♂️

# 고민한 부분
## 다대다 관계를 어떻게 풀어낼 것인가?
테이블을 설계하려고 하다 보니, `Session`과 `NsUser`과 다대다 관계라는 것을 알게 되었습니다. 다대다 관계는 `일대다`와 `다대다` 관계로 풀어야 하는 것은 알고 있었지만 도메인 설계할 때는 전혀 고려하지 못했습니다. 그래서 `Enrollment`이라는 중간 객체를 만들었습니다. 이렇게 테이블을 설계할 때 분리하기 보다는 처음부터 도메인을 설계할 때 다대다 관계라면 `일대다`와 `다대다` 관계로 풀어서 설계하는 것이 낫다고 판단했는데, 선동님은 어떻게 하시는지 궁금합니다!

# 궁금한 점
## final 키워드를 이렇게 사용하는 것이 좋은가?
저는 `내 코드가 그렇게 이상한가?`라는 책을 읽고 저자는 가변으로 인해 의도와는 다르게 동작할 수 있기 때문에 기본은 불변을 권장합니다. 저도 이 저자의 말에 동의해서 지금까지 메서드 파라미터, 지역 변수 등 다양한 곳에서 final을 붙여 쓰고 있습니다. 궁금한 점은 현업에서는 이렇게 `final`을 사용하는지 궁금합니다!

## 연관 관계도 도메인을 설계할 때 고민하면 좋은가?
2단계에 연관 관계를 신경쓰지 않고 구현했기 때문에 테이블을 설계하면서 연관 관계를 고려해야 했습니다. 도메인을 설계할 때 도메인 간의 연관 관계만을 고려하고, 추후에 이를 기반으로 테이블을 설계하면 될까요?

2024-04-12 05:03 UTC, seondongpyo requested changes
3단계 미션도 잘 작성해주셨네요 👍 
다만 `앞 단계에서 구현한 도메인 모델을 DB 테이블과 매핑하고, 데이터를 저장한다.` 라는 요구사항을 충족하지 않고 있는 것으로 보여요. 도메인 모델에 해당하는 Repository를 추가하고 저장하는 로직을 작성하시고 단위 테스트도 작성해주시면 좋을 것 같습니다.
몇 가지 코멘트 드렸는데 확인 후 다시 리뷰 요청을 부탁 드리겠습니다.

2024-04-12 05:03 UTC, seondongpyo commented on src/main/java/nextstep/enrollment/domain/Enrollment.java
> +public class Enrollment {
> 테이블을 설계하려고 하다 보니, Session과 NsUser과 다대다 관계라는 것을 알게 되었습니다. 다대다 관계는 일대다와 다대다 관계로 풀어야 하는 것은 알고 있었지만 도메인 설계할 때는 전혀 고려하지 못했습니다. 그래서 Enrollment이라는 중간 객체를 만들었습니다. 이렇게 테이블을 설계할 때 분리하기 보다는 처음부터 도메인을 설계할 때 다대다 관계라면 일대다와 다대다 관계로 풀어서 설계하는 것이 낫다고 판단했는데, 선동님은 어떻게 하시는지 궁금합니다!

다대다 관계 문제를 중간 객체를 통해 아주 잘 풀어내셨습니다 👍
저도 다대다 관계는 일대다, 다대일 관계로 풀어서 설계하려는 편입니다.

2024-04-12 05:03 UTC, seondongpyo commented on src/main/java/nextstep/enrollment/domain/Enrollment.java
> +        session.getEnrollments().add(this);
`Session`에서 값을 꺼내는 대신에 메시지를 보내서 처리해보면 어떨까요?

2024-04-12 05:03 UTC, seondongpyo commented on src/main/java/nextstep/images/domain/CoverImage.java
> +    private Session session;
`Session`의 식별자만 가지고 있어도 충분하지 않을까요? `Session`을 상태로 추가하신 이유가 궁금합니다.

2024-04-12 05:03 UTC, seondongpyo commented on src/main/java/nextstep/qna/infrastructure/JdbcAnswerRepository.java
>  public class JdbcAnswerRepository implements AnswerRepository {
> 그런데, 이렇게 구현을 하면 서비스가 확장을 할 때 다른 Repository에서도 조회하는 로직이 필요할텐데, 그럴 때마다 private 메서드로 구현해야 될까란 생각을 하게 되었습니다. 그래서 이 로직들을 각각 JdbcUserRepository와 JdbcQuestionRepository로 분리하려 했습니다. 만약 분리를 한다면 JdbcAnswerRepository가 JdbcUserRepository와 JdbcQuestionRepository에 의존해야 했습니다. 이렇게 설계하는 것은 옳지 않다고 생각했고, 더 나은 방법이 생각이 나지 않아 우선 private 메서드로 구현했습니다. 이 부분을 더 분리할 수 있는 좋은 방법이 있을까요?

- 개인적인 의견을 드리자면, 저는 `JdbcAnswerRepository`에 추가로 필요한 `Repository`들을 의존하도록 설계할 것 같아요.  말씀하신 것처럼 private 메서드가 우후죽순 늘어날 가능성을 제외할 수 있고, 각각의 private 메서드가 하는 일이 `JdbcAnswerRepository`의 책임이 아닌 각 객체의 `Repository`의 역할이라고 보기 때문입니다.
- 이 부분은 3단계 미션과 직접적인 관계가 없는데 수정하신 이유가 있으실까요?

2024-04-12 05:03 UTC, seondongpyo commented on src/main/java/nextstep/sessions/domain/Session.java
>  public class Session {
추가하신 도메인들에 대한 저장 로직을 각각의 `Repository`를 생성하여 처리해보면 어떨까요?

2024-04-12 05:03 UTC, seondongpyo commented on src/main/java/nextstep/sessions/domain/Session.java
> +    public Session(final int maxEnrollment, final SessionStatus sessionStatus, final long price,
> 저는 내 코드가 그렇게 이상한가?라는 책을 읽고 저자는 가변으로 인해 의도와는 다르게 동작할 수 있기 때문에 기본은 불변을 권장합니다. 저도 이 저자의 말에 동의해서 지금까지 메서드 파라미터, 지역 변수 등 다양한 곳에서 final을 붙여 쓰고 있습니다. 궁금한 점은 현업에서는 이렇게 final을 사용하는지 궁금합니다!

개발 조직마다 다르겠지만, 제가 있는 조직에서는 매개변수마다 `final` 키워드를 붙이진 않습니다.
물론 가변성을 제한함으로써 코드의 안정성을 높이고 버그를 방지하는 데 도움이 됩니다만, 코드가 불필요하게 장황해질 수 있고 그로 인해 가독성을 저하시킨다는 단점도 있습니다. 또한 참조형 변수가 전달되는 경우는 `final`이 그 대상을 반드시 불변으로 만들지 않습니다. 재할당이 안 되는 것일 뿐이지 내부의 상태는 변경할 수도 있으니, 이런 경우에는 `final` 키워드가 크게 의미가 없을 수도 있습니다.

여기까지는 개인적인 의견이었고, 결국엔 같이 코드를 작성하는 동료들과의 충분한 의사소통을 통해 코딩 스타일을 맞추는 것이 가장 중요하다고 생각합니다.

2024-04-12 05:03 UTC, seondongpyo commented on src/main/java/nextstep/sessions/domain/Session.java
>  public class Session {
> 2단계에 연관 관계를 신경쓰지 않고 구현했기 때문에 테이블을 설계하면서 연관 관계를 고려해야 했습니다. 도메인을 설계할 때 도메인 간의 연관 관계만을 고려하고, 추후에 이를 기반으로 테이블을 설계하면 될까요?

도메인 간의 연관 관계를 먼저 고려하여 모델을 설계하고, 이를 기반으로 테이블을 설계하는 것이 일반적입니다. 
그러나 ORM을 공부해보셨으면 아시겠지만 OOP에서의 연관 관계와 데이터베이스에서의 연관 관계는 다를 수 있습니다. 또한 도메인 모델이 데이터베이스 설계를 완전히 제어하지는 않기 때문에 성능 최적화, 쿼리 효율, 트랜잭션 관리 등 데이터베이스와 관련된 특정 부분들은 데이터베이스에 맞게 코드에 반영해야 할 수도 있다는 점도 고려해야 할 사항입니다.

2024-04-12 08:13 UTC, leeedohyun commented on src/main/java/nextstep/enrollment/domain/Enrollment.java
> +        session.getEnrollments().add(this);
맞네요! 반영하겠습니다!

2024-04-12 08:18 UTC, leeedohyun commented on src/main/java/nextstep/images/domain/CoverImage.java
> +    private Session session;
저도 처음에는 `Session`의 id만 가지고 있으면 될 것 같다는 생각은 했는데, `Session`을 추가한 이유는 크게 없는 것 같아요! 단순하게 이전에 계속 연관 관계를 고려할 때 객체로만 하다 보니 그렇게 구현했네요. 이미지 같은 경우에는 `Session`의 식별자만 가지고 있어도 된다고 생각합니다!

2024-04-12 08:21 UTC, leeedohyun commented on src/main/java/nextstep/qna/infrastructure/JdbcAnswerRepository.java
>  public class JdbcAnswerRepository implements AnswerRepository {
> 이 부분은 3단계 미션과 직접적인 관계가 없는데 수정하신 이유가 있으실까요?

별 다른 이유는 없습니다. CRUD 코드를 작성에 신경쓰다 보니 수강 신청과 관련 없는 부분을 구현했네요😅

2024-04-12 08:21 UTC, leeedohyun commented on src/main/java/nextstep/sessions/domain/Session.java
>  public class Session {
넵! 반영하겠습니다.

2024-04-12 08:23 UTC, leeedohyun commented on src/main/java/nextstep/sessions/domain/Session.java
> +    public Session(final int maxEnrollment, final SessionStatus sessionStatus, final long price,
> 참조형 변수가 전달되는 경우는 final이 그 대상을 반드시 불변으로 만들지 않습니다. 재할당이 안 되는 것일 뿐이지 내부의 상태는 변경할 수도 있으니, 이런 경우에는 final 키워드가 크게 의미가 없을 수도 있습니다.

이 부분은 저도 동의합니다. 첨조형인 경우에는 의미가 없을 수도 있죠....😢

2024-04-13 09:39 UTC, leeedohyun reviewed
안녕하세요 선동님. 주말 잘 보내고 계신가요?
리뷰 반영하면서 리팩토링 해봤어요!

## 리팩토링한 부분

- `Session`에서 값을 꺼내는 대신에 메시지를 보내서 `Enrollment` 리스트에 추가
- `CoverImage`가 `Session`의 식별자만 가지도록 변경

## 추가한 부분

- `Session`과 `Enrollment`에 대한 저장 로직 `Repository`에 구현 및 테스트

2024-04-14 04:18 UTC, seondongpyo approved these changes
피드백 반영 잘해주셨네요 👍 
이번 단계는 여기서 merge 하겠습니다.
남은 주말 잘 쉬시고 다음 단계서 뵐게요 🔥

2024-04-14 04:18 UTC, merged