feat: 1단계 - 레거시 코드 리팩터링
next-step/java-lms pull request #473
Opened 2024-04-12 14:11 UTC by jaejeong1

2024-04-13 04:19 UTC, mskangg requested changes
안녕하세요 재정님
이번 미션 리뷰를 맡은 강민수입니다 🙇

1단계 미션 정말 깔끔하게 잘 구현해주셨어요! 👍 
다만, 테스트코드가 없어 이부분 확인만 부탁드려요!

2024-04-13 04:19 UTC, mskangg commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(deleteHistories.getValue());
Service 레이어가 굉장히 얇아졌군요 👍 💯

2024-04-13 04:19 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Answer.java
> +        return new DeleteHistory(ContentType.ANSWER, this.id, this.writer, LocalDateTime.now());
```suggestion
        return DeleteHistory.createAnswer(this.id, this.writer, LocalDateTime.now());
```

삭제이력은 답변, 질문 모두 있으니
위와 같이 정적생성자를 사용해도 될것 같아요!

2024-04-13 04:19 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Answers.java
> +    }
👍

2024-04-13 04:19 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Answer.java
> +    public DeleteHistory delete(NsUser loginUser) throws CannotDeleteException {
커밋이 누락된것인지 테스트코드가 하나도 없네요 😅

2024-04-13 06:12 UTC, jaejeong1 commented on src/main/java/nextstep/qna/domain/Answer.java
> +        return new DeleteHistory(ContentType.ANSWER, this.id, this.writer, LocalDateTime.now());
네, 객체 생성 로직을 드러내기 보다 캡슐화하는게 나아보이네요. 감사합니다!!

2024-04-13 06:12 UTC, jaejeong1 commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(deleteHistories.getValue());
감사합니다 :)

2024-04-13 10:49 UTC, jaejeong1 commented on src/main/java/nextstep/qna/domain/Answer.java
> +    public DeleteHistory delete(NsUser loginUser) throws CannotDeleteException {
테스트코드가 빠졌군요 ㅠㅠ 추가 완료했습니다 :)

2024-04-13 10:52 UTC, jaejeong1 reviewed
피드백 반영했습니다.

2024-04-14 07:49 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요~!
그런데, 현재 master branch 에 작업해주셨어요.
다음 단계 진행시 branch 이름을 단계별로 지정 부탁드립니다! (ex. step2)
그럼 화이팅 🔥

2024-04-14 07:49 UTC, mskangg commented on src/test/java/nextstep/qna/domain/QuestionTest.java
> +@ExtendWith(MockitoExtension.class)
유닛테스트에 mockito 를 추가한 이유가 있을까용?

2024-04-14 07:49 UTC, merged