4단계 - 요구사항 변경
next-step/java-lms pull request #481
Opened 2024-04-14 03:03 UTC by oht1221

안녕하세요 현구님, 4단계 리뷰요청 드립니다 :)

2024-04-15 03:43 UTC, Hyeon9mak requested changes
안녕하세요 홍택님! 어느덧 마지막 미션이네요! 👍 
간단한 코멘트 몇 가지 남겼으니 확인해주세요!

2024-04-15 03:43 UTC, Hyeon9mak commented on src/main/java/nextstep/courses/domain/Course.java
> +    }
id 에 대한 불변 확보 👍 
정말로 '엔티티'가 되었네요 😄 👍

2024-04-15 03:43 UTC, Hyeon9mak commented on src/main/java/nextstep/courses/domain/Session.java
>    }
미리 메서드를 통해 이름을 부여해둔 덕분에, `addStudent` 내부에서는 큰 변화 없이 자연스러운 형태로 코드가 변경될 수 있었네요!

2024-04-15 03:43 UTC, Hyeon9mak commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionImageRepository.java
> +  );
RowMapper 활용 👍

2024-04-15 03:43 UTC, Hyeon9mak commented on src/main/java/nextstep/courses/service/CourseService.java
> +
접근제한을 관리해줄 수 있겠어요!

2024-04-15 03:43 UTC, Hyeon9mak commented on src/main/java/nextstep/courses/service/CourseService.java
> +  }
service 계층이 domain, persistence 계층과 소통만 담당하네요 👍

2024-04-15 03:43 UTC, Hyeon9mak commented on src/main/resources/schema.sql
> +    primary key (id)
> - DB 테이블에 데이터가 존재한다는 가정하에 리팩터링해야 한다.
> - 즉, 기존에 쌓인 데이터를 제거하지 않은 상태로 리팩터링 해야 한다.

요런 요구사항이 있었는데요, schema 가 요렇게 변경된다면 기존 데이터들 모두에 영향이 전파될 것 같아요.
기존 `create table` ddl 은 두고, 신규로 테이블 속성을 변경하는 ddl 을 작성해보는 건 어떨까요?

2024-04-15 03:43 UTC, Hyeon9mak commented on src/test/java/nextstep/courses/infrastructure/SessionImageRepositoryTest.java
> +//    jdbcTemplate.update("DELETE FROM session_image");
👀

2024-04-16 14:09 UTC, oht1221 commented on src/main/java/nextstep/courses/service/CourseService.java
> +
아 접근 제어자를 깜박했네요 ㅎㅎ private 추가했습니다!

2024-04-16 14:10 UTC, oht1221 commented on src/main/resources/schema.sql
> +    primary key (id)
아하 제가 교수사항을 제대로 파악을 못했네요 ㅠ 말씀해주신대로 기존 insert DDL은 두고 update DDL을 작성하였습니다!

2024-04-16 14:11 UTC, oht1221 commented on src/test/java/nextstep/courses/infrastructure/SessionImageRepositoryTest.java
> +//    jdbcTemplate.update("DELETE FROM session_image");
주석 제거를 깜박했네요 😂 제거하였습니다!

2024-04-17 11:37 UTC, Hyeon9mak requested changes
안녕하세요 홍택님! approve 직전 마아아아아지막 코멘트 하나만 남겼습니다!
다음 리뷰 요청 때 별도로 질문 없으시면 approve 하려고 합니다!
마지막 까지 화이팅!!

2024-04-17 11:37 UTC, Hyeon9mak commented on src/main/resources/schema.sql
> +ADD CONSTRAINT pk_registration PRIMARY KEY (id);
기존 데이터가 존재하는 상황에서 갑작스럽게 not null 컬럼이 새로 추가되면, 문제가 발생할 것 같아요 😱 
(아마도 DDL 이 정상적으로 동작하지 않을거에요.)

2가지 해결방법이 있을 것으로 생각되는데요,

1. 우선 nullable 한 컬럼으로 만든 후, 기존 데이터를 마이그레이션 후 not null 로 변경한다.
2. 현재 ddl 에 `DEFAULT` 키워드로 기본 값을 채워주고, 나중에 다시 데이터를 마이그레이션 한다.

2024-04-17 14:56 UTC, oht1221 commented on src/main/resources/schema.sql
> +ADD CONSTRAINT pk_registration PRIMARY KEY (id);
아하 그러네요, 실제 운영환경이라면 이미 기존 데이터가 있는 상황이라 not null 컬럼을 추가할 수가 없겠네요. 아마 저의 경우에는 기존 데이터가 하나도 없는 상황이라 문제 없이 실행되어서 캐치하지 못했던 것 같습니다. 리뷰 감사드립니다! 👍

2024-04-18 09:13 UTC, Hyeon9mak approved these changes
안녕하세요 홍택님! 마지막 미션까지 고생 많으셨습니다 👍 👍 
요구사항도 모두 만족되었고 잘 변경해주셔서 마지막 미션 approve 하려고 합니다.

그간 남겨드린 코멘트들이 도움이 되셨을까요?
홍택님과 여러가지 의견을 교류하면서 저도 한걸음 더 성장한 시간이었던거 같습니다. 🙇‍♂️ 
홍택님도 과정이 즐거우셨길 바라면서 마무리 하도록 하겠습니다!

고생 많으셨습니다!!

2024-04-18 09:13 UTC, merged