[STEP 2] 수강 신청 도메인 모델 (kylekim2123, 김영주)
next-step/java-lms pull request #483
Opened 2024-04-14 06:07 UTC by kylekim2123

### PR 개요
- "step 2 수강 신청 도메인 모델"에 대한 수행 내용을 제출합니다.

---

### 기능 요구사항
1. `강의(Session)`
   - [x]  스케줄, 커버 이미지, 상태, 종류, 과정을 기준으로 새로운 강의를 생성한다.
   - [x]  특정 강의에 대한 수강 신청을 한다.
   - [x]  강의 상태가 “모집중”이 아닐 때, 수강 신청하는 경우 예외를 던진다.
   - [x]  유료 강의의 수강 인원 제한을 초과하는 경우 예외를 던진다.
   - [x]  유료 강의의 수강 인원 제한이 최소 인원 제한 미만인 경우 예외를 던진다.
   - [x]  유료 강의의 결제 금액과 수강료가 일치하지 않는 경우 예외를 던진다.
   - [x]  수강료가 최소 수강료 미만인 경우 예외를 던진다.
2. `이름(Name)`
   - [x]  문자열을 기준으로 새로운 이름을 생성한다.
   - [x]  문자열이 null인 경우 예외를 던진다.
   - [x]  문자열이 빈 문자열, 공백, 개행인 경우 예외를 던진다.
3. `스케줄(Schedule)`
   - [x]  강의 시작일과 종료일을 기준으로 새로운 스케줄을 생성한다.
   - [x]  강의 종료일이 시작일 보다 앞선 경우 예외를 던진다.
4. `커버 이미지(CoverImage)`
   - [x]  크기, 종류, 너비, 높이를 기준으로 새로운 커버 이미지를 생성한다.
   - [x]  크기(Size)가 0MB 이하이거나 1MB를 초과하는 경우 예외를 던진다.
   - [x]  종류가 gif, jpg, jpeg, png, svg 이외인 경우 예외를 던진다.
   - [x]  너비가 300px 미만인 경우 예외를 던진다.
   - [x]  높이가 200px 미만인 경우 예외를 던진다.
   - [x]  너비와 높이의 비율이 3:2가 아닌 경우 예외를 던진다.
5. `상태(SessionStatus)`
   - [x]  준비중, 모집중, 종료 이외의 상태인 경우 예외를 던진다.

---

감사합니다.

2024-04-14 08:05 UTC, kylekim2123 reviewed
감사합니다 :)

2024-04-14 08:05 UTC, kylekim2123 commented on src/main/java/nextstep/qna/domain/question/Answer.java
> +        validateQuestionIsNotNull(question);
[지난 리뷰](https://github.com/next-step/java-lms/pull/441#discussion_r1557120616)
- 말씀하신대로 검증 로직을 별도의 메서드로 분리했습니다.

2024-04-14 08:05 UTC, kylekim2123 commented on src/main/java/nextstep/qna/domain/question/Answers.java
> +                .collect(Collectors.toUnmodifiableList());
[지난 리뷰](https://github.com/next-step/java-lms/pull/441#discussion_r1557121958)
- 향상된 for문으로 되어있던 로직을 Stream API를 이용하는 방향으로 변경했습니다.

2024-04-15 05:02 UTC, ksy90101 requested changes
안녕하세요.
2단계 너무 잘 해주셨네요!!!!
큰 피드백은 없지만, 그래도 한번 집고 넘어가면 좋을게 있어 Request Change를 해봤습니다
확인부탁드려요~

2024-04-15 05:02 UTC, ksy90101 commented on src/main/java/nextstep/courses/domain/course/CourseRepository.java
> +    Course findById(final Long id);
Optional을 적용해서 Course가 null이 나오는 경우를 처리하면 어덜까요?

2024-04-15 05:02 UTC, ksy90101 commented on src/main/java/nextstep/courses/domain/course/Course.java
>  public class Course {
Coures가 Session의 List를 가지고 있어야 하지 않을까요?
하나의 교육은 여러개의 기수가 될수 잇다.

2024-04-15 05:02 UTC, ksy90101 commented on src/main/java/nextstep/courses/domain/session/Session.java
> +    private final Long courseId;
객체지향적으로 한게 아니라 courseId로 한 이유가 있나요?

2024-04-15 05:02 UTC, ksy90101 commented on src/main/java/nextstep/courses/domain/session/Session.java
> +    }
원시값을 리턴하는게 더 좋지 않을까요?

2024-04-15 16:05 UTC, kylekim2123 commented on src/main/java/nextstep/courses/domain/course/CourseRepository.java
> +    Course findById(final Long id);
반영 : [b1ddf28](https://github.com/next-step/java-lms/pull/483/commits/b1ddf2844646475aba9ffdc7aa13ab26b358a54c)
- findById에 대해 Optional 처리를 했습니다.

2024-04-15 16:05 UTC, kylekim2123 commented on src/main/java/nextstep/courses/domain/course/Course.java
>  public class Course {
반영 : [ecd1b8a](https://github.com/next-step/java-lms/pull/483/commits/ecd1b8ab5e716ce71450a0c54e3c21fc026b2445)
- 맞습니다! 일급컬렉션 이용해서 Sessions 객체를 가지도록 변경했습니다.

2024-04-15 16:06 UTC, kylekim2123 commented on src/main/java/nextstep/courses/domain/session/Session.java
> +    private final Long courseId;
반영 : [ecd1b8a](https://github.com/next-step/java-lms/pull/483/commits/ecd1b8ab5e716ce71450a0c54e3c21fc026b2445)
- 기존 레거시 코드에서는 연관관계에 대해서 객체가 아니라 id로 되어있어서 통일 하려고 했습니다.
- 그런데 굳이 그럴필요 없을 것 같아서, Course 객체를 참조하도록 변경했습니다.

2024-04-15 16:06 UTC, kylekim2123 commented on src/main/java/nextstep/courses/domain/session/Session.java
> +    }
반영 : [ecd1b8a](https://github.com/next-step/java-lms/pull/483/commits/ecd1b8ab5e716ce71450a0c54e3c21fc026b2445)
- 해당 내용 반영 했습니다!

2024-04-16 07:59 UTC, ksy90101 approved these changes
남긴 피드백 너무 잘 적용해주셨네요!!
요구사항들을 모두 잘 충족해주셔서, 이미 이 미션을 해보신거 같은 느낌이 들었습니다 ... ㅎㅎ
2단계는 마무리 하고 3단계에서 뵐게요~
홧팅입니다!

언제든 질문이 있다면 DM주세요!

2024-04-16 08:00 UTC, merged