[Step3] 수강신청(DB 적용)
next-step/java-lms pull request #491
Opened 2024-04-14 15:42 UTC by Danden1

안녕하세요!

이전 피드백들 반영완료했습니다.

자잘한 실수를 많이 하네요.

궁금한 점은 코멘트로 남겼습니다!

감사합니다.

2024-04-14 15:47 UTC, Danden1 commented on src/main/java/nextstep/courses/infrastructure/JdbcCourseRepository.java
> -        String sql = "insert into course (title, creator_id, created_at) values(?, ?, ?)";
기존에는 id를 자동으로 만들어줘서 넣게 했었습니다. 그럴 경우 아래 부분에서 문제가 발생합니다.

2024-04-14 15:47 UTC, Danden1 commented on src/main/java/nextstep/courses/infrastructure/JdbcCourseRepository.java
> +                sessionRepository.savePaySession((PaySession) session, course.getId());
여기에서 문제가 발생합니다. 제가 DB 테이블을 설계할 때 `Session`들은 fk로 `Course`의 id를 가지게 했습니다.

여기서 문제는 해당  실제로 db에 들어간 `Course`의 아이디를 알 수 있는 방법이 없습니다.

<br>

그래서 id로 조회하기 보다는 `Course`제목으로 조회하는 기능을 만들어서 이용하려고 했습니다. 그리고 `Course`를 insert하면, id가 생성될 것 입니다. db에서 제목으로 id를 조회한 후 `Session`을 저장하려고 했습니다. 

하지만 이러면 중간에 db에서 조회하는 과정이 필요한데, 이는 성능이 저하될 것 같습니다.

<br>

그래서 이를 테스트하기 위해 자동으로 id를 만드는 부분을 없애고 했습니다.

실무에서는 꼭 필요한 기능 같은데, 이를 빼는 건 좀 아닌 것 같습니다.  실무에서는 이러한 문제를 어떻게 해결하나요?

2024-04-15 09:36 UTC, testrace requested changes
안녕하세요 용하님 😃 
3단계 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청 부탁드려요

2024-04-15 09:36 UTC, testrace commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-web'
라이브러리를 추가하신 이유가 있으실까요?

2024-04-15 09:36 UTC, testrace commented on src/main/java/nextstep/courses/domain/Course.java
> +        this.sessions = new Sessions();
부 생성자는 주 생성자를 호출하면 어떨까요?

2024-04-15 09:36 UTC, testrace commented on src/main/java/nextstep/courses/domain/SessionRepository.java
> +    void saveFreeSession(FreeSession freeSession, Long courseId);
강의의 타입이 늘어나면 인터페이스도 늘어날 것 같은데요
추상 메서드인만큼 PaySession, FreeSession 을 나누지 않고 Session을 조회하면 어떨까요?

2024-04-15 09:36 UTC, testrace commented on src/main/java/nextstep/courses/infrastructure/JdbcCourseRepository.java
> +                sessionRepository.savePaySession((PaySession) session, course.getId());
자동생성되는 키 값이 필요하다면 KeyHolder 를 활용합니다

2024-04-15 09:36 UTC, testrace commented on src/main/resources/schema.sql
> +);
두 테이블에는 중복되는 필드가 존재하는데요 
중복 필드를 제거하면 어떨까요?

2024-04-15 09:36 UTC, testrace commented on src/main/resources/schema.sql
> +);
이미지까지 테이블을 나눌 필요가 있을까요?
나누게 된 계기가 궁금합니다 🤔

2024-04-15 09:36 UTC, testrace commented on src/main/resources/schema.sql
> +);
pay, free 외에 타입이 추가된다면 테이블은 3개가 추가되어야 하고, repository 코드도 많이 추가되어야 할 것 같아요
중복된 필드나 코드가 적지 않을 것 같은데 의도하신 바가 맞으신지 궁금합니다

2024-04-15 09:36 UTC, testrace commented on src/test/java/nextstep/courses/domain/SessionsTest.java
> +        assertThat(sessions.getSessions()).hasSize(2).containsExactly(TestSessionFactory.recruitStatusSession(sessionId1), TestSessionFactory.recruitStatusSession(sessionId2));
테스트가 실패하네요 😢 
<img width="1206" alt="image" src="https://github.com/next-step/java-lms/assets/8064743/eee06823-7857-427f-8c09-ae93c61049f6">

2024-04-15 09:36 UTC, testrace commented on src/test/java/nextstep/courses/domain/utils/TestSession2.java
> +public class TestSession2 extends Session {
클래스명이나 변수명은 넘버링 대신 의미를 드러낼 수 있게 네이밍하면 어떨까요?

2024-04-15 10:17 UTC, Danden1 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-web'
Application(Spring)을 실행하자마자 바로 종료되어서 추가했었습니다. 이 부분 수정하겠습니다!

2024-04-15 10:18 UTC, Danden1 commented on src/main/resources/schema.sql
> +);
이미지는 합쳐도 될 것 같습니다!

2024-04-15 10:21 UTC, Danden1 commented on src/main/resources/schema.sql
> +);
제 개인적으로는 최대한 테이블을 나누고 싶었습니다. 그 이유는 나중에 쿼리를 실행할 때, 원하는 `Session`을 찾기 수월해서 입니다. 또한 다른 타입의 `Session`에 변경점이 생길 경우 테이블 구조를 바꾸기 용이할 것 같아서 이렇게 분리했었습니다.

실제로 제가 재직 중인 회사에서는 하나의 테이블에 여러 데이터를 넣는 경우가 있습니다. 이 경우 특정 기능에 따라서 컬럼을 추가 하고 싶은데, 이를 하는 것이 거의 불가능합니다. 또한 데이터가 방대해지다 보니, 원하는 데이터를 찾는데 시간이 너무 오래 걸렸었습니다.

이러한 경험을 바탕으로 저는 테이블을 분리했었습니다!

2024-04-15 10:21 UTC, Danden1 commented on src/main/resources/schema.sql
> +);
넵. 맞습니다! 위의 코멘트에 답변 달았습니다.

2024-04-15 10:22 UTC, Danden1 commented on src/test/java/nextstep/courses/domain/SessionsTest.java
> +        assertThat(sessions.getSessions()).hasSize(2).containsExactly(TestSessionFactory.recruitStatusSession(sessionId1), TestSessionFactory.recruitStatusSession(sessionId2));
확인해보겠습니다! 😢

2024-04-15 10:22 UTC, Danden1 commented on src/test/java/nextstep/courses/domain/utils/TestSession2.java
> +public class TestSession2 extends Session {
수정하겠습니다.

2024-04-15 15:45 UTC, Danden1 commented
안녕하세요.

- `Course` key 자동으로 생성하게 설정 및 KeyHolder 이용
- `SeesionRepository` method 추상화
- `SessionsTest` 테스트 실패 해결
- 부 생성자 주 생성자 호출하도록 변경
- 불필요한 라이브러리 삭제
- `TestSession2` 이름 변경


테이블 설계 관련해서는 코멘트로 남겼습니다!

2024-04-16 10:12 UTC, Danden1 commented on src/main/resources/schema.sql
> +);
하지만 하나의 fk에 여러 table이 참조될 수 없습니다. 제가 개발한 것처럼 sessiondl 나누어져있다면, 합치지 못할 것 같습니다.

2024-04-16 16:17 UTC, testrace approved these changes
안녕하세요 용하님 😃 
소소하게 코멘트 하나 남겼습니다
확인해 주시고 다음 단계 진행해 주세요

2024-04-16 16:17 UTC, testrace commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionRepository.java
> +        }
경험하셨던 문제를 해결하기 위해 다른 방법을 적용해 보시는 것은 좋다고 생각합니다 
다만 이 방법에서는 다른 문제가 생기는데요
Session의 하위 타입이 생기면 if 분기 추가가 필요합니다. 
find~ 메서드뿐 아니라 save~ 메서드에서도 타입만큼 분기가 필요하게 되고, JdbcSessionRepository는 엄청나게 커질 것이라 쉽게 예상되는데요
find, save 외 다른 기능까지 추가된다면 테이블의 수 만큼 메서드도 늘어나야 합니다.
테이블을 분리했다면 Repository 구현체들도 분리하는 등 새롭게 생긴 이슈에 대한 해결책에 대해서도 고민해 보시면 좋을 것 같습니다.

2024-04-16 16:17 UTC, testrace commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionRepository.java
> +import nextstep.users.domain.UserRepository;
사용하지 않는 코드, 주석, import는 제거해 주시면 좋을 것 같아요

2024-04-16 16:18 UTC, merged