Step2: 수강신청
next-step/java-lms pull request #492
Opened 2024-04-14 15:52 UTC by chyjeon

안녕하세요 리뷰어님! 
step2 수강신청을 구현하여 리뷰요청드립니다.
이번 과제도 잘 부탁드립니다!

2024-04-15 03:48 UTC, Hyeon9mak requested changes
안녕하세요 창열님! 2단계 잘 진행해주셨습니다 👍 
간단한 코멘트 남겼으니 확인해주세요!

2024-04-15 03:48 UTC, Hyeon9mak commented on src/test/java/nextstep/courses/domain/ImageTest.java
> +    }
경계값을 이용한 VO test 👍

2024-04-15 03:48 UTC, Hyeon9mak commented on src/main/java/nextstep/courses/domain/Session.java
> +    }
sessionStatus 에게 부정형으로 물어본다면, if 키워드 사이 눈에 잘 띄지 않는 `!` 를 제거해볼 수 있겠네요!

```java
sessionStatus.isNotRecruiting()
```

2024-04-15 03:48 UTC, Hyeon9mak commented on src/main/java/nextstep/courses/domain/SessionStudentCount.java
> +}
https://hyeon9mak.github.io/github-no-newline-at-a-end-of-file/
😉

2024-04-15 03:48 UTC, Hyeon9mak commented on src/test/java/nextstep/courses/domain/ImageTest.java
> +    }
`@DisplayName` 에 테스트 의도를 더욱 명확히 나타내고,
용량과 같이 경계값을 이용해 테스트를 작성하는 것은 어떨까요?

2024-04-15 14:43 UTC, chyjeon commented on src/main/java/nextstep/courses/domain/SessionStudentCount.java
> +}
개행은 항상 듣는데 잘 고쳐지지 않네요.. 익숙해지도록 노력하겠습니다!

2024-04-15 14:53 UTC, chyjeon commented on src/test/java/nextstep/courses/domain/ImageTest.java
> +    }
경계값을 활용하겠습니다!

2024-04-16 09:45 UTC, Hyeon9mak approved these changes
안녕하세요 창열님! 피드백 잘 반영해주셨습니다 👍 
깃 커밋은 추후 롤백 지점을 잡기 위한 가장 작은 단위일텐데요,
어떤 작업들이 있었는지 더욱 명확히 구분하고 롤백 기준을 잡아내기 위해
"리뷰 반영" 대신 "Image 테스트 코드를 경계값을 이용하도록 수정" 등으로 자세하게 변경하면 더욱 좋을거 같아요 😉 
다음 단계부터는 요런 부분도 신경써주시면 더욱! 좋을거 같습니다 👍 
다음 단계에서 뵐게요!

2024-04-16 09:45 UTC, merged