Step1 레거시 리팩토링 미션
next-step/java-lms pull request #5
Opened 2023-05-15 12:24 UTC by right1203

안녕하세요 리뷰어님
아래 기능 구현하였습니다.

- Service의 비즈니스로직을 Domain 객체로 리팩토링
- Answer, DeleteHistory의 일급 컬렉션 구현
- 이미 삭제된 경우 예외 추가
- Answer가 삭제되는 중 예외 발생 시 답변들의 삭제 상태를 되돌리는 로직 추가

이번 미션 잘 부탁드립니다 :)
감사합니다.

2023-05-17 11:11 UTC, nokchax requested changes
안녕하세요, 영훈님!
레거시 리팩토링 미션을 함께하게 된 김광현입니다 :) 
첫번째 스텝 잘 진행해 주셨어요, 꼼꼼하게 짜주셨네요
몇가지 코멘트 남겼는데 확인 부탁드립니다 🙇

2023-05-17 11:11 UTC, nokchax commented on src/main/java/nextstep/qna/domain/Answer.java
>      public Answer setDeleted(boolean deleted) {
setter를 외부에 공개하면 어떤 문제가 생길까요?

2023-05-17 11:11 UTC, nokchax commented on src/main/java/nextstep/qna/domain/Answer.java
> +    public Answer setContents(String contents) {
setter 보다 좋은 함수명은 없을까요?

2023-05-17 11:11 UTC, nokchax commented on src/main/java/nextstep/qna/domain/Answers.java
> +        }
현재 try catch로 삭제 불가 여부를 캐치하셔서 롤백하는 방식을 택하셨는데요,
예외를 그대로 throw하는 방식과 어떤 차이가 있고, 어느 방식이 더 좋을까요?

2023-05-17 11:11 UTC, nokchax commented on src/main/java/nextstep/qna/domain/Question.java
> +    private DeleteHistory deleteQustion(NsUser requestUser) throws CannotDeleteException {
```suggestion
    private DeleteHistory deleteQuestion(NsUser requestUser) throws CannotDeleteException {
```

2023-05-18 11:07 UTC, right1203 commented on src/main/java/nextstep/qna/domain/Answers.java
> +        }
생각해봤을 때는 해당 프로젝트는 Spring 프로젝트이니 Repository에서 데이터를 꺼내고, 가공 후 다시 넣는 것이 일반적인 패턴일 것 같습니다.
그러면 서비스 쪽에서 받아서 Repository에 업데이트가 되지 않도록 하면 될 것 같아서 굳이 객체 내에서 롤백하는 방식을 선택할 필요는 없는 것 같습니다.

말씀하신 의도가 맞는지 모르겠네요.
광현님 의도를 좀 더 말씀 주시면 좋을 것 같아요 ^^

2023-05-18 11:10 UTC, right1203 commented on src/main/java/nextstep/qna/domain/Answer.java
>      public Answer setDeleted(boolean deleted) {
protected로 변경했습니다

2023-05-18 11:19 UTC, nokchax commented on src/main/java/nextstep/qna/domain/Answers.java
> +        }
네, 말씀 주신것 처럼 예외 처리를 하지 않는다면, 굳이 내부에서 롤백을 위한 코드를 추가할 필요가 없죠,
결과적으로 코드가 더 간결해지구요 :)

2023-05-18 12:39 UTC, nokchax approved these changes
안녕하세요, 영훈님!
피드백 잘 적용해 주셨습니다.
이만 머지할게요, 다음 단계 진행해 주세요!

2023-05-18 12:39 UTC, nokchax commented on src/main/java/nextstep/qna/domain/Answers.java
> +    public boolean hasOthers(NsUser requestUser) {
👍

2023-05-18 12:39 UTC, nokchax commented on src/main/java/nextstep/qna/domain/Question.java
> +        deleteHistories.addAll(answers.deleteAll(requestUser));
👍

2023-05-18 12:39 UTC, merged