[수강신청 - 도메인 모델] step2 미션
next-step/java-lms pull request #503
Opened 2024-04-16 11:41 UTC by m5s3

이번에도 잘 부탁드립니다 리뷰어님 😄

2024-04-17 09:49 UTC, mskangg requested changes
2단계도 정말 잘 구현해주셨네요 👍 👏 
몇가지 피드백 남겨드렸어요.
확인부탁드릴게요! 🙇

2024-04-17 09:49 UTC, mskangg commented on src/main/java/nextstep/courses/CannotRegisterException.java
> +public class CannotRegisterException extends Exception {
checked exception 을 확장하신 이유가 있을까요? 🤔

2024-04-17 09:49 UTC, mskangg commented on src/main/java/nextstep/courses/domain/Session.java
> +            throw new CannotRegisterException(String.format("해당 강의 상태 %s에서는 수강 신청을 할 수 없습니다.", state.getState()));
checked exeption 을 확장하여 해당 메서드를 실행하는 모든 메서드에 시그니쳐가 붙었네요 🤔

2024-04-17 09:49 UTC, mskangg commented on src/main/java/nextstep/courses/domain/Image.java
> +    private static final List<String> allowedExtensions = List.of("gif", "jpg", "jpeg", "png", "svg");
열거형이니 enum 으로 관리하는게 좋아보입니다 😄

2024-04-17 09:49 UTC, mskangg commented on src/main/java/nextstep/courses/domain/Image.java
> +    private static final double RATIO = (double) Math.round(3.0 / 2.0 * 100) / 100;
위와 같은 값은 이미지 메타정보이니, 캡슐화가 가능해보여요 🤔

2024-04-17 09:49 UTC, mskangg commented on src/main/java/nextstep/courses/domain/Session.java
> +    private long fee;
> 규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.
인스턴스 변수의 수를 줄이기 위해 도전한다.

1단계 힌트에 나와있던 내용이에요.
이번에도 적용하는건 어떨까요? 🤔
최대한 클래스로 캡슐화해보는것 추천드립니다.

당장 보이는건 기간이 보이네요 😄

2024-04-17 09:49 UTC, mskangg commented on src/main/java/nextstep/courses/domain/Sessions.java
> +    }
객체의 값을 꺼내 처리하지 않고 메세지를 보내 잘 구현해주셨네요 👍

2024-04-17 09:49 UTC, mskangg commented on src/test/java/nextstep/courses/domain/CourseTest.java
> +    }
검증 로직이 없네요 🤔

2024-04-17 09:49 UTC, mskangg commented on src/test/java/nextstep/courses/domain/ImageTest.java
> +        Image test02 = new Image("test_02.png");
여기도 검증 로직이 없군요 🤔
생성자에서 아무일도 하지 않아도 테스트는 통과될것 같아요 😅

2024-04-17 14:58 UTC, m5s3 commented on src/main/java/nextstep/courses/CannotRegisterException.java
> +public class CannotRegisterException extends Exception {
제가 알고 있는 지식으로는 `unchecked` 는 논리적인 오류로 시스템에서 대응해야 하는 것으로 알고 있습니다. 따라서 롤백을 하던가, 복구를 하는등 즉시 조치를 취해야 한다고 생각합나다.
`checked` 는 비즈니스상 오류로 기획에 따라 달라 진다고 생각합니다.
가령 최대 인원일때 바로 시스템 상으로 거절 처리를 하거나등이 아닌, 이메일으로 부가적으로 처리하거나, 대기순을 주거나등 이라고 생각합니다.
따라서 `checked` 로 구현 했습니다.
혹시 제가 잘못된 부분이 있으면 알려주시면 감사하겠습니다. 😄

2024-04-26 00:27 UTC, javajigi requested changes
객체 지향 설계 원칙을 지키면서 미션 진행 잘 했네요. 💯 
바로 merge하려다 피드백 남겨봤어요.
빠르게 피드백 반영하고 다음 단계 진행하시죠.

2024-04-26 00:27 UTC, javajigi commented on src/main/java/nextstep/courses/domain/Image.java
> +        this.imageMeta = new ImageMeta(width, height, fileSize, ext);
```suggestion
       this(imageUrl, new ImageMeta(width, height, fileSize, ext);
```

인스턴스 변수와 같은 타입을 가지는 주 생성자를 추가하고 위와 같이 구현해 보는 것은 어떨까?

2024-04-26 00:27 UTC, javajigi commented on src/main/java/nextstep/courses/domain/ImageMeta.java
> +public class ImageMeta {
👍

2024-04-26 00:27 UTC, javajigi commented on src/main/java/nextstep/courses/domain/Money.java
> +    public boolean equal(Money amount) {
자바 표준에 맞춰 equals 메서드로 구현하는 것이 낫지 않을까?

2024-04-26 00:27 UTC, javajigi commented on src/main/java/nextstep/courses/domain/Session.java
> +    private Enrollment enrollment;
인스턴스 변수 사이에 빈 공백 라인이 있는 곳도 있고 아닌 곳도 있다.
의도한 것이라면 어떤 의도에서 위와 같이 구현할 것인가?

2024-04-26 00:27 UTC, javajigi commented on src/main/java/nextstep/courses/domain/Session.java
> +    public Session(long id, String title, SessionType sessionType, SessionState state, Image image,
주 생성자를 생성자의 마지막에 구현하는 것이 일반적인 관례임

2024-04-26 00:27 UTC, javajigi commented on src/main/java/nextstep/courses/domain/Students.java
> +    public final int size() {
```suggestion
    }
    
    public final int size() {
```

2024-04-26 00:27 UTC, javajigi commented on src/test/java/nextstep/courses/domain/EnrollmentTest.java
> +
정상적으로 수강 등록하는 case도 추가해야 하지 않을까?

2024-04-26 00:27 UTC, javajigi commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +        Session session = new Session(1L, "lms", SessionType.FREE, SessionState.RECRUITING, image, now.plusDays(5), now.plusDays(30));
Session 객체와 같이 인스턴스 변수가 많은 객체를 테스트하려면 객체를 생성하는데 어려움이 있다.
중복 코드 또한 많이 발생해 Session을 생성할 때 생성자의 인자가 변경되는 경우 변경할 부분이 많아진다.
https://www.arhohuttunen.com/test-data-builders/ 문서 참고해 Session과 같이 복잡한 객체의 테스트 데이터를 생성할 때 어떤 방법을 사용할 것인지 선택해 보면 좋겠다.
이번 기회에 내가 선호하는 방법을 적용해 보고 앞으로도 쭈욱 활용하는 방식이면 좋겠다.

2024-04-26 09:46 UTC, m5s3 commented on src/main/java/nextstep/courses/domain/Money.java
> +    public boolean equal(Money amount) {
[1058afe](https://github.com/next-step/java-lms/pull/503/commits/1058afef8c4678c16a57b7c6369535da55bf98b5) 에 적용했습니다!

2024-04-26 13:05 UTC, m5s3 commented on src/main/java/nextstep/courses/domain/Image.java
> +        this.imageMeta = new ImageMeta(width, height, fileSize, ext);
[d563e3d](https://github.com/next-step/java-lms/pull/503/commits/d563e3d8b9a87a8b94b5488b5d599473c83bd1f6) 이런게 반영했습니다!

2024-04-26 13:07 UTC, m5s3 commented on src/main/java/nextstep/courses/domain/Session.java
> +    private Enrollment enrollment;
빈 공백 라인인 클래스 분리하면서 실수로 지우지 못했습니다. 😓 
조금더 신경쓰도록 하겠습니다!

2024-04-26 13:12 UTC, m5s3 commented on src/main/java/nextstep/courses/domain/Session.java
> +    public Session(long id, String title, SessionType sessionType, SessionState state, Image image,
[fe89706](https://github.com/next-step/java-lms/pull/503/commits/fe89706bba5560651498d1d65437b5fc7223d3f6) 반영했습니다! 
자바를 계속 혼자 공부하고 있어서 관례에 대해서 잘 모르고 있었습니다.
너무 감사합니다!

2024-04-26 13:15 UTC, m5s3 commented on src/main/java/nextstep/courses/domain/Students.java
> +    public final int size() {
[a04a1c1](https://github.com/next-step/java-lms/pull/503/commits/a04a1c136b4263fbe194602efc831004aab32a71) 반영했습니다~
무의미한 제어자 삭제하도록 하겠습니다.

2024-04-26 13:17 UTC, m5s3 commented on src/test/java/nextstep/courses/domain/EnrollmentTest.java
> +
[44d3717](https://github.com/next-step/java-lms/pull/503/commits/44d3717861df54c614a7b4ba301ff46dc0209a64) 추가했습니다~

2024-04-26 13:21 UTC, m5s3 commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +        Session session = new Session(1L, "lms", SessionType.FREE, SessionState.RECRUITING, image, now.plusDays(5), now.plusDays(30));
질문이 있습니다.
`Session` 클래스 경우 일급 컬렉션이 `Sessions`가 존재하고 있습니다. 따라서 `Object Mother Pattern` 을 도입을 할려고 하면
`Sessions` 에 구현을 해야 할것 같습니다. 왜냐하면 일급 컬렉션 역할 중 하나가 해당 객체의 생성까지 책임이 있다고 생각이 들었습니다. 그런데 `Session` 테스트 케이스에 해당 `Sessions` 테스트를 `Session` 에는 할 수가 없으니 `Builder Pattern` 을 도입 했습니다.
`Enrollment` 에는 `Object Mother Pattern` 을 도입했습니다.

---

한 프로젝트에서 이렇게 서로 다른 두 패턴을 사용해도 괜찮을까요?

2024-04-26 22:04 UTC, javajigi commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +        Session session = new Session(1L, "lms", SessionType.FREE, SessionState.RECRUITING, image, now.plusDays(5), now.plusDays(30));
객체의 성격에 따라 다른 패턴을 사용하는 것이 더 나은 방법이라 생각해요.
무조건 한 가지 패턴을 고집하기보다 지금과 같이 상황에 따른 적절한 방법을 찾아 적용하는 것이 좋은 선택이라고 봅니다.

2024-04-26 22:08 UTC, javajigi approved these changes
피드백 반영 너무 잘 했네요. 💯 
Builder 패턴은 잘 적용했는데 사용하는 부분에 생각해 봤으면 하는 내용이 있어 피드백 남겼어요.
3단계 진행할 때 함께 반영해 보세요.

2024-04-26 22:08 UTC, javajigi commented on src/main/java/nextstep/courses/domain/Enrollment.java
> +public class Enrollment {
👍

2024-04-26 22:08 UTC, javajigi commented on src/main/java/nextstep/courses/domain/Image.java
> +    }
👍

2024-04-26 22:08 UTC, javajigi commented on src/test/java/nextstep/courses/domain/CourseTest.java
> +                .build();
```suggestion
        Session session1 = new Session.Builder(1L)
                .sessionType(SessionType.FREE)
                .build();
```
빌더 패턴을 적용해 테스트하는 것이 Session 생성을  편하게 하기 위함이다.
무료 강의 테스트라면 해당 값을 식별할 수 있도록 위와 같이 구현하면 어떨까?

2024-04-26 22:08 UTC, merged