2단계 - 수강신청(도메인 모델)
next-step/java-lms pull request #511
Opened 2024-04-17 12:33 UTC by Dongock

안녕하세요. 수강신청 2단계 pr 요청 드립니다.
이번 과제는 뭔가 제가 한 방향이 맞는지 고민이 되어서요. 혹시 틀리다면 얼마든지 편하게 말씀 부탁드리겠습니다.

일단 질문이 몇 가지 있습니다.

먼저 기존에 과제들에서 원시값 포장에 대해서 배웠었는데, 이 부분이 고민인게 모든 원시값들에 대해 전부 포장하는건 너무 많은 객체를 생성하게 되어 비효율적이라는 생각이 듭니다. 그런데 또,  SessionImage 부분에서 생성자 쪽에 이 원시값들에 대해 validate가 나열되어 있는데, 기존 구글이나 이런 내용에서 validate를 생성자에 전부 넣는 것이 아닌 원시값 포장을 한 뒤 각각 갖고 있게 한다는 내용을 본 거 같아서 정확히 원시값 포장에 대한 기준이 무엇일까에 대한 고민이 있습니다.
비즈니스적인 로직이 있는 원시값들에 대해서만 포장하는 것이 맞을까요?

또, 기본적으로 생성되어 있던 객체들에는 id값이 있는데 구체적인 이유가 알고 싶습니다. 객체 비교나 해쉬값과 관련이 있는 부분일까요?

또, 유료강의 관련해서 이미 결제가 되어 있다고 해서 그 부분에 대한 검증은 따로 넣지는 않았지만,
PaySession(유료강의) 부분을 구현하다보니 상위에 추상화 클래스로 Session을 만들었더니
수강신청이라는 메소드를 signUp(NsUser user) 이런식으로 메소드가 나왔습니다.
그런데 유료강의는 수강신청에서 금액 검증을 하려면 저 signUp 메소드에 매개변수로 금액 관련한 정보를 받아야 할 거 같아서,
오히려 Session이라는 클래스로 무료강의와 유료강의를 못 묶을 수도 있다는 생각이 들었습니다.
이 부분 어떻게 생각하실까요?

피드백 굉장히 자세해도 좋으니 얼마든지 주시면 감사하겠습니다!

2024-04-17 12:34 UTC, Dongock commented on src/main/java/nextstep/sessions/domain/SessionImage.java
> +        validateImageRate(imageWidth, imageHeight);
질문 1번 부분입니다.

2024-04-17 12:34 UTC, Dongock commented on src/main/java/nextstep/qna/domain/Answer.java
> +    private Long id;
질문 2번 부분입니다.

2024-04-17 12:34 UTC, Dongock commented on src/main/java/nextstep/sessions/domain/PaySession.java
> +    }
질문 3번입니다.

2024-04-19 11:38 UTC, csh0034 commented on src/main/java/nextstep/qna/domain/Answer.java
> +    private Long id;
이전 미션까지는 DB 에 연결하지 않고 분리하여 객체지향설계를 연습하였다면
수강신청 미션의 경우 실무에서 사용하는 환경과 유사하게 DB 연결까지 하므로 
DB 의 PK 의 해당하는 식별자가 추가된 부분입니다!

2024-04-19 12:10 UTC, csh0034 requested changes
2단계 구현 잘 해주셨네요 😄 
몇가지 코멘트 남겨두었는데 확인 부탁드립니다!

2024-04-19 12:10 UTC, csh0034 commented on src/main/java/nextstep/sessions/domain/SessionStatus.java
> +public enum SessionStatus {
enum 사용 👍

2024-04-19 12:10 UTC, csh0034 commented on src/main/java/nextstep/sessions/domain/ImageType.java
> +public enum ImageType {
imageType 을 두지 않고 `name().toLowerCase()` 를 사용하여 비교해볼수도 있겠네요!

2024-04-19 12:10 UTC, csh0034 commented on src/main/java/nextstep/sessions/domain/ImageType.java
> +                .orElseThrow(() -> {
orElseThrow 메서드 내부를 보면  `throw exceptionSupplier.get();` 과 같이 호출합니다.
따라서 예외 객체를 생성후 throw 하는것이 아닌 객체 생성만 해보시면 좋을것 같아요!

2024-04-19 12:10 UTC, csh0034 commented on src/main/java/nextstep/sessions/domain/SessionPeriod.java
> +    private final int startDate;
만약 99999999 와 같이 전달 되면 어떻게 될까요? 
LocalDateTime 와 같이 날짜를 표현하는 객체를 사용해보는것도 좋을것 같습니다!

2024-04-19 12:10 UTC, csh0034 commented on src/main/java/nextstep/sessions/domain/SessionImage.java
> +public class SessionImage {
원시값을 모두 포장해보는건 너무 극단적일까요? 🤔

2024-04-19 12:10 UTC, csh0034 commented on src/main/java/nextstep/sessions/domain/Session.java
> +public abstract class Session {
상속은 한번만 가능하므로 신중하게 사용해야합니다.
강의타입을 두고 처리해볼수 있지 않을까요? 🤔

추가로 `과정(Course)은 기수 단위로 운영하며, 여러 개의 강의(Session)를 가질 수 있다.` 의 요구사항이라면 Course 에 Session 목록이 필요하지 않을까요?

2024-04-19 12:10 UTC, csh0034 commented on src/main/java/nextstep/sessions/domain/PaySession.java
> +    public void signUp(NsUser nsUser) {
- 유료 강의는 수강생이 결제한 금액과 수강료가 일치할 때 수강 신청이 가능하다
- 유료 강의의 경우 결제는 이미 완료한 것으로 가정하고 이후 과정을 구현한다.
  - 결제를 완료한 결제 정보는 payments 모듈을 통해 관리되며, 결제 정보는 Payment 객체에 담겨 반환된다.

상단의 요구사항에 맞춰 Payment 객체를 활용하여 검증을 해보면 좋을것 같아요!

2024-04-19 12:10 UTC, csh0034 commented on src/test/java/nextstep/courses/domain/SessionPeriodTest.java
> +        assertThatThrownBy(
`assertThatIllegalArgumentException` 를 사용해볼수도 있을것 같네요 🙂

2024-04-19 12:10 UTC, csh0034 commented on src/main/java/nextstep/sessions/domain/Session.java
> +    private final Course course;
Course 를 객체 상태로 직접참조하는것과 id 를 사용하여 간접참조 하는것의 
차이에 대해서도 고민해보시면 좋을것 같습니다.

2024-04-19 12:10 UTC, csh0034 commented on src/main/java/nextstep/sessions/domain/SessionImage.java
> +        validateImageRate(imageWidth, imageHeight);
원시값 또는 문자열을 포장의 장점은 비지니스 로직 추가를
할 수 있으며 응집도가 높은 클래스를 검증된 형태로 사용가능한 점입니다.

저는 과정중엔 조금더 극단적으로 클래스 분리를 적용해보길 권장하는데요
이러한 연습과정을 하면서 분리해야 하는 기준이나 장점들에 대한 통찰을
얻을수 있기 때문입니다.

적용을 해보시면서 적절한 기준을 세워두시는것도 좋을것 같아요 😄

2024-04-19 12:10 UTC, csh0034 commented on src/main/java/nextstep/sessions/domain/PaySession.java
> +    }
무료강의와 같이 Payment 가 없을 경우는 별도 메서드를 
분리해서 처리해보거나 강의타입에 따라서 기능이 다르게 동작을 해야할때 실제
수행해야 하는 책임을 별도로 분리해보는 방법을 적용해볼수도 있을것 같아요.
고민해보시고 궁금한사항 있으시면 질문주세요!

2024-04-21 08:37 UTC, Dongock commented on src/main/java/nextstep/sessions/domain/SessionImage.java
> +        validateImageRate(imageWidth, imageHeight);
말씀하신 것처럼 과정은 연습이니 모두 클래스 분리를 진행해봤습니다.
실제 현장에서 기준을 세우는 연습을 계속해서 해봐야겠네요. 코드보다 이런 기준이나 설계가 훨씬 어렵다는 것을 느끼고 있습니다...

2024-04-21 08:38 UTC, Dongock commented on src/main/java/nextstep/qna/domain/Answer.java
> +    private Long id;
감사합니다. 이제 db 연결을 진행하면서 pk값을 의미하는 거였군요!

2024-04-21 08:39 UTC, Dongock commented on src/main/java/nextstep/sessions/domain/ImageType.java
> +public enum ImageType {
요부분 SessionName으로 변경을 진행했는데 결국 이름에서 확장자를 꺼내도 저 하드코딩된 확장자 이름으로 validate를 진행해야 할 것으로 보여서, ImageType은 그대로 두고 일종의 validate의 용도로 쓰고 있는데 이 방법이 혹시 비효율적인 걸까요?

2024-04-21 08:40 UTC, Dongock commented on src/main/java/nextstep/sessions/domain/ImageType.java
> +                .orElseThrow(() -> {
변경 완료했습니다! 감사합니다 ㅎㅎ 메서드 내부에서 이미 throw exceptionSupplier로 호출하고 있었군요

2024-04-21 09:13 UTC, Dongock commented on src/main/java/nextstep/sessions/domain/SessionPeriod.java
> +    private final int startDate;
말씀하신 거에서 고민하다가 LocalDate를 이용해서 한번 변경해봤습니다.

2024-04-21 09:13 UTC, Dongock commented on src/main/java/nextstep/sessions/domain/SessionImage.java
> +public class SessionImage {
클래스 분리를 최대한 해보면서 연습하라고 하셔서 모두 클래스 분리 진행했습니다!
아직도 기준을 만드는 건 쉽지 않네요

2024-04-21 09:20 UTC, Dongock commented on src/test/java/nextstep/courses/domain/SessionPeriodTest.java
> +        assertThatThrownBy(
IllegalArgumentException을 위한 테스트가 있는 줄은 몰랐습니다! 쓸일이 많아 보이네요 감사합니다 ㅎㅎ

2024-04-21 09:34 UTC, Dongock commented on src/main/java/nextstep/sessions/domain/Session.java
> +    private final Course course;
Course를 직접들고 있는게 아니라 CourseId를 들고 가는식으로 변경 완료했습니다.
혹시 직접 참조말고 간접참조로 추천해주신 이유를 간략하게라도 들을 수 있을까요??

2024-04-21 09:58 UTC, Dongock commented on src/main/java/nextstep/sessions/domain/Session.java
> +public abstract class Session {
Session 목록으로 Sessions라는 일급컬렉션을 만들었는데요. 여기에 대해 고민이 하나 있습니다. 이 Course라는 강의가 생길때 생성자에 Sessions가 포함되어야 하는지에 대한 여부인데요. 맨처음엔 Sessions를 생성자로 넣었다가 확인해보니 JdbcCourseRepository에서 문제가 생겨,  add 메소드를 통해 Session을 추가하는 식으로 진행했는데, 사실 이방식이 정확하게 맞다는 생각이 들진 않아서요. 이런 경우는 JdbcCourseRepository까지 리팩토링이 같이 진행되어야 하는건가요??

2024-04-30 12:34 UTC, Dongock commented on src/main/java/nextstep/sessions/domain/PaySession.java
> +    public void signUp(NsUser nsUser) {
Payment를 받고 검증하는 부분까지 추가했습니다!

2024-05-01 11:58 UTC, javajigi approved these changes
2단계 마무리하느라 수고했어요. 👍 
제가 추가로 피드백 몇 개 남겼는데요.
3단계 진행할 때 함께 반영해 보면 좋겠습니다.
현재 객체 크기가 상당히 작은데요. 3단계 db 매핑을 어떻게 할지 기대되네요.

2024-05-01 11:58 UTC, javajigi commented on src/main/java/nextstep/sessions/domain/Session.java
> +        this.createdAt = LocalDateTime.now();
주 생성자를 부생성자를 호출하도록 구현하는 것은 어떨까?

2024-05-01 11:58 UTC, javajigi commented on src/main/java/nextstep/sessions/domain/Session.java
> +    public void signUp(NsUser nsUser, Payment payment) {
Session과 같이 인스턴스 변수가 많은 객체에 수강 신청과 같은 복잡한 로직을 함께 구현할 경우 Session의 복잡도는 증가한다.
수강신청 가능 여부를 판단할 때 필요한 값을 가지는 Enrollment와 같은 객체를 추가한 후 Enrollment가 수강 신청 로직을 구현하는 것은 어떨까?

2024-05-01 11:58 UTC, javajigi commented on src/test/java/nextstep/sessions/domain/PaySessionTest.java
> +        session = Session.createPaySession(0L, 0L, sessionPeriod, sessionImage, SessionStatus.PREPARING, 0, 1000);
Session 객체와 같이 인스턴스 변수가 많은 객체를 테스트하려면 객체를 생성하는데 어려움이 있다.
중복 코드 또한 많이 발생해 Session을 생성할 때 생성자의 인자가 변경되는 경우 변경할 부분이 많아진다.
https://www.arhohuttunen.com/test-data-builders/ 문서 참고해 Session과 같이 복잡한 객체의 테스트 데이터를 생성할 때 어떤 방법을 사용할 것인지 선택해 보면 좋겠다.
이번 기회에 내가 선호하는 방법을 적용해 보고 앞으로도 쭈욱 활용하는 방식이면 좋겠다.

2024-05-01 11:58 UTC, merged