🚀 1단계 - 레거시 코드 리팩터링
next-step/java-lms pull request #517
Opened 2024-04-18 08:33 UTC by hhhhhwi

2024-04-19 01:52 UTC, mskangg requested changes
안녕하세요 휘연님!
이번 미션 리뷰를 맡은 강민수입니다 🙇

1단계 미션 잘 구현해주셨네요! 👍 
모각코를 하셨다니 정말 멋지군요 👏 

몇가지 코멘트 남겨드렸어요.
확인부탁드릴게요! 🙏

2024-04-19 01:52 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Question.java
> +    public class Detail {
inner class 는 static 으로 관리하는게 좋습니다.
관련 링크 남겨드릴게요! 

https://johngrib.github.io/wiki/java/inner-class-may-be-static/

2024-04-19 01:52 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Question.java
> +            }
다른 예외 조건인데 메세지는 동일하여 에러로그만 보고 판단하기 어렵겠네요 🤔

2024-04-19 01:52 UTC, mskangg commented on src/main/java/nextstep/qna/domain/answer/Answer.java
> +    public DeleteHistory convertDeleteHistory(LocalDateTime regDatetime) {
삭제이력을 생성하는거니, create 가 더 자연스러워보입니다 😄

2024-04-19 01:52 UTC, mskangg commented on src/main/java/nextstep/qna/service/QnAService.java
> +        DeleteHistories deleteHistories = question.getDeleteHistories(regDateTime);
```suggestion
        DeleteHistories deleteHistories = question.delete(loginUser);
```

위와 같이 삭제한 뒤 이력이 반환되는건 어떨까요?

```
요청자: 질문아 니가 가진 질문과 답변을 삭제해줘
질문: 그래, 삭제했어. 자, 니가 삭제 요청한 삭제 이력이야.
```

와 같이 이해할 수 있을것 같아요!

2024-05-02 16:00 UTC, hhhhhwi commented
안녕하세요!
제가 요 근래 갑작스럽게 업무가 많아져서.. 😢 
이제야 피드백 반영 진행해보았습니다 ㅠ 

잘 부탁드립니다!

2024-05-03 00:02 UTC, javajigi approved these changes
1단계 미션 구현 잘 했네요. 💯 
이 미션이 앞으로 레거시 코드를 리팩터링하는데 도움이 되었기를 바랍니다.
피드백 하나 남겼는데요. 한번 고민해 보면 좋겠어요.

2024-05-03 00:02 UTC, javajigi commented on src/main/java/nextstep/qna/domain/Question.java
> +    public DeleteHistories delete(NsUser user) throws CannotDeleteException {
```suggestion
    public void delete(NsUser user) throws CannotDeleteException {
```
바로 아래 DeleteHistories를 생성하는 별도의 메서드가 있다.
메서드가 한 가지 일만 한다는 원칙을 지켜 void로 반환하는 것은 어떨까?

2024-05-03 00:02 UTC, merged