🚀 3단계 - 수강신청(DB 적용)
next-step/java-lms pull request #537
Opened 2024-05-20 09:52 UTC by hhhhhwi

2024-05-21 00:41 UTC, javajigi requested changes
도메인 객체 설계한 후 DB 매핑하는 것이 쉽지 않죠?
그럼에도 불구하고 포기하지 않고 도전해 완료했네요. 💯 
약속한 시간은 끝났지만 피드백 한번 반영한 후 리뷰 요청 보내면 바로 merge하면서 리뷰 마감할께요.

2024-05-21 00:41 UTC, javajigi commented on src/main/java/nextstep/courses/domain/session/SessionFactory.java
> +	public Session createSession(SessionEntity sessionEntity) {
SessionFactory를 두지 않고 SessionEntity에서 Session을 생성하도록 구현하는 것은 어떨까?
Entity 객체가 도메인 객체에 의존 관계를 가져도 되지 않을까?

2024-05-21 00:41 UTC, javajigi commented on src/main/java/nextstep/courses/domain/session/SessionImage.java
>  	ImageFile imageFile;
```suggestion
	private final ImageFile imageFile;
```

2024-05-21 00:41 UTC, javajigi commented on src/main/java/nextstep/courses/domain/session/SessionImage.java
> +		this.imageFile = new ImageFile(id);
```suggestion
		this(new ImageFile(id));
```
부생성자가 주생성자를 호출해 구현할 것을 추천

2024-05-21 00:41 UTC, javajigi commented on src/main/java/nextstep/courses/domain/session/SessionImage.java
> +	public SessionImage(ImageFile imageFile) {
주생성자는 생성자의 마지막에 구현하는 것이 관례

2024-05-21 00:41 UTC, javajigi commented on src/main/java/nextstep/courses/domain/session/SessionImage.java
> +		this.imageFile = new ImageFile(id, size, width, height, type);
```suggestion
		this(new ImageFile(id, size, width, height, type));
```
부생성자가 주생성자를 호출해 구현할 것을 추천
이렇게 구현할 경우 유효성 체크와 같은 중복 코드를 제거하는 효과가 생긴다.

2024-05-21 00:41 UTC, javajigi commented on src/main/java/nextstep/courses/entity/SessionEntity.java
> +public class SessionEntity {
도메인 객체와 DB 매핑을 담당하는 Entity를 분리하려는 시도 👍

2024-05-21 00:41 UTC, javajigi commented on src/main/java/nextstep/courses/domain/student/Student.java
> +public class Student {
이 객체가 추가되면서 Session 도메인에 수강생 목록을 가지는 구조가 되어야 하지 않을까?

2024-05-21 13:03 UTC, hhhhhwi commented on src/main/java/nextstep/courses/domain/student/Student.java
> +public class Student {
Student에 sessionId로 간접매핑만 시키고 Session에는 매핑을 안 시켰었네요..! 추가해두었습니다! 👍

2024-05-21 13:05 UTC, hhhhhwi commented on src/main/java/nextstep/courses/domain/session/SessionFactory.java
> +	public Session createSession(SessionEntity sessionEntity) {
Entity와 도메인의 의존 관계를 아예 두고 싶지 않아서 Factory로 구현했었는데요..!
고민해보니 중간 객체를 두는 것 또한 의존관계로 보일 수도 있고, 굳이 관리 포인트만 늘어나는 것 같네요..!

2024-05-21 13:11 UTC, hhhhhwi commented
포비님!
늦은 PR에도 정성스레 리뷰해주셔서 정말 감사합니다...! 🙇 

비록 미션을 너무 늦게 수행했지만, 
이번 강의 덕분에 이전보다는 쉽게 객체지향적 사고를 할 수 있게 된 것 같습니다..! (ㅎㅎ 아직 능숙하지는 않지만요..! 😂 )

그리고 특히나 이번 수강신청 단계는 미션을 진행하면서,
제가 운영하고 있는 레거시 서비스를 리팩토링 할 수 있지 않을까? 라는 약간의 용기💪 를 얻을 수 있었습니다..!

다시 한 번 탄탄히 공부해보고, 팀원들에게 공유할 수 있는 자리를 가져보는 등
더 좋은 결과까지 이루어낼 수 있도록 노력해보겠습니다!

이번 강의도 정말 수고 많으셨습니다!

2024-05-22 00:00 UTC, javajigi approved these changes
빠르게 피드백 반영했네요. 💯 
지금까지 힘든 과정 지속하느라 넘 수고했어요.
이 교육 과정이 앞으로 개발자로 살아가는데 조금은 도움이 되기를 바랍니다.

2024-05-22 00:00 UTC, merged