Step1: 1단계 - 레거시 코드 리팩터링
next-step/java-lms pull request #542
Opened 2024-10-20 04:29 UTC by wlghsp

안녕하세요 

리뷰어님 1단계 - 레거시 코드 리팩터링 pr 올립니다.

일급 컬렉션 추가 등 리팩토링은 진행하였는데, 인스턴스 변수의 수를 3개 미만으로 줄이지 못한 점이 아쉽습니다. 

리뷰 부탁드립니다.

2024-10-20 05:33 UTC, testrace requested changes
안녕하세요 지호님 😃 
수강신청 미션을 함께 하게 된 송용주입니다.
리팩토링 깔끔하게 잘 해주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청해 주세요.

2024-10-20 05:33 UTC, testrace commented on src/main/java/nextstep/qna/README.md
> +- [ ] repository 패키지로 repository 이동
해결이 된 항목은 체크해 주시면 좋을 것 같아요.

2024-10-20 05:33 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answer.java
> +        this.deleted = true;
setter를 활용하지 않고 메시지를 보내도록 메서드를 제공하면 어떨까요?

2024-10-20 05:33 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answers.java
> +    }
일급 컬렉션 활용 👍 
정적 팩토리 메서드와 생성자는 차이가 없으니 정적 팩토리 메서드는 제거해도 괜찮지 않을까요?

2024-10-20 05:33 UTC, testrace commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(question.generateDeleteHistories());
깔끔하게 리팩토링 하셨네요 👍 
다만 check~ 메서드를 모두 호출을 해야한다는 사실을 모른다면 일부 조건만 충족하더라도 삭제가 가능한 상황이 됩니다.
도메인 객체가 스스로 판단해서 삭제 결과를 리턴하면 어떨까요?
```suggestion
        Question question = findQuestion(questionId);
        List<DeleteHistory> histories = question.delete(loginUser);
        deleteHistoryService.saveAll(histories);
```

2024-10-20 05:33 UTC, testrace commented on src/main/java/nextstep/qna/domain/common/BaseTime.java
> +public abstract class BaseTime {
1단계는 인스턴스 변수의 수는 이후 단계에서 적용해 보시면 좋을 것 같아요.

2024-10-20 06:22 UTC, wlghsp commented on src/main/java/nextstep/qna/domain/common/BaseTime.java
> +public abstract class BaseTime {
네 알겠습니다 
감사합니다.

2024-10-20 06:24 UTC, wlghsp commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(question.generateDeleteHistories());
제안해주신 코드가 훨씬 깔끔하네요.
반영하겠습니다.

2024-10-20 06:26 UTC, wlghsp commented on src/main/java/nextstep/qna/domain/Answers.java
> +    }
네 필요한 경우에 정적 팩토리 메서드 사용해야하는데 제가 남발했던 거 같습니다. 
반영하겠습니다.

2024-10-20 06:26 UTC, wlghsp commented on src/main/java/nextstep/qna/README.md
> +- [ ] repository 패키지로 repository 이동
네 알겠습니다. :)

2024-10-20 07:25 UTC, wlghsp commented on src/main/java/nextstep/qna/domain/Answer.java
> +        this.deleted = true;
네 알겠습니다.

2024-10-21 05:23 UTC, testrace requested changes
안녕하세요 지호님 😃 
피드백 반영 잘해주셨네요 👍 
조금만 더 개선하면 좋을 것 같아 코멘트 남겨두었습니다.
확인해 주시고 다시 리뷰 요청해 주세요.

2024-10-21 05:23 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answer.java
> +    }
외부에서 이 메서드를 호출한다면 동일 작성자 여부를 검증하지 않고 삭제가 가능하게 됩니다.
1개의 답변만 삭제하더라도 checkIfAnotherOwnerExists 메서드를 항상 수행하도록 변경하면 어떨까요?

2024-10-21 05:23 UTC, testrace commented on src/main/java/nextstep/qna/domain/Question.java
> +    public void deleteQuestion() {
public 으로 열려 있다보니 여전히 검증없이 삭제가 가능합니다.
private으로 변경하거나 메서드를 제거해서 항상 작성자와 일치여부를 검증하도록 하면 어떨까요?
Answer#deleteAnswer 마찬가지입니다.

2024-10-21 05:23 UTC, testrace commented on src/main/java/nextstep/qna/domain/Question.java
> +        return generateDeleteHistories();
이전의 피드백과 마찬가지로 check~ 메서드를 일일이 호출해줘야한다는걸 모른다면 작성자와 관계 없이 삭제가 가능합니다.
checkIfAnswerOwner 메서드를 직접 호출하지 않고 메시지를 보내서 결과를 받으면 어떨까요?
`List<DeleteHistory> answerDeleteHistories = answers.delete(loginUser);`

2024-10-21 05:23 UTC, testrace commented on src/test/java/nextstep/qna/domain/QuestionTest.java
> +                        () -> Q1.delete(NsUserTest.SANJIGI)
AnswerTest에도 동일하게 delete 메서드로 예외를 검증하면 좋을 것 같아요

2024-10-21 12:00 UTC, wlghsp commented on src/main/java/nextstep/qna/domain/Answer.java
> +    }
네 알겠습니다. :)

2024-10-21 12:00 UTC, wlghsp commented on src/main/java/nextstep/qna/domain/Question.java
> +    public void deleteQuestion() {
네 감사합니다.

2024-10-21 12:01 UTC, wlghsp commented on src/test/java/nextstep/qna/domain/QuestionTest.java
> +                        () -> Q1.delete(NsUserTest.SANJIGI)
네 감사합니다.

2024-10-21 12:01 UTC, wlghsp commented on src/main/java/nextstep/qna/domain/Question.java
> +        return generateDeleteHistories();
네 '메시지를 보낸다' 명심하겠습니다.
감사합니다.

2024-10-21 12:29 UTC, testrace approved these changes
피드백 반영 잘해주셨네요 👍 
다음 단계 진행해 주세요.

2024-10-21 12:29 UTC, testrace commented on src/main/java/nextstep/qna/domain/Answer.java
> +        this.deleted = true;
답변만 삭제하더라도 요구사항에 따라 예외를 던질 수 있게 되었네요 👍

2024-10-21 12:29 UTC, merged