Step1 - 레거시 코드 리팩터링
next-step/java-lms pull request #545
Opened 2024-10-20 12:54 UTC by jeonghyeonkwon

안녕하세요 리뷰어님!

이번 lms 과제 제출 드립니다.

잘 부탁 드립니다!

2024-10-21 08:23 UTC, mskangg requested changes
안녕하세요 정현님!
이번 미션 리뷰를 맡은 강민수입니다 🙇 

1단계 구현 잘해주셨네요!
service 를 좀더 줄일 수 있을것 같아 피드백 남겨드렸습니다.
확인후 재요청 부탁드릴게요 🙏

2024-10-21 08:23 UTC, mskangg commented on src/main/java/nextstep/qna/service/QnAService.java
> +        Answers answers = question.validate(loginUser);
validate 는 보통 유효성을 검증하는 메서드로 활용됩니다.
리턴값이 존재하는게 어색해보이네요 🤔

2024-10-21 08:23 UTC, mskangg commented on src/main/java/nextstep/qna/service/QnAService.java
> +        List<DeleteHistory> deleteHistories = question.delete();
답변을 위에서 검증하는것도 결국 삭제시 검증이 필요한 부분 아닐까요? 🤔

질문을 삭제할 때 질문에 달려 있는 모든 댓글을 전부 삭제하면서 검증하는건 어떨까요?

2024-10-21 08:23 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Question.java
> +        result.add(new DeleteHistory(ContentType.QUESTION, id, writer, LocalDateTime.now()));
정적 생성자를 통해 질문과 답변삭제이력을 만드는건 어떨까요?

`DeleteHistory.questionOf()`
`DeleteHistory.answerOf()`

ContentType 을 매번 넣지 않아도 될것 같아요 :)

2024-10-21 08:23 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Answers.java
> +    }
👍

2024-10-21 08:23 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Question.java
> +    public List<DeleteHistory> delete() {
`질문을 삭제할 때 답변 또한 삭제해야 하며, 답변의 삭제 또한 삭제 상태(deleted)를 변경한다.`

의 요구사항을 잘 만족하게 구현해주셨네요 👍

2024-10-21 10:36 UTC, jeonghyeonkwon commented
피드백 해주신 내용 감사합니다!

내용들 수정 해서 다시 요청드립니다

2024-10-22 01:48 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요! 👍 
소소한 피드백 남겨드렸는데, 확인해주세요~!
그럼 다음 단계도 화이팅 🔥

2024-10-22 01:48 UTC, mskangg commented on src/main/java/nextstep/qna/domain/DeleteHistory.java
> +    }
👍

2024-10-22 01:48 UTC, mskangg commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(question.delete(loginUser));
👍

2024-10-22 01:48 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Answer.java
> +    }
```suggestion
    public DeleteHistory delete(NsUser nsUser) {
        validate(nsUser);
        this.deleted = true;
        return DeleteHistory.answerOf(id, writer);
    }
```

삭제할 때 검증하는 방식은 어떨까요?

2024-10-22 01:48 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Question.java
> +        answers.validate(nsUser);
답변들을 삭제하는 메서드 안에서 validate 를 처리한다면 이 코드는 제거가되도 될것 같군요 🤔

2024-10-22 01:48 UTC, merged

2024-10-22 06:59 UTC, jeonghyeonkwon commented on src/main/java/nextstep/qna/domain/Answer.java
> +    }
만약 
질문(작성자 : 유저1) 의 답변1(작성자: 유저1), 답변2(작성자 : 유저2)가 있다라고 
가정 했을때 답변1은 삭제 시 검증 로직이 통과 되어 deleted = true로 바뀝니다

그리고 답변2의 삭제 메소드 내부에 검증을 하면 예외 발생으로 답변1 deleted의 상태를 다시 변경 해야 되는 거 아닌가요???

2024-10-30 07:07 UTC, mskangg commented on src/main/java/nextstep/qna/domain/Answer.java
> +    }
트랜잭션을 하나로 묶었다면 롤백되어 문제가 없을것 같아요