1단계 - 레거시 코드 리팩터링
next-step/java-lms pull request #561
Opened 2024-10-24 06:42 UTC by sinyebin

안녕하세요 1단계 리뷰 부탁드립니다!

레거시 코드 리팩토링을 처음 진행해보아서 이렇게 하는게 맞는지 의문이 드네요,, 
이렇게 진행하는게 맞는걸까요?

2024-10-24 16:16 UTC, dhmin5693 requested changes
안녕하세요~

코드를 작성하면서 고민을 되게 많이 하신 모양이에요 😄 
조금만 더 수정했으면 좋겠다 싶은 부분에 리뷰를 남겨두었으니 확인 부탁드립니다.

어려운 부분 있으시면 언제든지 DM주세요.

2024-10-24 16:16 UTC, dhmin5693 commented on src/main/java/nextstep/qna/domain/Answer.java
> +        return new DeleteHistory(this, LocalDateTime.now());
LocalDateTime.now() 는 항상 현재 시간을 반환합니다.
매 호출마다 다른 결과를 내줄 때 멱등성이 지켜지지 않는다고 하는데요,
이로 인해 문제가 발생할 수 있습니다. [참고](https://jojoldu.tistory.com/451)

그리고 `Answer` 는 1개만 삭제되는게 아니라 모든 `Answer`가 동시에 삭제될 수 있는데, 논리적으로 같은 시간에 삭제했지만 실제로 기록되는 시간은 약간 다를 수 있기도 하겠네요.

매개변수로 넘겨주거나 가장 윗단(controller 등)에서만 1회 호출한다던가, 인터페이스를 통한 약결합으로 넘겨주는 등의 방법으로 해결할 수 있어요.

2024-10-24 16:16 UTC, dhmin5693 commented on src/main/java/nextstep/qna/domain/Answers.java
> +    }
이 생성자를 호출한 곳에서 매개변수 값을 수정하면 값이 변경될 수 있어요.
[방어적 복사](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable)에 대해서 알아보시면 좋아요.

2024-10-24 16:16 UTC, dhmin5693 commented on src/main/java/nextstep/qna/domain/DeleteHistory.java
> +    }
생성의 방향도 고민해보셔요.
현재 `Answer`와 `DeleteHistory` 가 서로를 참조하는 구조라서 서로의 변경에 취약하기도 합니다.

그리고 `Answer`는 삭제하며 `DeleteHistory`를 남기는 등 다소 합리적으로 참조하는데 반해 `DeleteHistory`에서 `Answer`를 참조해봤자 생성 외에는 사용되지 않습니다.

2024-10-24 16:16 UTC, dhmin5693 commented on src/main/java/nextstep/qna/domain/Answers.java
> +    }
매개변수를 변경하는 방향으로 코드가 작성되어 있네요.
이렇게 되면 일급 함수의 조건을 위반하게 됩니다.
output은 없지만 input이 변경되는 구조에요.

매개변수를 변경하기보다는 이 메소드의 결과로 `DeleteHistories`를 반환한다면 다른 요소에 영향을 주지 않는, 사이드 이펙트가 없는 코드를 작성할 수 있습니다.

2024-10-24 16:16 UTC, dhmin5693 commented on src/main/java/nextstep/qna/domain/Question.java
> +        answers.deleteQuestionAllAnswers(deleteHistories);
여기도 LocalDateTime.now 개선해주시고 다른 리뷰를 참조하여 참조의 방향을 바꿔주세요.
(`Answer`가 `DeleteHistory` 참조)

2024-10-25 00:53 UTC, sinyebin commented on src/main/java/nextstep/qna/domain/DeleteHistory.java
> +    }
answer를 참조하지 않고 id, writer를 보내어 생성을 할 수 있도록 수정하였는데
` 
public DeleteHistory deleteAnswer(LocalDateTime deleteTime) {
        this.deleted = true;
        return deleteFromAnswer(this.id, this.writer, deleteTime);
    }   
 public static DeleteHistory deleteFromQuestion(Long id, NsUser deletedBy, LocalDateTime createdDate) {
        return new DeleteHistory(ContentType.QUESTION, id, deletedBy, createdDate);
    }
`
아니면 
`
public DeleteHistory deleteAnswer(){
        this.deleted=true;
        return new DeleteHistory(ContentType.ANSWER, id, writer, LocalDateTime.now());
    }
`
 이런식으로  기존에 있는 생성자로 사용하는게 좋을까요?

2024-10-25 15:12 UTC, dhmin5693 commented on src/main/java/nextstep/qna/domain/DeleteHistory.java
> +    }
넵, 필요한 곳에서 생성을 하시는게 더 바람직합니다 😄 

`DeleteHistory` 의 이름으로 유추해보면 너무나 많은 곳에 쓰일 수 있어요.
이번 미션에는 없는 요소라 할지라도 리뷰, 별점 등등 `DeleteHistory`를 남길만한 곳은 다양합니다.

그러다보니 `DeleteHistory`에서 각각의 도메인 객체들을 의존하여 생성하기에는 너무 많은 의존이 생겨버릴 수 있기도 합니다.

2024-10-25 15:15 UTC, dhmin5693 approved these changes
잘 반영해주셨네요 👍 👍 
수고하셨습니다.
다음 미션 진행해주세요~

2024-10-25 15:15 UTC, dhmin5693 commented on src/main/java/nextstep/qna/domain/DeleteHistory.java
> +    }
`DeleteHistory` 에 굳이 팩토리 메소드를 놓을 필요는 없을 것 같아요.

2024-10-25 15:15 UTC, dhmin5693 commented on src/main/java/nextstep/qna/domain/Answers.java
> +    public DeleteHistories deleteQuestionAllAnswers(LocalDateTime deleteTime) {
👍

2024-10-25 15:15 UTC, dhmin5693 commented on src/main/java/nextstep/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(deleteHistories.getDeleteHistories());
👍

2024-10-25 15:15 UTC, merged