2단계 - 수강신청(도메인 모델)
next-step/java-lms pull request #573
Opened 2024-10-26 15:09 UTC by Park1122

안녕하세요 멘토님 리뷰 부탁드립니다! :)

2024-10-26 22:41 UTC, neojjc2 commented
#tag @neojjc2

2024-10-27 02:51 UTC, neojjc2 commented on src/main/java/nextstep/courses/domain/course/Course.java
> +package nextstep.courses.domain.course;
패키지 구조가 좀 이상한 것 같습니다 😅 
`course`관련 패키지 하위에 다시 `course`가 들어가는건 좀 어색하네요.
`sessions`도 하나의 모듈 관점에서 분리되는게 더 좋을 것 같습니다 😄 

```
main/java/nextstep
│── courses
│   │── domain
│   │── service
│   └── infrastructure
│── sessions
│   │── domain
│   │── service
│   └── infrastructure
└── payments
    │── domain
    │── service
    └── infrastructure
```

추가적으로 요구사항도 하나 더 확인 부탁 드리겠습니다. 
`Course`와 `Sesssion`간에 연관이 없는 것 같습니다  🙏
> **수강 신청 기능 요구사항**
과정(Course)은 기수 단위로 운영하며, 여러 개의 강의(Session)를 가질 수 있다.

2024-10-27 02:51 UTC, neojjc2 commented on src/main/java/nextstep/courses/domain/session/EnrolledUsers.java
> +public class EnrolledUsers {
`Session`을 수강하는 유저를 관리하는 일급컬렉션 사용 좋습니다 👍 

소소한 의견이긴 합니다만 사용자를 바로 매핑하기 보다 `수강신청정보` 같은 객체를 통해 
`Session`과 `NsUser`의 매핑정보를 관리 하도록 하면 어떨까 싶습니다. 

왜냐하면 수강신청 시간이라던지 부수적으로 관리해야할 정보들이 충분히 발생할 수 있는데 
`Session - User`간 매핑이 된다면 위와 같은 요구사항이 추가되었을 때, 대응이 어렵습니다 🤔 

이 부분은 조금만 더 고민해주시면 감사하겠습니다 🙏

2024-10-27 02:51 UTC, neojjc2 commented on src/main/java/nextstep/courses/domain/session/EnrolledUsers.java
> +    public boolean isAlreadyEnrolled(NsUser user) {
소소한 의견입니다만 기존 수강여부를 확인하는 로직 제공도 좋은데, 아예 `List`가 아닌 `Set<NsUser>`라면 
좀 더 예외처리를 누락하더라도 버그 발생을 줄일 수 있는 코드가 될 수 있을 것 같습니다 🙇

2024-10-27 02:51 UTC, neojjc2 commented on src/main/java/nextstep/courses/domain/session/EnrolledUsers.java
> +        return Collections.unmodifiableList(users);
불변객체 반환 좋습니다 💯

2024-10-27 02:51 UTC, neojjc2 commented on src/main/java/nextstep/courses/domain/session/SessionType.java
> +    }
`freeType`, `paidType` 아이디어 좋네요 👍

2024-10-27 02:51 UTC, neojjc2 commented on src/main/java/nextstep/courses/domain/session/SessionType.java
> +    private final int tuition;
`tuition`까지는 괜찮은데 `maximumEnrollment`는 원시객체로 포장되면 좋을 것 같은데 어떻게 보시나요?? 🤔 

> **이전단계 프로그래밍 요구사항**
> 규칙 3: 모든 원시값과 문자열을 포장한다.

2024-10-27 02:51 UTC, neojjc2 commented on src/main/java/nextstep/payments/domain/Payment.java
> +    }
`Payment`쪽에 결제상태를 알 수 있는 상태 값이 `Enum`형태로 추가 되는건 어떨까요?? 🤔 
단순히 결제 금액이 같다고 해서 결제가 완료상태로 보긴 좀 어려울 것 같습니다. 
금액은 같지만 실제 결제는 대기상태일 수도 있고, 결제취소도 사실 결제금액은 동일한 상태입니다. 
향 후 확장성을 위해서라도 별도 `status`로 관리 되는게 좋을 것 같습니다 😄

2024-10-27 02:51 UTC, neojjc2 commented on src/main/java/nextstep/courses/domain/session/Session.java
> +        }
검증 좋습니다 👍 검증에 대한 역할도 각 객체들을 통해 잘 위임해주신 것 같습니다.

2024-10-27 02:51 UTC, neojjc2 commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +}
테스트 정말 꼼꼼하고 좋습니다 👍 
소소한 의견입니다만 스켈레톤 코드라도 `SessionService` 같은 서비스를 만들어서 어떻게 사용될지에 대해서도
같이 고민해주시면 더 좋은 구조가 나올 것 같습니다 🙇

2024-10-27 02:55 UTC, neojjc2 requested changes
안녕하세요 정욱님 🙇 

2단계 잘 진행해주셨습니다 😄 
곳곳에 고민의 흔적들과 좋은 아이디어들이 돋 보이는 코드였습니다 💯 

조금만 보완되면 좋을 것 같아서,
소소한 의견들 몇 가지 드렸는데요,
한번 보시고 괜찮다 싶으신 부분들에 대해서는
수정 검토 해주시면 감사하겠습니다.

그럼 재 리뷰 요청 기다리고 있겠습니다 🙏

2024-10-27 04:25 UTC, Park1122 commented on src/main/java/nextstep/payments/domain/Payment.java
> +    }
2단계 요구사항에서 결제가 완료된 상태에 대한 정보를 다루는 객체가 Payment라는 점에서 굳이 상태를 넣지 않아도 될거 같습니다.
만약 별개의 결제 진행 과정 관련 객체가 추후 필요시 별도로 생성되는게 옳다고 생각합니다.

2024-10-27 06:24 UTC, neojjc2 commented on src/main/java/nextstep/payments/domain/Payment.java
> +    }
@Park1122 네 정욱님 그 관점에서 생각해보니 어느정도 이해는 됩니다.
> 결제를 완료한 결제 정보는 payments 모듈을 통해 관리되며, 결제 정보는 Payment 객체에 담겨 반한된다.

이미 결제가 완료 된 상태에서 생성되는 객체이니, 그 관점이라면 존재여부만 체크해도 될 것 같다는 생각이 듭니다.
근데 존재여부만 가지고 `complete`상태로 보자니 추가 확인이 더 되면 좋을 것 같아서 
강의금액과 결제금액을 비교하신게 아닌가 생각이 드네요 😄 

제가 혼동이 좀 됐던 부분은 분명 상태를 물어보는 코드인데 (`isComplete`) 인자를 전달하는 부분이 있고
실제 `method` 내부에서도 결제금액과 강의금액이 동일한지 여부를 체크하고 있어서,
결제금액과 강의금액이 같으면 결제가 완료상태인가?? 하는 의문이 들었습니다. 

유지보수 관점에서 봤을 때,  결제완료 금액과 강의 금액의 불일치는 충분히 발생할 수 있는 상황이기에 (결제 완료후 강의정보가 수정되었거나, 할인쿠폰 적용등등) 결제완료 정보에서 금액을 확인하는 `isPaidAmount(int tuition)` 가 더 적당하지 않나?? 그리고 별도 상태를 가져가야 하지 않을까?? 하는 생각에서 시작된 의견이었는데, 정욱님 의견을 듣고보니 좀 멀리 간 것도 없지않아 있네요 😄 

근데 그런 관점에서 보신거라면 지금 상태도 나쁘지 않을 것 같습니다. 
그리고 `Payment`는 본 미션에서 핵심도메인은 아니니 이정도 선에서 마무리 지으시죠 🙏

2024-10-27 06:25 UTC, neojjc2 approved these changes
안녕하세요 정욱님 🙇 

요청사항 빠르게 반영해주셨는데요?? 😮 

수고 많으셨습니다.
3단계로 가시죠 🔥

2024-10-27 06:27 UTC, merged