2단계 - 수강신청(도메인 모델)
next-step/java-lms pull request #589
Opened 2024-10-29 08:53 UTC by sinyebin

안녕하세요 2단계 미션 리뷰 부탁드립니다!
미션을 진행하면서 무료 강의, 유료 강의를 나누면서 추상화로 진행을 하였는데
register를 할 때 결제 여부를 확인하는 것에 있어서 고민을 많이 하였고,
Optional을 사용하였는데 이렇게 해도 되는지가 궁금합니다.

2024-10-29 12:43 UTC, dhmin5693 requested changes
안녕하세요~

질문하신 부분에 답변을 남겨두었어요.
다른 부분도 참고하셔서 수정에 반영해주시면 감사하겠습니다.

궁금한 점 있으시면 언제든지 DM 보내주세요 😄

2024-10-29 12:43 UTC, dhmin5693 commented on src/main/java/nextstep/courses/domain/ImgType.java
> +        ALLOWED_EXTENSIONS = Collections.unmodifiableSet(extensions);
캐싱 너무 좋네요! 👍 

별도의 static 영역 없이도 stream을 활용하여 ALLOWED_EXTENSIONS = this.values()... 으로 가능합니다.

2024-10-29 12:43 UTC, dhmin5693 commented on src/main/java/nextstep/courses/domain/PaidSession.java
> +    public PaidSession(Long id, String title, LocalDateTime startDay, LocalDateTime endDay, SessionStatus sessionStatus, Students students, Long fee) {
startDay, endDay 라는 이름을 사용하시려면 `LocalDateTime` 보다는 `LocalDate` 를 사용하시는게 더 적절하지 않을까요?

2024-10-29 12:43 UTC, dhmin5693 commented on src/main/java/nextstep/courses/domain/Session.java
> +    }
null 은 가급적 반환하지 마세요.
자바에서는 항상 NPE가 가장 큰 골칫거리거든요.

이 메소드는 abstract로 두고 free에서 0을 반환하는건 어떤가요?

2024-10-29 12:43 UTC, dhmin5693 commented on src/main/java/nextstep/courses/domain/Session.java
> +    }
register는 유료/무료 여부에 따라 로직이 갈리고 있어요.
여기도 추상화를 해주세요.

공통 로직은 이 클래스에 두고 분기가 생기는 부분만 abstract로 추상화하시면 될거 같아요.

2024-10-29 12:43 UTC, dhmin5693 commented on src/main/java/nextstep/courses/domain/SessionImg.java
> +        if ((double) imgWidth / imgHeight != REQUIRED_ASPECT_RATIO) {
컴퓨터가 소수점을 표현하는 방법은 부동소수점인데요, 정확한 숫자를 표기하기 어렵다는 문제가 있어요.

width : height = 3 : 2라면 수학적으로 3 * width = 2 height 도 성립합니다.
이렇게 바꿔보시는건 어떤가요?

2024-10-29 12:43 UTC, dhmin5693 commented on src/main/java/nextstep/courses/domain/SessionImg.java
> +        throw new IllegalArgumentException(INVALID_IMG_TYPE);
예외 발생의 책임은 `ImgType` 가 가져가도 어색하지는 않겠네요.

그리고 줄임말은 가급적 배제 부탁드리겠습니다. (img -> Image)

2024-10-29 12:43 UTC, dhmin5693 commented on src/main/java/nextstep/courses/domain/Session.java
> +    public void register(NsUser student, Optional<Payment> payment) {
이 미션에서 payment 로직이 제대로 주어지지 않다보니 상상력에 기대어야 하는 문제가 있긴 한데요,
`Optional` 을 사용하신건 결제가 있을 수도 있고 없을 수도 있기 때문일까요?

정의하기 나름이지만 0원으로 결제하는 과정도 `Payment`로 충분히 가정할 수 있어보이고 그렇게 되면 `Optional`은 없어도 될 것 같아요.

2024-10-30 01:06 UTC, sinyebin commented on src/main/java/nextstep/courses/domain/Session.java
> +    public void register(NsUser student, Optional<Payment> payment) {
결제가 아예 없을 수 있다고 생각하여 optional로 하였는데 0원으로 결제하는 방법을 생각을 못했습니다

2024-10-30 16:34 UTC, dhmin5693 approved these changes
피드백 잘 반영해주셨군요.
다음 단계 진행해주세요.
수고하셨습니다 🙇

2024-10-30 16:34 UTC, dhmin5693 commented on src/main/java/nextstep/courses/domain/FreeSession.java
> +    public FreeSession(String title, LocalDate startDay, LocalDate endDay, SessionStatus sessionStatus, Students students) {
변수명이 day여서 그런 의견을 드린 것이었는데, 시간은 확실히 필요없는게 맞을까요?

2024-10-30 16:35 UTC, merged