Step2: 수강신청(도메인 모델) 미션 제출합니다.
next-step/java-lms pull request #596
Opened 2024-10-30 03:16 UTC by hwan2-99

리뷰 잘부탁드립니다!. 설계부터 하다보니 시간이 오래걸렸네요..

2024-10-30 14:54 UTC, testrace requested changes
안녕하세요 태환님 😃 
2단계 잘 구현해 주셨네요 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청해 주세요.

2024-10-30 14:54 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session.java
> +public class Session {
>규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

위 규칙을 지키기 위해 인스턴스 변수를 더 분리해 보시면 좋을 것 같아요.

2024-10-30 14:54 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session.java
> +    private Session(Long id, LocalDate startDate, LocalDate endDate, SessionImage sessionImage, PaymentType paymentType,
부 생성자는 주 생성자를 호출해 중복을 제거하면 어떨까요?
startDate, endDate 인자는 SessionDate 타입으로 변경하면 인자의 수도 줄일 수 있겠네요

2024-10-30 14:54 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session.java
> +    }
PaymentType이 늘어나면 그 만큼 메서드도 늘어날 수 있는데요
모든 메서드는 checkRecruiting 메서드를 호출해야되는 중복도 발생하게 됩니다.
'수강신청 한다' 라는 개념을 추상화해서 중복을 제거하면 어떨까요?

2024-10-30 14:54 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session.java
> +            throw new IllegalArgumentException("이미 정원이 다 찬 강의입니다.");
정원과 동일한 수강생을 가진 강의에 신청을 한다면 어떻게 될까요?
if 분기에 따른 모든 케이스를 단위 테스트로 검증해 보시면 좋을 것 같아요.
추가로 중복 신청에 대한 검증도 추가하면 좋을 것 같아요.

2024-10-30 14:54 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session.java
> +    }
테스트를 위한 코드는 지양해 주시면 좋을 것 같아요.

2024-10-30 14:54 UTC, testrace commented on src/main/java/nextstep/courses/domain/SessionDate.java
> +    private LocalDate endDate;
재할당을 막기 위한 final을 추가하면 좋을 것 같아요.

2024-10-30 14:54 UTC, testrace commented on src/main/java/nextstep/courses/domain/SessionStatus.java
> +package nextstep.courses.domain;
image처럼 session 관련 도메인들도 하나의 패키지로 이동하면 어떨까요?

2024-10-30 14:54 UTC, testrace commented on src/main/java/nextstep/courses/domain/image/ImageSize.java
> +    private static final int MAX_VOLUME = 1_048_576;
일반적으로 용량을 나타낼 때는 바이트 단위 수식으로 나타냅니다.
1MB의경우 아래처럼 표현하면 쉽고 빠르게 파악 가능합니다.
```suggestion
    private static final int MAX_VOLUME = 1 * 1024 * 1024;
```

2024-10-30 14:54 UTC, testrace commented on src/main/java/nextstep/courses/domain/image/SessionImage.java
> +    private final Long id;
현 시점에 id가 필요할까요?

2024-10-30 14:54 UTC, testrace commented on src/main/java/nextstep/courses/domain/image/SessionImage.java
> +        ImageExtension.confirmImageExtension(fileName);
ImageExtenstion을 상수로만 활용하기 보다 필드로 활용하면 어떨까요?
fileName 변수의 타입을 String이 아닌 별도의 도메인 객체로 도출한다면 confirm 메서드를 호출하는 것이 아니라
객체를 생성하는 과정에서 유효성을 검증할 수 있을 것 같아요
ImageSize 처럼요.

2024-10-30 14:54 UTC, testrace commented on src/test/java/nextstep/courses/domain/ImageSizeTest.java
> +package nextstep.courses.domain;
테스트 코드도 프로덕션 코드의 패키지 구조와 동일하게 맞춰 주시면 좋을 것 같아요
```suggestion
package nextstep.courses.domain.image;
```

2024-10-30 14:54 UTC, testrace commented on src/test/java/nextstep/courses/domain/SessionImageTest.java
> +        assertThat(sessionImage).isNotNull();
SessionTest처럼 내부의 값까지 검증하면 어떨까요?

2024-10-30 14:54 UTC, testrace commented on src/test/java/nextstep/courses/domain/SessionImageTest.java
> +    }
예외 메시지까지 검증하면 어떨까요?

2024-10-30 14:54 UTC, testrace commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +    void 무료_강의_신청() {
유료 강의 신청 테스트는 없네요 😢 
전체적으로 단위 테스트가 부족하거나, 있다 하더라도 내용이 빈약한 느낌입니다.
단위 테스트는 부족하고 기능 목록 정의도 없고 커밋 단위도 매우 크기에 TDD 사이클로 개발한 흔적을 찾을 수 없었습니다.
이전 단계에서 학습하신 내용을 '모두' 적용해서 진행해 보시는 것을 추천드립니다.

2024-10-30 16:35 UTC, hwan2-99 commented on src/main/java/nextstep/courses/domain/Session.java
> +public class Session {
이 부분은 최대한 고민한게 이정도인데 더 분리할 수 있을까요..? 제일 힘들었던 부분이었던것 같습니다 :(

2024-10-30 16:35 UTC, hwan2-99 commented on src/main/java/nextstep/courses/domain/Session.java
> +    private Session(Long id, LocalDate startDate, LocalDate endDate, SessionImage sessionImage, PaymentType paymentType,
그렇게 처리할 수 잇겠네요..! 수정하겠습니다.

2024-10-30 16:35 UTC, hwan2-99 commented on src/main/java/nextstep/courses/domain/Session.java
> +    }
이부분도 고민을 했었던 부분입니다! 주어진 요구사항만 보고 위와같이 구현했는데 확장성을 위해서 추상화하는게 좋아보이네요! 감사합니다

2024-10-30 16:35 UTC, hwan2-99 commented on src/main/java/nextstep/courses/domain/Session.java
> +    }
이코드는 테스트코드만을 위한 코드가 아닙니다!.. 제 딴엔 언젠가 강의의 상태를 변경할때의 서비스를 위한코드라고 생각해서 만들었습니다, 어쩌다보니 테스트코드에 사용되었습니다... 그럼에도 지우는게 맞을까요..

2024-10-30 16:35 UTC, hwan2-99 commented on src/main/java/nextstep/courses/domain/image/ImageSize.java
> +    private static final int MAX_VOLUME = 1_048_576;
처음알았네요.. 감사합니다

2024-10-30 16:35 UTC, hwan2-99 commented on src/main/java/nextstep/courses/domain/image/SessionImage.java
> +    private final Long id;
다시보니 도메인모델만 먼저 구현하는거였네요! 테이블까지 한번에 생각하다보니 id를추가했습니다.. 수정하겠습니다.

2024-10-30 16:38 UTC, hwan2-99 commented on src/test/java/nextstep/courses/domain/SessionImageTest.java
> +    }
기존에는 어떤타입의 예외만일어났는지 확인했었는데 예외메시지까지 검증하면 확실하게 처리할 수 있겠네요!

2024-10-30 16:40 UTC, hwan2-99 commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +    void 무료_강의_신청() {
제가 커밋분기가 꼬여서 작성한부분이 사라졌네요.. 추가하겠습니다!
`DB 테이블 설계 없이 도메인 모델부터 구현한다.` 라는 요구사항을 놓치고 테이블 설계부터 하다보니 제 고민이 길어져서 커밋단위도 어떤기준을 해야할지 고민하다보니 크게 잡고 구현했던것 같습니다.. 다시 잘 고민해보겠습니다

2024-10-30 16:42 UTC, hwan2-99 commented on src/main/java/nextstep/courses/domain/image/SessionImage.java
> +        ImageExtension.confirmImageExtension(fileName);
이부분은 궁금한게 있습니다! 열거형 클래스가 아닌 필드로 활용하면 장점이 따로 있을지가 궁금합니다. 이렇게 해도 해당객체를 생성하는 과정에서 유효성을 검증하는 단계가 아닌가요?? 제가 이해를 잘못한걸까요??

2024-10-31 11:10 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session.java
> +public class Session {
수강신청 기능과 관련있는 필드끼리 분리하면 어떨까요?

2024-10-31 11:22 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session.java
> +    }
`언젠가 강의의 상태를 변경할때` 예상이 가능한 요구사항이라도 당장 필요하지 않다면 만들지 않으시는것을 추천드립니다.
[YAGNI](https://ko.wikipedia.org/wiki/YAGNI) 라는 말이 있습니다. 참고해 보시면 좋을 것 같아요.
말씀하신 것처럼 기능이 아닌 용도의 설명이 필요한 코드라면 제거하는 것이 맞다고 생각합니다.
코드를 읽는 모두에게 설명을 해줘야하 하는 코드라면 얼마든지 오해할 수 있다고 생각해요.
생성자에서 SessionStatus 값을 인자로 받아 할당해서 상태별 강의를 만들면 어떨까요?

2024-10-31 11:37 UTC, testrace requested changes
피드백 반영 잘해주셨네요 👍 
조금만 더 개선하고 넘어가면 좋을 것 같아요.
코멘트 확인해 주시고 다시 리뷰 요청해 주세요.

2024-10-31 11:37 UTC, testrace commented on src/main/java/nextstep/courses/domain/image/SessionImage.java
> +        ImageExtension.confirmImageExtension(fileName);
열거타입의 변수를 활용해 보시라는 코멘트였습니다 😃 
Session 이 SessionStatus 필드를 가지는 것처럼요.
```java
    public SessionImage(String fileName) {
        this.extention = ImageExtention.of(fileName);
    }
```

그리고 confirmImageExtension 메서드도 단위 테스트를 추가해 보시면 좋을 것 같아요.

2024-10-31 11:37 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/Session.java
> +    public void subscribe(NsUser user) {
유료 강의인데 subscribe 메서드를 호출하게 되면 어떻게 될까요?
유료/무료 구분은 Session이 가장 잘 알고 있으니 직접 분기하면 어떨까요?
여전히 PaymentType에 따라 메서드는 계속해서 늘어날 수 있는 상황인데요
PaymentType와 관계없는 요구사항이 추가되어도 Session 객체의 코드는 계속 늘어나게 됩니다.
수강신청 기능과 직접 관련있는 객체를 도출해 책임을 위임하면 어떨까요?
```java
public void subscribe(NsUser user) {
    enrollment.enroll(user);
}
```

추가로 수강신청 기능의 흐름을 알 수 있게 간단한 Service 클래스도 추가해 보시면 좋을 것 같아요.

2024-10-31 11:37 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/Session.java
>      public void subscribePaidSession(NsUser user, Payment payment) {
추상화를 제안드렸는데 변경된 코드에서는 어떤 의도로 추상화해주셨는지 알기 어렵네요 😅 
무료강의신청, 유료강의신청 메서드가 나뉘어 있다면 
신청하는 입장에서 어떤 메서드를 호출해야할지 내부 상황을 알고 있어야 합니다.
추상화가 된다면 신청하는 입장에서 신청 객체 내부를 몰라도 그냥 신청만 하면됩니다.
'수강신청' 이라는 객체를 도출해서 어떤 유효성들을 검증할지는 내부에서 판단하면 어떨까요?

2024-10-31 11:37 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/Session.java
> +            if (subscriber.getUserId().equals(user.getId())) {
>규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다
>규칙 8: 일급 콜렉션을 쓴다.
>규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

userId를 꺼내서 비교하지 않고 메시지를 보내면 어떨까요?
나아가 Subscriber 라는 객체가 지금 필요한지 고민해 보셔도 좋을 것 같아요.

2024-10-31 11:37 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/Subscriber.java
> +    }
사용하지 않는 코드는 제거해 주세요.

2024-10-31 11:37 UTC, testrace commented on src/test/java/nextstep/courses/domain/session/SessionTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
예외 타입만 보면 user 에게 뭔가 잘못이 있을 것 같은데요.
강의 상태에 따라 던져진 예외이니 적절한 표준예외나 커스텀 예외를 만들어 활용하면 어떨까요?

2024-10-31 11:37 UTC, testrace commented on src/test/java/nextstep/courses/domain/session/SessionTest.java
> +        NsUser user1 = NsUserTest.JAVAJIGI;
`무료_강의_중복신청_예외처리` 테스트와 다르지 않는 테스트입니다.
'강의상태', '중복신청' 같은 검증을 PaymentType 만큼 계속 추가해야할 수 있습니다.
수강신청 이라는 기능에서 공통적으로 처리할 수 있는 부분을 분리할 수 없는지 고민해 보시면 좋을 것 같아요.

2024-10-31 11:37 UTC, testrace commented on docs/README.md
> +  - [x] 강의 수강신청은 강의 상태가 모집중일 때만 가능하다.
요구사항을 그대로 작성하기 보다 요구사항을 토대로 설계하신 내용 위주로 작성해 주시면 더 좋을 것 같아요.

2024-11-03 22:27 UTC, testrace approved these changes
안녕하세요 태환님 😃 
피드백 반영 잘해주셨네요 👍 
소소하게 코멘트 남겼는데 확인해 주시고 다음 단계 진행해 주세요.
핵심 학습 목표가 중요하니 꼭 참고해 주세요.

2024-11-03 22:27 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/SessionException.java
> +public class SessionException extends Exception {
Unchecked Exception 을 상속하면 어떨까요?

2024-11-03 22:27 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/Subscription.java
> +import nextstep.payments.domain.Payment;
사용하지 않는 코드, import는 제거해 주시면 좋을 것 같아요.
Subscriber 클래스도 사용하고 있지 않고 있어요.

2024-11-03 22:27 UTC, testrace commented on src/test/java/nextstep/courses/domain/session/SessionTest.java
> +    void 무료_강의_신청() throws SessionException {
신청 기능은 Subscription 클래스의 책임이니 테스트 코드도 SubscriptionTest로 이동하면 어떨까요?

2024-11-03 22:27 UTC, merged