🚀 2단계 - 수강신청(도메인 모델)
next-step/java-lms pull request #597
Opened 2024-10-30 07:54 UTC by Jureamer

안녕하세요 리뷰어님!

2단계 수강신청 (도메인 모델) 구현 완료하였습니다.

리뷰 부탁드리겠습니다~!

2024-10-30 11:55 UTC, catsbi requested changes
주형님 2단계 수강신청(도메인모델) 미션 잘 진행해주셨어요. 

몇가지 고민해보면 좋을 것 같아 코멘트 남겨드렸으니 확인 후 다시 리뷰요청 부탁드려요! 😄

2024-10-30 11:55 UTC, catsbi commented on src/main/java/nextstep/courses/domain/Course.java
> +    private List<Session> sessions = new ArrayList<>();
여기도 일급 컬렉션을 활용해볼 수 있지 않을까요?

2024-10-30 11:55 UTC, catsbi commented on src/main/java/nextstep/courses/domain/Image/ImageHeight.java
> +public class ImageHeight {
일급객체 설계 👍

2024-10-30 11:55 UTC, catsbi commented on src/main/java/nextstep/courses/domain/Student.java
> +public class Student extends NsUser {
일반 상용클래스를 상속하는건 권장드리지 않습니다. 행위에만집중하는 인터페이스 혹은 정말 공통으로 쓰는 필드들이 있고, 템플릿이 존재하고 재사용이 많은 경우  추상클래스를 사용할 수 있지만 일반 클래스는 상속해서 사용하기에는, 부모클래스의 단점이나 제약까지 같이 가져온다는 부분에서 권장드리지 않습니다. 

이펙티브자바에서도 권장하듯 상속보다는 위임으로 처리해보는건 어떨까요?

2024-10-30 11:55 UTC, catsbi commented on src/main/java/nextstep/courses/infrastructure/JdbcCourseRepository.java
> +//package nextstep.courses.infrastructure;
사용하지 않는 코드는 제거해주셔도 됩니다 ㅎㅎ 형상관리툴(git)을 사용하기때문에 추적도 가능하기 때문에 불필요한 코드로 가독성만 낮추는것보다 삭제하는걸 권장드려요

2024-10-30 11:55 UTC, catsbi commented on src/main/java/nextstep/office/Office.java
> +public class Office {
해당객체는 사용하지 않는 객체로 보여요 🤔

2024-10-30 11:55 UTC, catsbi commented on src/main/java/nextstep/courses/domain/Course.java
> +    public Payment processPayment(Student student, Long amount, Session session) {
해당함수도 Office만을 위한 함수로 보이는데 Office는 사용하지 않는걸로 보이네요!

2024-10-30 11:55 UTC, catsbi commented on src/main/java/nextstep/courses/domain/Session.java
> +    }
동일한 타입의 매개변수가 연달아 이어지고 그 매개변수가 4개가 넘어가는경우, 휴먼에러가 발생할 확류이 높아져요. 그런데 이는 컴파일에러가 아니기에 에러로 잡히지 않아 더 큰 문제가 될 가능성도 생기죠. 

그래서 이런 경우 빌더패턴을 권장하는편인데요. 해당 객체가 가진 필드들을보면 빌더패턴을 적용해봐도 좋겠다는 생각이 드는데 주형님은 어떻게 생각하시나요 ?!

2024-10-30 12:23 UTC, Jureamer commented on src/main/java/nextstep/courses/domain/Course.java
> +    private List<Session> sessions = new ArrayList<>();
일급 컬렉션 활용해서 수정해보겠습니다!

2024-10-30 12:25 UTC, Jureamer commented on src/main/java/nextstep/courses/domain/Student.java
> +public class Student extends NsUser {
아 그렇군요! 위임 방식을 이용해서 한 번 수정 해보도록 하겠습니다!

2024-10-30 12:25 UTC, Muzzle-kr commented on src/main/java/nextstep/courses/infrastructure/JdbcCourseRepository.java
> +//package nextstep.courses.infrastructure;
넵 사용하지 않는 부분 제거하겠습니다~

2024-10-30 12:27 UTC, Jureamer commented on src/main/java/nextstep/office/Office.java
> +public class Office {
Service를 구현하지 않았더니 미사용 되었네요. 이 부분 참고해서 수정하겠습니다~

2024-10-30 12:27 UTC, Jureamer commented on src/main/java/nextstep/courses/domain/Course.java
> +    public Payment processPayment(Student student, Long amount, Session session) {
이 부분도 수정하겠습니다!

2024-10-30 12:29 UTC, Muzzle-kr commented on src/main/java/nextstep/courses/domain/Session.java
> +    }
이 부분 빌더 패턴을 고려 해보기도 했습니다! 다른 자료형으로 들어오는 경우 처리를 어떻게 해야할 지 아직은 잘 모르겠지만 한 번 찾아보며 수정 해보겠습니다!

2024-10-30 13:18 UTC, Jureamer commented
리뷰어님! 

피드백 주신 부분 반영해보았습니다!

그리고 질문이 하나 있습니다.

Office를 삭제하고 나니, 따로 Course를 처리해줄 부분이 없어 CourseService에서 Course 처리하는 부분을 만들어주었습니다.
그런데 CourseService는 따로 MainApplication에서 불러주지 않는데 이 부분도 구현을 같이 해야하나 애매해서 일단은 제외하고 만들었습니다. 

이 부분은 추후 단계에서 구현하면 되는 부분일 지 아니면 해당 단계에서 CourseService를 사용하는 부분도 같이 구현해야하는 지 궁금해서 여쭙고 싶습니다!

그럼 재리뷰 부탁드리겠습니다~

2024-10-30 14:53 UTC, catsbi approved these changes
주형님 피드백반영 빠르게 해주셨네요 👍 

몇 가지 추가적으로 피드백 남겨드렸는데 확인 후 다음 3단계 미션에서 반영해보는걸로 하죠. ㅎㅎ

2단계는 머지하도록 하겠습니다!

2024-10-30 14:53 UTC, catsbi commented on src/main/java/nextstep/courses/domain/Course.java
> +    private Sessions sessions = new Sessions(new ArrayList<>());
new ArrayList초기화는 굳이 여기서 해주기보단 Sessions 일급 컬렉션에서 필드초기화로 빼도 괜찮을 것 같네요. 
오히려 컬렉션 자료구조같은경우 필드초기화를 통해 NPE 위험을 줄일수도 있구요 ㅎ

2024-10-30 14:53 UTC, catsbi commented on src/main/java/nextstep/courses/infrastructure/JdbcCourseRepository.java
> +                toLocalDateTime(rs.getTimestamp(5)));
RowMapper는 기본적으로 FunctionalInterface 스펙입니다(참고: [link](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/RowMapper.html))

그렇기 때문에 람다표현식을 통해 상수로 분리해줘도 괜찮을 것 같네요! 검색(select) 메서드가 현재는 findById뿐이지만 더추가될수도 있으니까요 ㅎㅎ

2024-10-30 14:53 UTC, catsbi commented on src/main/java/nextstep/sessions/Session.java
> +        private final String endDate;
두 값이 날짜타입이 아닌 문자타입인 이유가 있을까요 🤔

2024-10-30 14:53 UTC, catsbi commented on src/main/java/nextstep/courses/domain/Course.java
> +        session.register(student, amount);
바로 register 시도후 예외가 발생하면 이후 대응보다는, registrable과 같은 함수를 이용해 등록가능한지 확인 후 등록하는것도 괜찮을 것 같네요!

2024-10-30 14:53 UTC, catsbi commented on src/main/java/nextstep/users/domain/Student.java
> +    private NsUser nsUser;
피드백 반영 👍

2024-10-30 14:53 UTC, catsbi commented on src/test/java/nextstep/sessions/domain/SessionTest.java
> +public class SessionTest {
테스트를 작성하는건 귀찮지만 꼭 필요한 과정이죠 ㅎㅎ
그런데 테스트는 참 작성하기도 귀찮은데 실무에서 사실 한 번 작성한뒤로는 유지보수를 잘 하지 않기도 합니다. 
그렇기에 가독성과 유지보수성이 중요해요. 관리조차 어려우면 버려지기 더쉽거든요. 

그렇기에 저는 DisplayName등과 같은 주석이든 함수든 최소한 테스트케이스별로 어떤 함수가 어떤 조건에서 어떤 결과가 예상되는지는 작성해서 테스트 코드를 하나하나 안봐도 테스트 결과 콘솔창만 보고도 파악이 될 수 있도록 하는편입니다.

2024-10-30 14:53 UTC, merged

2024-10-30 14:56 UTC, catsbi commented
> Office를 삭제하고 나니, 따로 Course를 처리해줄 부분이 없어 CourseService에서 Course 처리하는 부분을 만들어주었습니다.
그런데 CourseService는 따로 MainApplication에서 불러주지 않는데 이 부분도 구현을 같이 해야하나 애매해서 일단은 제외하고 만들었습니다.
이 부분은 추후 단계에서 구현하면 되는 부분일 지 아니면 해당 단계에서 CourseService를 사용하는 부분도 같이 구현해야하는 지 궁금해서 여쭙고 싶습니다!   

기본적으로 미션의 요구사항을 최소 조건으로 하되 추가적으로 더 고민해보고 만드는것은 나쁘지 않다고 봅니다. 
현재 미션의 핵심은 TDD기반으로 도메인설계와 기능을 bottom-up으로 개발하는것에 있기 때문에 애플리케이션이나 컨트롤러등까지 고려하진 않으셔도 괜찮을 것 같아요 테스트를 통해 전부 충분히 테스트가 가능하니까요 ㅎㅎ 
Service를 구현하셨다면, 그리고 그 기능들이 요구사항과 맞다면 테스트코드는 작성하는게 맞지 않을까 생각하네요 ㅎㅎ

2024-10-31 10:03 UTC, Jureamer commented on src/main/java/nextstep/sessions/Session.java
> +        private final String endDate;
앗! 놓친 부분이네요 LocalDateTime으로 수정하겠습니다!

2024-10-31 10:08 UTC, Jureamer commented on src/main/java/nextstep/courses/domain/Course.java
> +        session.register(student, amount);
이 부분은 아직 헷갈리는 부분이긴 합니다! 하나의 메소드에 validate하는 부분을 같이 넣을 지 분리해서 하는 게 좋을지요.
하나의 메소드는 하나의 책임을 갖는 게 맞지만 validate 같은 부분은 조금 애매하더라구요. 
regiestrable 같은 경우는 다른 validation과는 의미적으로 다르기 때문에 별도로 메소드를 만들어주는 게 더 나은걸까요?

2024-10-31 10:21 UTC, Jureamer commented on src/test/java/nextstep/sessions/domain/SessionTest.java
> +public class SessionTest {
테스트 결과만 봐도 알 수 있도록 꼼꼼하게 작성해보겠습니다!