Step1
next-step/java-lms pull request #602
Opened 2024-10-30 14:53 UTC by kkksusu161

안녕하세요 리팩토링은 부끄럽지만 처음이라
잘부탁드립니다.

꼼꼼한 피드백 감사합니다!

2024-10-31 11:05 UTC, nooose requested changes
안녕하세요 반갑습니다! 리뷰어 성준혁입니다.
개선하면 좋겠어서 코멘트 남겼어요
확인 부탁드립니다!

2024-10-31 11:05 UTC, nooose commented on src/main/java/nextstep/qna/domain/Question.java
> +    private Answers answers;
일급컬렉션 사용 좋네요! 👍 👍

2024-10-31 11:05 UTC, nooose commented on src/main/java/nextstep/qna/domain/Question.java
> +        if(answers == null) {
```suggestion
        if (answers == null) {
```

2024-10-31 11:05 UTC, nooose commented on src/main/java/nextstep/qna/domain/Question.java
> +    public void isOwnerCheck(NsUser loginUser) throws CannotDeleteException {
```suggestion
    public void checkOwner(NsUser loginUser) throws CannotDeleteException {
```
isXXX 네이밍은 boolean 을 반환하는 것으로 오해할 수 있어보여요
validate나 check 같은 표현이 어울릴 것 같습니다.

2024-10-31 11:05 UTC, nooose commented on src/main/java/nextstep/qna/domain/Question.java
> +    private QuestionBoard questionBoard;
값 객체 래핑 좋습니다. 👍
 
지금은 단순 묶음을 위한 래핑으로 보이는데 값 검증을 위한 로직이 추가되면 더 좋을 것 같아요

2024-10-31 11:05 UTC, nooose commented on src/main/java/nextstep/qna/domain/Question.java
> +            answers = new Answers(new ArrayList<>());
```suggestion
            answers = new Answers(Collections.emptyList());
```

빈 리스트라면 제공하고 있는 `emptyList`를 사용하는 것을 권장드려요
왜 그럴까요?

2024-10-31 11:05 UTC, nooose commented on src/main/java/nextstep/qna/service/QnAService.java
> +        saveDeleteHistory(questionId, question, answers);
상황에 따라 서비스에 로직이 필요할 수 있지만
지금 상황에서 모든 로직을 도메인 모델에서 처리할 수 있을 것 같습니다!
```java
        Question question = getQuestion(questionId);
        var 이력리스트 = question.deleteQuestion(loginUser);
        deleteHistoryService.saveAll(이력리스트);
```
위 모양이 나오도록 리팩토링해보면 좋겠습니다! 🚀

2024-10-31 11:05 UTC, nooose commented on src/main/resources/step1.md
> +- [x] 각 도메인 객체 테스트 추가
👍

2024-10-31 11:05 UTC, nooose commented on src/test/java/nextstep/qna/domain/QuestionTest.java
> +    }
👍

2024-10-31 12:02 UTC, kkksusu161 commented on src/main/java/nextstep/qna/domain/Question.java
> +            answers = new Answers(new ArrayList<>());
두 방법의 핵심적인 차이점는 불변성이군요!

2024-10-31 12:08 UTC, kkksusu161 commented on src/main/java/nextstep/qna/service/QnAService.java
> +        saveDeleteHistory(questionId, question, answers);
저 모양이 나오면 안에서는 질문과답변을 삭제, 히스토리를 쌓는다. 인데 한 메소드는 한가지 일 만해야된다고 들었는데 그정도는 괜찮을까요? 커밋하였습니다!

2024-10-31 15:10 UTC, nooose commented on src/main/java/nextstep/qna/domain/Question.java
> +            answers = new Answers(new ArrayList<>());
emptyList는 이미 생성되어있는 빈 리스트를 반환해요
이런 점 때문에 새로운 객체를 생성하지 않아도 된다는 장점이 있습니다.

<img width="659" alt="image" src="https://github.com/user-attachments/assets/5a79bae3-8349-491a-865a-3d2826c256a4">

2024-10-31 15:31 UTC, nooose commented on src/main/java/nextstep/qna/service/QnAService.java
> +        saveDeleteHistory(questionId, question, answers);
> 도메인 모델에서만 처리할 수 있는 좋은점을 알겠는데 여기 있는 모든 로직을 혹시 왜 Question안에 넣도록 설계하게 될까요? 저는 Answer가 Question 안에서 호출함으로서 의존하게 되는 것 같아서 찝찝함에 서비스에서는 호출만 하면 되니까 역할 때문에 다 넣지는 않게 되었는데요 제가 서비스단에 비즈니스 로직이 가득한 곳에서 일하다보니 아직 명확히 이런 상황에 이러 이러해서 Question안에 다 넣어야지! 라는 이런감이 안옵니다.
> 

Question 안에서 Answer를 의존하는 것은 연관관계가 맺어있기 때문에 의존하는 것은 자연스러운 상황입니다.
그렇기 때문에 서비스가 아닌 도메인 모델안으로 녹여저도 괜찮다고 보는 것이죠
그렇다고해서 객체와 연관관계를 모두 맺어야할까요?
저는 객체가 **변경될 때** 지켜져야하는 유효성 검사가 같이 수행되어야하거나, 라이프 사이클이 같으면 연관관계를 맺고 있습니다.

> 또한 저 모양이 안에서는 질문과답변을 삭제, 히스토리를 쌓는다. 인데 한 메소드는 한가지 일 만해야된다고 들었는데 그정도는 괜찮을까요?pr올렸습니다. 확인부탁드립니다 감사합니다!

QnAService의 deleteQuestion 메소드를 보면 
1. 질문을 찾아
2. **삭제를 하고** 
3. 삭제 이력을 저장

위 3가지 일을 하고 있습니다. 이 3개의 작업이 하나의 질문 삭제 유즈케이스로 보는 것이죠
`question.deleteQuestion(loginUser);` 코드를 봤을때 질문 삭제를 위한 메시지를 전달하고 있다는 점에서 
삭제라는 하나의 목적(**2번**)을 위해 수행하고 있으므로 '한 가지 일'로 볼 수 있습니다.

2024-10-31 15:32 UTC, nooose commented on src/main/java/nextstep/qna/service/QnAService.java
> +        saveDeleteHistory(questionId, question, answers);
좋은 질문인 것 같고 저도 다시 생각해 볼 수 있었습니다.
관련해서 더 질문주시면 답변드리도록 할게요

2024-10-31 15:35 UTC, nooose approved these changes
잘 반영되었네요 👍 
답변 남겼어요 
확인 후 다음 단계 진행해 주세요!

2024-10-31 15:35 UTC, nooose commented on src/main/java/nextstep/qna/service/QnAService.java
> +    }
리팩토링 잘 되었어요 👍 

다음부터 리팩토링 후 불필요한 주석이나 코드는 제거하면 혼란을 줄일 수 있을 것 같아요

2024-10-31 15:37 UTC, merged

2024-11-01 08:45 UTC, kkksusu161 commented on src/main/java/nextstep/qna/domain/Question.java
> +            answers = new Answers(new ArrayList<>());
감사합니다!