Step2 commit
next-step/java-lms pull request #606
Opened 2024-10-31 07:10 UTC by Ryumina-edu

2024-11-01 02:30 UTC, testrace requested changes
안녕하세요 미나님 😃 
2단계 깔끔하게 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청해 주세요.

2024-11-01 02:30 UTC, testrace commented on src/main/java/nextstep/courses/CannotApplyException.java
> +public class CannotApplyException extends Exception {
CheckedException 을 상속하신 이유가 있으실까요?
UncheckedException을 상속하면 어떨까요?

2024-11-01 02:30 UTC, testrace commented on src/main/java/nextstep/courses/ImageUtils.java
> +public class ImageUtils {
객체 설계가 중심인 미션이니 유틸 클래스 없이 구현해 보시는 것을 추천드립니다.

2024-11-01 02:30 UTC, testrace commented on src/main/java/nextstep/courses/domain/ImageType.java
> +//    }
사용되지 않는 코드는 제거해 주시면 좋을 것 같아요.

2024-11-01 02:30 UTC, testrace commented on src/main/java/nextstep/courses/domain/ImageType.java
> +    }
테스트만 존재하고 프로덕션 코드에는 활용되고 있지 않네요.
이 코드도 사용되지 않는다면 제거하거나 SessionCoverImage 객체 생성할 때 활용하면 어떨까요?

2024-11-01 02:30 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session.java
> +    private Long id;
현 시점에서 id가 필요할까요?

2024-11-01 02:30 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session.java
> +    }
특정 생성자들은 PayType 필드를 초기화 하지 않기 때문에 정상적인 책임을 수행할 수 없는 구조입니다.
이런 경우는 단순히 테스트를 위해 생성자를 추가했다고 생각됩니다.
다양한 생성자를 제공하는 것은 좋지만 객체가 온전히 책임을 수행하는 전제는 필수라고 생각합니다.
점층적 생성 패턴등을 활용해 모든 부 생성자는 주 생성자를 호출하는 구조로 개선해 보시면 좋을 것 같아요.

2024-11-01 02:30 UTC, testrace commented on src/main/java/nextstep/courses/domain/SessionCoverImage.java
> +package nextstep.courses.domain;
이미지와 관련된 클래스들은 하나의 패키지를 만들어 이동하면 어떨까요?
이미지 외에도 관련있는 클래스들은 패키지로 구분해 보시면 좋을 것 같아요.

2024-11-01 02:30 UTC, testrace commented on src/main/java/nextstep/courses/domain/Size.java
> +    private static final long MAX_SIZE = 1_048_576L;
관례적으로 용량은 바이트 단위 수식으로 나타내면 어떨까요?
```suggestion
    private static final long MAX_SIZE = 1 * 1024 * 1024;
```

2024-11-01 02:30 UTC, testrace commented on src/main/java/nextstep/courses/domain/Students.java
> +    private int maxStudentCount;
클래스명만 봤을 땐 수강생 목록이라고 예상했는데요.
카운트와 관련있는 객체라면 클래스명에도 카운트와 관련된 네이밍을 하면 어떨까요?

2024-11-01 02:30 UTC, testrace commented on src/main/java/nextstep/courses/domain/Students.java
> +    }
단위 테스트가 없네요 😢 
모든 기능을 TDD 사이클을 지키면서 구현해 보시는 것을 추천드립니다.
커밋에 그 흔적을 남겨주시면 더 좋을 것 같아요.

2024-11-01 02:30 UTC, testrace commented on src/test/java/nextstep/courses/ImageUtilsTest.java
> +    private String imageUrl = "C:\\Users\\mina\\OneDrive\\바탕 화면\\Red_Apple.jpg";
테스트는 언제 어디서나 항상 통과해야합니다.
<img width="860" alt="image" src="https://github.com/user-attachments/assets/abb13b63-0b42-4f12-8a10-82efb80c78c6">

로컬 파일을 활용한 테스트는 지양해 주시면 좋을 것 같아요.
앞선 코멘트에서도 말씀드렸지만 유틸 클래스는 제거하면 좋을 것 같아요.

2024-11-01 02:30 UTC, testrace commented on src/test/java/nextstep/courses/domain/RatioTest.java
> +    void create_올바른_비율이_아닌_경우() {
테스트 코드는 객체의 명세서 역할이 가능하니 올바르지 않는 기준이 무엇인지 명확히 하면 어떨까요?
예외 케이스가 있다면 정상 케이스도 있으니 테스트를 추가하면 좋을 것 같아요

2024-11-01 02:30 UTC, testrace commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +    void 최대_수강_인원_초과() {
>무료 강의는 최대 수강 인원 제한이 없다.

무료 강의에 대한 검증도 추가하면 어떨까요?

2024-11-01 02:30 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session.java
> +    private LocalDateTime endDateTime;
>규칙 6: 모든 엔티티를 작게 유지한다.
>규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

인스턴스 변수의 수를 최대한 줄여 보시면 좋을 것 같아요.
신청과 직접 관련 있는 필드들을 분리하거나 시작일 종료일을 묶어 기간 검증도 할 수 있을 것 같아요.

2024-11-01 02:30 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session.java
> +        }
apply 메서드를 호출하는 간단한 Service 클래스도 추가해 보시면 좋을 것 같아요.

열거 타입을 비교할 때도 메시지를 보내면 어떨까요?
`status.isRecruit()`

중복 신청에 대한 검증도 추가해 보시면 좋을 것 같아요.

그리고 수강신청 조건이 추가되면 apply 메서드 내부는 길어질 수 밖에 없을 것 같아요.
추상화를 활용해 조건을 분리하는 방법도 고려해 보시면 좋을 것 같아요.

2024-11-02 13:43 UTC, Ryumina-edu commented on src/main/java/nextstep/courses/CannotApplyException.java
> +public class CannotApplyException extends Exception {
생각 없이 CheckedException을 상속했던 것 같아요..!
반성하겠습니다!

2024-11-02 13:47 UTC, Ryumina-edu commented on src/test/java/nextstep/courses/ImageUtilsTest.java
> +    private String imageUrl = "C:\\Users\\mina\\OneDrive\\바탕 화면\\Red_Apple.jpg";
넵 유틸 클래스는 제거하도록 하겠습니다!

2024-11-02 15:10 UTC, Ryumina-edu commented on src/main/java/nextstep/courses/domain/Session.java
> +    }
테스트를 위해 생성자를 너무 무자비하게 생성했던 것 같습니다.
좀 더 생각 후 코드 수정하도록 하겠습니다.
좋은 피드백 감사드립니다!

2024-11-03 15:03 UTC, Ryumina-edu commented
정성스러운 피드백 감사드립니다!
시간은 오래 걸렸지만 그래도 많은 부분을 수정하면서 배운 것이 많은 것 같습니다 ㅎㅎ

한가지 질문 드리고 싶은 것이 있는데요,
피드백 주신 내용 중
> 무료 강의에 대한 검증도 추가하면 어떨까요?
위 부분에 대해 아직 수정을 하지 못한 상태인데 현재 구조에서 어떤 방향으로 수정을 하는 것이 좋을 지 조언 부탁드리겠습니다!
무료 강의일 경우 최대 수강 학생 수를 임의로 9999로 설정한다던가 이런저런 생각을 해봤는데
현재 구조에서 어떻게 수정을 하면 좋을 지 조금 감이 안잡혀서요.. 부탁드리겠습니다! 🙏

2024-11-03 23:39 UTC, testrace requested changes
안녕하세요 미나님 😃 
피드백 반영 잘해주셨네요 👍 
조금만 더 개선하면 좋을 것 같아 코멘트 남겨두었습니다.
확인해 주시고 다시 리뷰 요청해 주세요.

2024-11-03 23:39 UTC, testrace commented on src/main/java/nextstep/courses/domain/Course/Course.java
> +package nextstep.courses.domain.Course;
패키지명은 [컨벤션](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names)에 따라 소문자로 작성해 주세요

2024-11-03 23:39 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session/Enrollment.java
> +    private Students students;
final 키워드를 추가하면 어떨까요?
가능한 불변 객체를 활용해 보시면 좋을 것 같아요.

2024-11-03 23:39 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session/PayType.java
> +        if (!isFree() && price == 0) {
부정문은 상대적으로 가독성이 떨어지니 긍정문으로 표현하면 어떨까요?
```suggestion
        if (isPay() && price == 0) {
```

2024-11-03 23:39 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session/SessionCoverImage/SessionCoverImage.java
> +    private SessionCoverImageType sessionCoverImageType;
ImageType 타입을 활용하면 어떨까요?

2024-11-03 23:39 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session/Students.java
> +        }
>무료 강의일 경우 최대 수강 학생 수를 임의로 9999로 설정한다던가 이런저런 생각을 해봤는데
현재 구조에서 어떻게 수정을 하면 좋을 지 조금 감이 안잡혀서요.. 부탁드리겠습니다! 🙏

인원 제한 값을 `Integer.MAX_VALUE` 등으로 설정하면 지금의 구조도 당장 큰 문제는 없을 것 같아요.
특정 방법대로 해야만하는 정답은 없지만 지금까지 학습하신 객체 설계에 대해 학습하셨으니 객체를 활용해 해결해 보시는 것을 추천드립니다.
'수강신청' 이라는 개념을 추상화하고, 무료/유료에 따라 구현체를 달리하면 어떨까요?

2024-11-03 23:39 UTC, testrace commented on src/test/java/nextstep/courses/domain/Session/SessionTest.java
> +        SessionPeriod sessionPeriod = new SessionPeriod(startDateTime, endDateTime);
여러 테스트에서도 반복되어 사용되는 인스턴스들은 Fixture로 만들어 활용하면 어떨까요?

2024-11-03 23:39 UTC, testrace commented on src/main/java/nextstep/courses/domain/Session/Enrollment.java
> +public class Enrollment {
신청과 관련된 클래스들도 하나의 패키지로 관리해도 좋을 것 같아요.

2024-11-04 14:41 UTC, testrace approved these changes
안녕하세요 미나님 😃 
피드백 반영 잘해주셨네요 👍 
소소하게 코멘트 남겼는데 확인해 주시고 다음 단계 진행해 주세요.
핵심 학습 목표가 중요하니 꼭 참고해 주세요.

2024-11-04 14:41 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/sessionCoverImage/Size.java
> +package nextstep.courses.domain.session.sessionCoverImage;
[컨벤션](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names)에 따라 패키지명의 알파벳은 소문자만 사용하면 좋을 것 같아요

2024-11-04 14:41 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/enrollment/Enrollment.java
> +    void enroll(NsUser student, Payment payment);
인터페이스를 활용해 주셨네요 👍

2024-11-04 14:41 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/enrollment/FreeEnrollment.java
> +    private final Price price;
무료 강의는 price가 없어도 괜찮지 않을까요?

2024-11-04 14:41 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/sessionCoverImage/SessionCoverImage.java
> +    private final String imageFileType;
String 타입 대신 ImageType 을 활용하면 어떨까요?
```suggestion
    private final ImageType imageFileType;
```

2024-11-04 14:41 UTC, merged