2단계 - 수강신청(도메인 모델)
next-step/java-lms pull request #618
Opened 2024-11-02 05:46 UTC by yunji1201

안녕하세요 리뷰어님

늦었지만 2단계 진행하였습니다.
조금이라도 수정이 필요할 것같은 부분, 모두 코멘트 남겨주시면 감사하겠습니다! :)

2024-11-02 14:06 UTC, shared-moon requested changes
윤지님 안녕하세요!
2단계 미션 잘 진행 해 주셨네요 :)
코멘트를 좀 남겨 두었는데, 확인 후 리뷰 재요청 부탁드려요!
고생 많으셨습니다 :)

2024-11-02 14:06 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/Image.java
> +            throw new IllegalArgumentException("파일은 너비가 300px, 높이가 200px 미만이어야 합니다.");
>이미지의 width는 300픽셀, height는 200픽셀 이상이어야 하며, width와 height의 비율은 3:2여야 한다.

유효성검사가 잘못 걸린 것 같아요!

2024-11-02 14:06 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/Session.java
> +    public Session(String title, LocalDate startDate, LocalDate endDate, Image sessionImage, boolean isFree, int maxEnrollment, int sessionFee) {
이 생성자는 왜 필요한걸까요 ?

2024-11-02 14:06 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/Session.java
> +            throw new IllegalStateException("수강 신청은 모집중인 상태에서만 가능하빈다.");
오타가 있네요!

2024-11-02 14:06 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/Session.java
> +        if (!isFree && enrollCount >= maxEnrollment) {
무료 강의는 얼리리턴을 하도록 하는 건 어떨까요 ?

2024-11-02 14:06 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/Session.java
> +    public void enroll() {
무료 강의에 대한 신청으로 만드신걸까요 ?
그렇다면 강의타입이 무료인지 검사하는 유효성검사가 있는게 더 좋을 것 같아요!

약간 무료/유료 강의 메서드를 아예 분리하는것도 괜찮을 것 같구요! 아예 추상화를 해보는 것도 방법일 것 같네요 :)

2024-11-03 09:54 UTC, yunji1201 commented on src/main/java/nextstep/courses/domain/Session.java
> +    public Session(String title, LocalDate startDate, LocalDate endDate, Image sessionImage, boolean isFree, int maxEnrollment, int sessionFee) {
오버로딩된 생성자를 통해 기본값을 쉽게 설정하려고 한거여서 테스트코드에서도 사용하고 있는데, 차라리 필요한 필드를 명시적으로 설정하는게 더 나을까요?

2024-11-03 11:35 UTC, yunji1201 commented
코네트 남겨주신 부분 모두 수정하려고 노력하였습니다. 
더 수정이 필요한 부분 말씀해주세요. 감사합니다!

2024-11-04 12:59 UTC, shared-moon approved these changes
윤지님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
코멘트를 좀 남겨 뒀는데, 다음 미션 진행 전 확인 부탁드려요!
고생 많으셨습니다 :)

2024-11-04 12:59 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/Image.java
> +        if (width < MINIMUM_WIDTH || height < MINIMUM_HEIGHT) {
👍

2024-11-04 12:59 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/Session.java
> +    protected void validateDate(LocalDate startDate, LocalDate endDate) {
요건 private이어도 되지 않을까요 ?

2024-11-04 12:59 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/Session.java
> +class FreeSession extends Session {
이너클래스 사용하신 이유가 있을까요 ?

2024-11-04 12:59 UTC, merged