Step2
next-step/java-lms pull request #625
Opened 2024-11-02 15:43 UTC by kkksusu161

수강신청 step2 
이번에 난이도를 느껴서 시간이 걸렸는데요!
많은 피드백 부탁드립니다. 감사합니다! 

* 어려웠던 점 
먼저 Session 에서 각 인스턴스변수들을  분리하고
무료강의 로직과 유료강의 로직이 더 있을 수 있고 필드도 다를테니 클래스 분리하는건 어떨까하고 
PaidSession / FreeSession 을 분리했습니다. 또한 다른 종류의 강의도 있을거라 가정하였습니다. 

공통은 Session 으로 두고 그러다보니 점점 꼬이게되었는데요. 
1. 공통 필드들은 Session에 있으므로 합성하려니 문제가 발생한다.
합성을 하려니 문제가 발생함 : 서비스에서 db를 등록할 때를 위해 팩토리패턴으로 SessionFactory 을 해야하는데 합성으로 하면 ReturnType은 Session이며, return 유료강의, return 무료강의로 리턴해야하는데 합성을 하면 못하게 됨, 인터페이스도 안됨 (필드존재)
 -> 상속 받아야만 한다. -> 그러나 상속은 좋지 않다고 들어서 혼란스러움 

2. 수강 신청한다, 강의들마다 규칙이 다르니 벨리데이션체크한다. -> SessionStrategy 를 만들게 됨 

그래서 public class PaidSession extends Session implements SessionStrategy {
이렇게 되어버리는 현상이 발생하였습니다.
이게 맞는 걸 까요?

2024-11-02 19:26 UTC, nooose commented
> 공통 필드들은 Session에 있으므로 합성하려니 문제가 발생
합성을 하려니 문제가 발생함 : 서비스에서 db를 등록할 때를 위해 팩토리패턴으로 SessionFactory 을 해야하는데 합성으로 하면 ReturnType은 Session이며, return 유료강의, return 무료강의로 리턴해야하는데 합성을 하면 못하게 됨, 인터페이스도 안됨 (필드존재)
-> 상속 받아야만 한다. -> 그러나 상속은 좋지 않다고 들어서 혼란스러움

상속보다 조합을 고려하라는 말을 많이 들어보셨던 것 같네요
상속이 좋지 않다고 하는 이유는 섣부른 상속이 나중에 발목을 잡게되는 경우가 많습니다.
큰 미래를 보지못하고 섣부르게 상속 구조로 설계하면 두번작업하는 일들이 많아질 수 있기 때문이에요.

지금 상황에서 조합을 택하면 무료, 유료가 다른 타입으로 생성될 것이고 중복 필드도 발생하게 되겠네요
인터페이스로 타입을 추상화시킬 수 있지만 이 방법도 섣부른 추상화 문제가 발생하게됩니다.

이번 미션에서는 상속을 택하든 단일 클래스에서 분기 처리를 하든 정답은 없습니다. 
초반에 어느정도 중복을 허용하다가 자리를 잡고 상속구조로 리팩토링을 해봐도 좋습니다.
이번 미션에서 경험하고 어떤 부분에서 상속이 좋고 나쁜지 경험해 보셨으면 합니다.

더 궁금한 부분은 질문으로 남겨주세요!

2024-11-02 19:30 UTC, nooose requested changes
안녕하세요 수연님
잘 구현하셨습니다 👍 
이번에 코멘트가 많은데요 확인 부탁드립니다!

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/CannotRegisteSessionException.java
> +public class CannotRegisteSessionException extends Exception {
커스텀 예외 👍

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/CannotRegisteSessionException.java
> +    private static final long serialVersionUID = 1L;
이 예외는 직렬화 대상인가요? 
설명 부탁드려도 될까요?

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/Course.java
> +    private Long id; //1기2기3기
주석없이 기수를 표현하는 필드를 선언해봐도 좋지 않을까요?

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/SessionInfo.java
> +    private long createId;
생성자의 ID라면 creatorId 가 좀 더 좋을 것 같네요!

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/SessionInfo.java
> +    private LocalDateTime applyEndDate;
시간 범위에 대한 체크도 이뤄지면 좋을 것 같네요
종료일이 시작일보다는 빠를 수 없는 것 처럼요

---

값 객체로도 표현이 가능할 것 같습니다!

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/Sessions.java
> +public class Sessions {
일급컬렉션 사용 시도는 좋은 것 같아요
그러나 List를 사용한 것과 비교해보면 어떠한 장점도 가지지 않는 상황 같네요
어떻게 생각하시나요?

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/StateCode.java
> +    private final int statusCode;
코드는 추후 DB 매핑을 위한 값일까요?

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/StateCode.java
> +    }
내부에서 예외를 던지는 구조네요
만약 수강신청이 불가능할 때 다른 예외를 던지고 싶거나,
해당 조건으로 로직을 작성해야할 때 예외를 캐치 후에 다시 예외를 던져야하는 번거로운 상황이 발생할 수 있습니다.

상태를 표현하는 타입이니 boolean을 리턴하는 상태 체크 메소드로 설계하면 어떨까싶어요

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/Students.java
> +        return false;
```java
중복검사(student);
students.add(student);
```

수강생 추가 시 중복이 불가능하게 막아도 되지않나요?

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/service/SessionService.java
> +    //추후 db로 변경 예정..
```suggestion
    // TODO: 추후 db로 변경 예정..
```
만약 intellij를 사용하고 계신다면 위와 같이 작성하는 것을 권장드려요
TODO, FIXME 같은 태그는 하이라이팅을 지원하고 
컴파일 시 warning으로 확인도 가능합니다!

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/Session.java
> +public class Session {
상속 구조로 잡으셨네요
그렇다면 abstract 클래스로 변경하면 어떨까요?

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/SessionStrategy.java
> +public interface SessionStrategy {
Session이라는 추상 클래스로 구현해야 할 메소드를 정의할 수 있었을 것 같아요
그런데도 SessionStrategy 인터페이스를 추가 구현한 이유가 궁금합니다.

인터페이스로 해당 메소드들만 작게 분리하고 싶으신 걸까요?

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/SessionImage.java
> +    private static List<String> list = new ArrayList<>(Arrays.asList("gif", "jpg", "jpeg", "png", "svg"));
변수 이름만으로 파악이 불가능할 것 같아요
어떤 리스트인지 구체적인 네이밍이 필요해 보입니다.

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/Session.java
> +    private StateCode stateCode;//이넘이니까 클래스로 받아도되네
코드를 보다보면 대화를 하는 것 같네요 😄

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/Session.java
> +    private long salePrice;
강의 금액이 long 단위까지 필요한지 고민하면 좋을 것 같아요

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/FreeSession.java
> +                       int fileSize, String type, int width, int height, String fileName) {
생성자에 인자가 너무 많은 것 같아요
만들어주신 SessionImage, SessionInfo을 인자로 받아도 좋을 것 같아요

그래도 필드가 너무 많다면 빌더패턴도 고민해 보면 좋겠네요! (무시하셔도 좋습니다)

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/FreeSession.java
> +    public void validateOrderSession(RequestOrderParam requestOrderParam) {
검증 메소드를 외부에서 호출하는 상황이 있나요?

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/SessionFactory.java
> +    //유료랑 무료 필드가 들어왔을때 계속해서 추가해야하나?
팩토리 클래스에 역할이 그런게 아닐까 싶어요 😄 

그런데  유료 세션, 무료 세션 요청 자체가 나뉠 수 있고, 요청 규격도 달라질 수 있습니다.
이러면 앞단에서 분기가 발생하여 Factory 클래스 없이도 각각 생성할 수 있는 구조가 될 수 있습니다. 
참고만 해주세요~

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/service/SessionService.java
> +        return new Sessions(sessions);
아직 서비스 유즈케이스까지는 제대로 고려하지 않은 상태인것 같습니다.
이런 부분들은 테스트 코드로 작성해 볼 수 있지 않을까요?

2024-11-02 19:30 UTC, nooose commented on src/main/java/nextstep/courses/domain/Session.java
> +    private boolean isPaid;
무료/유료가 아닌 다른 타입의 세션이 생길 수 있겠네요
확장성을 고려해 enum 타입을 필드로 가지면 어떨까요?

2024-11-03 09:56 UTC, kkksusu161 commented on src/main/java/nextstep/courses/CannotRegisteSessionException.java
> +    private static final long serialVersionUID = 1L;
직렬화 대상이 아닙니다 자동으로 인텔리J가 자동으로 만들었네요 삭제하겠습니다!

2024-11-03 12:18 UTC, nooose approved these changes
잘 구현하셨네요 👍 
도메인 모델들을 만들면서 클래스가 많아졌는데
다음 단계에서 패키지별로 정리하면 더 좋을 것 같네요
수고하셨습니다!

2024-11-03 12:18 UTC, nooose commented on src/main/java/nextstep/courses/domain/FreeSession.java
> +    private void validateRegistSession(long salePrice) {
무료강의라면 생성자에서 0으로 기본값 할당해도 좋겠네요
primitive 타입이라면 초기화하지 않아도 0으로 할당되나 명시하는 것이 좋을 것 같습니다.

2024-11-03 12:18 UTC, nooose commented on src/main/java/nextstep/courses/service/SessionService.java
> +    private SessionRepository sessionRepository;
현재는 의존성을 세터 주입해주는 방식이네요 
이러면 스프링이 아닌 환경에서 테스트할 때 주입하기가 어렵기 때문에
생성자 주입 방식을 사용하는 것이 좋을 것 같아요

객체 생성에 필요한 의존성을 명확하게 나타낼 수 있고 테스트하기 쉬운 구조를 유지할 수 있습니다.

2024-11-03 12:18 UTC, nooose commented on src/main/java/nextstep/courses/domain/SessionImage.java
> +    private static List<String> list = new ArrayList<>(Arrays.asList("gif", "jpg", "jpeg", "png", "svg"));
extensions 같은 네이밍이 좋지 않을까요?
클래스 변수로 관리되고 있으니 불변리스트에 불변변수로 만드는 것을 권장드려요
```java
private static final List<String> file_extensions = List.of("gif", "jpg", "jpeg", "png", "svg");
```

2024-11-03 12:18 UTC, merged