Step4 - 수강신청(요구사항 변경)
next-step/java-lms pull request #629
Opened 2024-11-03 14:20 UTC by BISohn27

안녕하세요 리뷰어님!

수강신청 4단계 리뷰 요청 드립니다.

최대한  스트랭글러 패턴을 따라해볼려고 노력했는데 쉽지가 않네요 😢 

혹시 아래의 요구 사항이 선발된 인원인지에 대한 판별할 수 있는 검증도 추가되어야 하는걸까요? 
현재는 수강 신청 요청한 사람에 대해서 승인을 하거나 거절하는 방식으로 구현한 상태인데 추가 구현이 필요한 것인지도 문의드립니다.
> 우아한테크코스(무료), 우아한테크캠프 Pro(유료)와 같이 선발된 인원만 수강 가능해야 한다.

리뷰 잘 부탁드립니다 🙇‍♂

2024-11-04 12:20 UTC, mskangg requested changes
4단계 구현 잘해주셨네요!
예외테스트까지 꼼꼼히 잘해주셨습니다.
몇가지 피드백 남겨드렸는데, 확인부탁드릴게요 🙇

2024-11-04 12:20 UTC, mskangg commented on src/main/java/nextstep/courses/domain/enrollment/Enrollment.java
> +    }
> 우아한테크코스(무료), 우아한테크캠프 Pro(유료)와 같이 선발된 인원만 수강 가능해야 한다.

위 요구사항처럼 검증을 해야할것 같아요 :)

1. 특정 강의
    - 수강신청 -> 선발 -> 승인
2. 모든 강의
    - 수강신청 -> 승인

선발에 대한 요구사항을 추가구현하면 될것 같습니다!

2024-11-04 12:20 UTC, mskangg commented on src/main/java/nextstep/courses/entity/CoverImageEntity.java
> +
```
    id bigint generated by default as identity,
    file_path varchar(200) not null,
    session_id bigint not null,
    primary key (id),
    FOREIGN KEY (session_id) REFERENCES session(id)
```

session_id  가 존재하지 않네요 🧐
엔티티와 도메인을 분리해주셨는데, 엔티티에 컬럼이 빠진것 같아요

2024-11-04 12:20 UTC, mskangg commented on src/main/java/nextstep/courses/entity/CourseEntity.java
> +    public static CourseEntity from(Course course) {
👍

2024-11-04 12:20 UTC, mskangg commented on src/main/java/nextstep/courses/entity/SessionEntity.java
> +    private List<CoverImageEntity> coverImageEntities;
엔티티면 테이블과 매칭되는 컬럼을 가지고있어야하지 않을까요?

2024-11-04 12:20 UTC, mskangg commented on src/main/java/nextstep/courses/infrastructure/session/JdbcSessionRepository.java
> +                .orElseThrow(() -> new IllegalStateException("강의 저장 실패"))
데이터베이스 예외인데, IllegalStateException 예외를 발생시키고 있네요 🧐

2024-11-04 12:20 UTC, mskangg commented on src/main/java/nextstep/courses/service/SessionService.java
> +        entity.addStudentEntities(studentRepository.findBySessionId(entity.getId()));
서로다른 repository 를 호출하여 관계를 매핑해주고 있군요 👍 
항상 세션을 호출할때마다 학생을 호출해야한다면, sessionRepository 구현체에서 studentRepository  인터페이스를 주입받아 호출하는것도 방법이 될것 같은데, 어떻게 생각하시나요? 🧐

2024-11-04 12:20 UTC, mskangg commented on src/test/java/nextstep/courses/domain/enrollment/EnrollmentTest.java
> +    }
예외테스트 👍

2024-11-04 12:42 UTC, BISohn27 commented on src/main/java/nextstep/courses/entity/CoverImageEntity.java
> +
session_id 추가하였습니다!

2024-11-04 13:04 UTC, BISohn27 commented on src/main/java/nextstep/courses/entity/SessionEntity.java
> +    private List<CoverImageEntity> coverImageEntities;
제가 이부분 이해를 잘 못해서 혹시 말씀해주신게 CoverImageEntity 클래스 내부에 실제로 매칭되는 session_id 칼럼 필드가 있어야 한다는 것일까요 아니면 List<CoverImageEntity> 보다는 List<Long> coverImageIds 로 엔티티가 아니라 엔티티를 조회할 수 있는 실제 칼럼 값이 좋다는 것일까요?

2024-11-04 14:32 UTC, mskangg commented on src/main/java/nextstep/courses/entity/SessionEntity.java
> +    private List<CoverImageEntity> coverImageEntities;
>  CoverImageEntity 클래스 내부에 실제로 매칭되는 session_id 칼럼 필드가 있어야 한다는 것일까요
👍 

도메인모델과 엔티티를 분리했으니, 엔티티는 테이블의 속성과 가깝게 매핑하는게 일반적입니다.
엔티티는 데이터베이스의 구조와 일관된 형태로 설계되어야 엔티티와 도메인을 분리한 의미가 있을것 같아요 :)

2024-11-04 14:33 UTC, BISohn27 commented on src/main/java/nextstep/courses/domain/enrollment/Enrollment.java
> +    }
추가 구현했습니다!

2024-11-04 14:34 UTC, BISohn27 commented on src/main/java/nextstep/courses/entity/CoverImageEntity.java
> +
엔티티에 추가했습니다!

2024-11-04 14:36 UTC, BISohn27 commented on src/main/java/nextstep/courses/infrastructure/session/JdbcSessionRepository.java
> +                .orElseThrow(() -> new IllegalStateException("강의 저장 실패"))
Spring Data 계열을 사용하고 있어서 IllegalStateException 대신 DataAccessException 계열로 변경하였는데 사용자 정의 예외를 따로 정의하지 않아도 괜찮겠죠?

2024-11-04 14:38 UTC, BISohn27 commented on src/main/java/nextstep/courses/service/SessionService.java
> +        entity.addStudentEntities(studentRepository.findBySessionId(entity.getId()));
CoverImageRepository 는 SessionRepository 에서 직접 사용하고 있어서 말씀해주신대로 StudentEntity도 SessionRepository 에서 직접 호출하는 것으로 변경했습니다.

2024-11-04 14:39 UTC, BISohn27 commented on src/main/java/nextstep/courses/entity/SessionEntity.java
> +    private List<CoverImageEntity> coverImageEntities;
> 엔티티면 테이블과 매칭되는 컬럼을 가지고있어야하지 않을까요?

다른 피드백 주신 내용은 변경해서 구현했는데 위 피드백 내용은 제가 이해를 잘 못해서 혹시 말씀해주신게 CoverImageEntity 클래스 내부에 실제로 매칭되는 session_id 칼럼 필드가 있어야 한다는 것일까요 아니면 List<CoverImageEntity> 보다는 List<Long> coverImageIds 로 엔티티가 아니라 엔티티를 조회할 수 있는 실제 칼럼 값이 좋다는 것일까요?

2024-11-04 14:42 UTC, BISohn27 commented on src/main/java/nextstep/courses/entity/SessionEntity.java
> +    private List<CoverImageEntity> coverImageEntities;
아 감사합니다. 엔티티와 도메인을 분리하면 엔티티는 최대한 데이터베이스에 가깝게 설계되는게 좋은 설계라 볼 수 있군요 😄

2024-11-04 14:42 UTC, BISohn27 commented
리뷰어님 리뷰 요청 다시 드립니다 🙇‍♂

2024-11-05 08:46 UTC, mskangg approved these changes
피드백 반영 잘해주셨네요! 👍👏
마지막 미션까지 고생 많으셨어요! 🚀

과정을 시작하기 전과 지금을 비교해 보면 많은 변화가 있었을 거라 생각합니다. 
당장은 현업에 바로 적용하기 어려울 수 있지만, 미션에서 보여준 열정처럼 실무에서도 계속 열심히 하신다면 충분히 적용할 수 있을 거라 믿어요. 
응원하겠습니다! 🫡

그럼 정말 수고 많으셨고, 이 미션은 머지하겠습니다. :)

2024-11-05 08:46 UTC, mskangg commented on src/main/java/nextstep/courses/domain/enrollment/Enrollment.java
> +    }
👍

2024-11-05 08:46 UTC, mskangg commented on src/main/java/nextstep/courses/entity/CoverImageEntity.java
> +    private final String sessionId;
👍

2024-11-05 08:46 UTC, mskangg commented on src/main/resources/schema.sql
> +create table student (
👍

2024-11-05 08:46 UTC, merged