4단계 - 수강신청
next-step/java-lms pull request #633
Opened 2024-11-04 02:38 UTC by skdev0619

안녕하세요 리뷰어님
코드 리뷰 잘 부탁드립니다!!

2024-11-04 14:27 UTC, seondongpyo requested changes
마지막 단계도 잘 진행해주셨네요 👍 
몇 가지 코멘트 드렸는데 확인 후 다시 리뷰 요청을 부탁 드리겠습니다 🔥

2024-11-04 14:27 UTC, seondongpyo commented on src/main/java/nextstep/courses/domain/Session.java
> +        }
이 부분은 추가해주신 이유가 있으실까요?

2024-11-04 14:27 UTC, seondongpyo commented on src/main/java/nextstep/courses/domain/Status.java
> +    private final boolean recruitFlag;
위의 `ProgressStatus`처럼 '모집 상태'를 나타내는 열거형 타입을 하나 추가해봐도 좋을 것 같습니다.

2024-11-04 14:27 UTC, seondongpyo commented on src/main/java/nextstep/courses/service/EnrollmentService.java
>          sessionUsersRepository.bulkSave(users);
`List`로 만들어서 저장하는 대신에 `SessionStudent` 단일 객체로 저장해도 되지 않을까요?
```suggestion
        SessionStudent student = new SessionStudent(session.getId(), loginUser.getId());
        sessionUsersRepository.save(student);
```

2024-11-04 14:27 UTC, seondongpyo commented on src/main/java/nextstep/users/domain/NsUser.java
> +    private boolean selectedFlag;
'선발 여부'는 일반적인 사용자보다는 특정 강의에 수강을 신청한 '수강생'인 경우에만 의미가 있을 것 같은데요,
`NsUser` 대신에 `SessionStudent`에 추가해보는 건 어떻게 생각하시나요?

2024-11-04 14:27 UTC, seondongpyo commented on src/main/java/nextstep/courses/service/EnrollmentService.java
다음 요구사항에 대한 비즈니스 로직도 추가해보면 어떨까요?
> - 강사는 수강신청한 사람 중 선발된 인원에 대해서만 수강 승인이 가능해야 한다.
> - 강사는 수강신청한 사람 중 선발되지 않은 사람은 수강을 취소할 수 있어야 한다.

2024-11-05 02:44 UTC, skdev0619 commented
피드백 주신 내용 반영했습니다. 확인 부탁드립니다!!

2024-11-05 02:44 UTC, skdev0619 commented on src/main/java/nextstep/courses/domain/Session.java
> +        }
깨진 테스트로 인해서 임시로 추가해놓았던 로직을 지우지 않았습니다;;
제거하도록 하겠습니다

2024-11-05 11:56 UTC, seondongpyo requested changes
피드백 잘 반영해주셨네요 👍 
조금 더 개선해보면 좋을 것 같아서 추가로 몇 가지 코멘트 드렸습니다.
조금만 더 힘내주세요 🔥

2024-11-05 11:56 UTC, seondongpyo commented on src/main/java/nextstep/courses/domain/SessionStudents.java
>  import static java.util.stream.Collectors.toList;
사용하지 않는 import들은 제거해주시면 좋을 것 같습니다.

2024-11-05 11:56 UTC, seondongpyo commented on src/main/java/nextstep/courses/domain/SessionStudents.java
> +    private List<SessionStudent> approvedStudents = new ArrayList<>();
선발된 수강생들만을 관리하는 List를 따로 만들어주신 이유가 있으실까요?
선발 여부와 상관 없이 하나의 List로 수강생을 관리해도 충분하지 않을까란 생각이 듭니다.

2024-11-05 11:56 UTC, seondongpyo commented on src/main/java/nextstep/courses/service/EnrollmentService.java
이전에 드렸던 코멘트를 참고해주세요. https://github.com/next-step/java-lms/pull/633#discussion_r1827820744
도메인 객체의 상태가 바뀌었다면 이를 최종적으로는 데이터베이스에도 반영을 해야 하니,
`EnrollmentService`에도 관련된 서비스 로직을 추가해보시면 좋을 것 같습니다.

2024-11-05 11:56 UTC, seondongpyo commented on src/main/java/nextstep/courses/domain/SessionStudents.java
> +        if(student.isSelected()){
IDE로 IntellIJ IDEA를 사용 중이시라면, 자동 포맷팅 단축키를 활용해보시는 걸 권장 드립니다.
(운영체제가 Windows라면 `Ctrl + Alt + L`, Mac이라면 `Cmd + Option + L`)
```suggestion
        if (student.isSelected()) {
```

2024-11-06 02:31 UTC, skdev0619 commented on src/main/java/nextstep/courses/domain/SessionStudents.java
> +    private List<SessionStudent> approvedStudents = new ArrayList<>();
수강생 리스트를 루프 돌면서 remove 하면 ConcurrentModificationException이 발생해서
수강생 리스트를 직접 remove 하지 않고 승인된 수강생 목록만 관리하는 approvedStudents를 생성했습니다

2024-11-06 02:49 UTC, skdev0619 commented
피드백 주신 내용 반영했습니다. 확인 부탁드립니다!!

기존에는 수강 승인/취소 메소드를 각각 분리했지만
하나의 메소드에서 수강 승인/취소 처리하도록 변경했습니다.

2024-11-06 11:50 UTC, seondongpyo approved these changes
피드백 잘 반영해주셨네요 👍 
수강신청 미션은 여기서 마무리하도록 하겠습니다.
그동안 미션 진행하시느라 고생 많으셨습니다, 완주 축하드려요 👏

2024-11-06 11:50 UTC, merged