Step3 : 수강신청(DB 적용)
next-step/java-lms pull request #637
Opened 2024-11-04 12:29 UTC by hanseu9839

안녕하세요. 리뷰어님 항상 좋은 리뷰해주셔서 감사합니다..! 

몇 가지 궁금한 점이 있어서 질문 남깁니다..! 

1. 아래와 같은 코드로 작성하였는데 도메인 객체에서 참조할 때, getter를 두번 가져와야하는데 괜찮은걸까요? 
`
jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(sql, new String[] {"id"});
            ps.setLong(1, sessionCoverImage.getSessionId());
            ps.setString(2, sessionCoverImage.getFileName());
            ps.setInt(3, sessionCoverImage.getCoverImageVolume().getSize());
            ps.setString(4, sessionCoverImage.getCoverImageExtensionType().getExtension());
            ps.setInt(5, sessionCoverImage.getCoverImageFileSize().getHeight());
            ps.setInt(6, sessionCoverImage.getCoverImageFileSize().getWidth());
            ps.setString(7, sessionCoverImage.getFilePath());
            return ps;
        }, keyHolder);
`
2.  JPA로 만약 사용한다고 가정하였을 때, 도메인 객체를 Entity로 사용한다면 일급컬렉션, 도메인 객체를 참조하는 값은 어떤 방법으로 저장해야하는지 궁금합니다..!

2024-11-06 11:57 UTC, catsbi requested changes
오리님 3단계 미션 잘 구현해줬습니다 👍 

몇 가지 추가적으로 고민해보면 좋을 부분들 피드백 남겨드렸으니 확인 후 다시 리뷰요청 부탁드려요!

2024-11-06 11:57 UTC, catsbi commented on src/main/java/nextstep/courses/domain/port/EnrollUserInfoRepository.java
> +public interface EnrollUserInfoRepository {
인터페이스 추상화를 잘 해주셨네요 👍

2024-11-06 11:57 UTC, catsbi commented on src/main/java/nextstep/courses/infrastructure/JdbcEnrollUserInfoRepository.java
> +        );
RowMapper는 재사용성이 높아보이는데, 지역변수보단 한단게 더 올려도 되지 않을까요?!

2024-11-06 11:57 UTC, catsbi commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionCoverImageRepository.java
> +            ps.setInt(3, sessionCoverImage.getCoverImageVolume().getSize());
```suggestion
            ps.setInt(3, sessionCoverImage.getCoverImageVolumeSize()); 
```

 이런식으로 dot(.)을 줄여봐도 좋을 것 같아요. 외부에서 A라는 객체에서 c~d까지 직접 찾아가는건 중간에 있는 b~c등의 엔티티에 대한 커플링을 높혀 유지보수성을 떨어트리기도하고 디미터 법칙도 위배할 수 있으니까요 ㅎㅎ

2024-11-06 11:57 UTC, catsbi commented on src/main/java/nextstep/courses/service/SessionService.java
> +                .build();
변수가 많아도 빌더패턴을 활용하니 어떤 변수에 어떤 값이 할당되는지 파악하기가 쉽네요 ㅎㅎ

2024-11-06 11:57 UTC, catsbi commented on src/main/java/nextstep/courses/service/SessionService.java
> +                .endDateTime(LocalDateTime.now().plusMonths(3))
now()가 각각 호출되기보단 지역변수로 할당해서 재사용해도 되지 않을까요?
startDateTime()함수 호출 이후 endDateTime()실행 시점에 서버에 블락이슈가 생기면서 오차가 생길수도 있을 것 같네요

2024-11-06 11:57 UTC, catsbi commented on src/main/java/nextstep/courses/service/SessionService.java
> +        Session session = new Session.SessionBuilder()
이런 경우 dto(변화가 많은 곳) 에서 domain(변화가 적은 곳)으로 의존성의 흐름이 흐르는건 문제가 되지 않기에 다음과 같이 책임을 위임시킬수도 있습니다. 

```java
Session session = dto.toEntity();
```

그리고 dto중 entity화 될 수 있는 객체는 EntityProvider등으로 믹스인 인터페이스를 선언해서 사용할수도 있고 그럼 더욱 추상화가 될 수도 있겠죠 ㅎㅎ

2024-11-06 11:57 UTC, catsbi commented on src/main/java/nextstep/courses/domain/dto/EnrollDto.java
> +    private Long price;
최초 객체 생성 후 변경이 없다면 final을 만들어 불변객체로 만들어도 되겠네요 ㅎㅎ

2024-11-06 11:57 UTC, catsbi commented on src/main/java/nextstep/courses/domain/dto/SessionDto.java
> +    public SessionDto(Long sessionId, String fileName, int height, int width, int volume, Long price, SessionPriceType sessionPriceType, SessionStatus sessionStatus, String filePath) {
4개 이상의 매개변수가 있고 동일한 타입이 연달아 있는 함수 혹은 생성자의 경우 휴먼에러로 인해 컴파일에러도 런타임에러도 아닌 상태로 잘못된 상태가 저장되는 문제가 생길 수 있어 빌더패턴이나 정적 팩토리 메서드패턴등의 디자인패턴등이 권장됩니다. ㅎㅎ

2024-11-06 11:57 UTC, catsbi commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionRepository.java
> +                .build()
이건 필수는 아니고 심화 피드백인데, RowMapper를 Entity 마다 맞춰서 생성해주는건 피곤하고 번거로운 작업이 될 것 같아요. 
RowMapper는 FunctionalInterface니 이를 구현하여 여러 엔티티에 제네릭타입으로 적절히 매핑해줄 수 있는 구현체를 만들어서 사용해도 좋을 것 같네요 ㅎㅎ
```suggestion
       RowMapper<Session> rowMapper = CustomRowMapper.create(Session.class);
       ...
       
       
       return jdbcTemplate.queryForObject(sql, rowMapper, id);
```

2024-11-06 11:57 UTC, catsbi commented on src/main/java/nextstep/courses/service/SessionService.java
> +    @Transactional(readOnly = true)
모든 메서드에 Transactional을 달아줘야하는건 너무 번거로울 것 같아요. 

전체적으로 많이 사용되는 속성의 Transactional 애노테이션을 클래스 레벨로 올리고, 함수 중 별도의 속성(ex: readOnly)을 사용하는 곳에만 Transactional을 별도로 붙혀줘도 되지 않을까요?

2024-11-06 14:34 UTC, hanseu9839 commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionCoverImageRepository.java
> +            ps.setInt(3, sessionCoverImage.getCoverImageVolume().getSize());
넵 좋은거 같아요..!

2024-11-06 14:39 UTC, hanseu9839 commented on src/main/java/nextstep/courses/service/SessionService.java
> +                .endDateTime(LocalDateTime.now().plusMonths(3))
넵 좋은거 같습니다..!

2024-11-07 05:52 UTC, hanseu9839 commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionRepository.java
> +                .build()
제네릭이랑, 리플렉션을 사용하여 구현하려고 했는데, 해당 부분이 컬럼 Name sessiond_id 같은 값들이 있어서 완전히 일치해야 사용가능하다고 해서 조금 더 고민해보겠습니다..!

2024-11-07 05:53 UTC, hanseu9839 commented on src/main/java/nextstep/courses/service/SessionService.java
> +    @Transactional(readOnly = true)
넵!

2024-11-07 14:17 UTC, catsbi approved these changes
오리님 3단계 미션 피드백 반영 잘 해주셨어요 👍 

몇 가지 코멘트 더 남겨드렸는데 심화 코멘트이기도 하니 참고하셔서 여유가 되신다면 다음 미션에서 같이 반영해보는걸로 해요. 

3단계는 머지하도록 하겠습니다!

2024-11-07 14:17 UTC, catsbi commented on src/main/java/nextstep/courses/domain/dto/EnrollDto.java
> +    private final Long price;
피드백 반영 👍

2024-11-07 14:17 UTC, catsbi commented on src/main/java/nextstep/courses/domain/dto/SessionDto.java
> +    public Session toModel() {
믹스인 인터페이스(Ex: Comparable, Serializable, ..)등을 이용해 인터페이스 정의 및 구현을 통해 이런 toModel 행위들을 추상화 할 수 있고 그럼, 서비스같은 컴포넌트들은 dto 구현체가 아닌 ModelSupplier같은 인터페이스를 의존하게 되며 구현체가 아닌 추상화에 의존한다 라는 SOLID원칙 중 DIP 원칙을 지킬 수 있게되니 참고해보면 좋을 것 같아요

2024-11-07 14:17 UTC, merged

2024-11-07 15:04 UTC, hanseu9839 commented on src/main/java/nextstep/courses/domain/dto/SessionDto.java
> +    public Session toModel() {
이부분에 대해서 항상 고민이 많았는데 해결된거 같습니다 적용해보겠습니다..!