Step4 commit
next-step/java-lms pull request #657
Opened 2024-11-13 09:06 UTC by Ryumina-edu

마지막 step도 잘 부탁드립니다!!! 🙇 🙇

2024-11-15 03:00 UTC, testrace requested changes
안녕하세요 미나님 😃 
4단계 잘 구현해 주셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 다시 리뷰 요청해 주세요.

2024-11-15 03:00 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/StudentRepository.java
> +    void cancel(long sessionId, long userId);
repository에서 select 라는 메서드명은 조회 기능으로 인식할 수 있을 것 같은데요
'select', 'cancel' 이라는 이름은 도메인영역에서 조금 더 어울리지 않나 싶어요.
repository의 역할에 맞게 save 같은 이름으로 변경하면 어떨까요?

2024-11-15 03:00 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/enrollment/FreeEnrollment.java
> +        if (!status.isRecruit() || enrollmentStatus.isImPossible()) {
모집 상태는 분리되었으니 진행 상태에 맞는 이름으로 변경하면 어떨까요?
```suggestion
        if (!status.진행중() || enrollmentStatus.isImPossible()) {
```

2024-11-15 03:00 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/sessioncoverimage/SessionCoverImageRepository.java
> +    SessionCoverImage findById(long coverImageId);
Optional 타입으로 반환해도 좋을 것 같아요

2024-11-15 03:00 UTC, testrace commented on src/main/java/nextstep/courses/service/SessionService.java
> +    }
수강신청 로직처럼 선발 과정은 도메인 로직으로 처리하고 그 결과를 저장하면 어떨까요?
```java
        Student student = studentRepository.find...(...);
        student.select();
        studentRepository.save(student);
```

2024-11-15 03:00 UTC, testrace commented on src/main/resources/schema.sql
> +    enrollment_status VARCHAR(30) not null,
> 프로그래밍 요구사항
>DB 테이블에 데이터가 존재한다는 가정하에 리팩터링해야 한다.
즉, 기존에 쌓인 데이터를 제거하지 않은 상태로 리팩터링 해야 한다.

새롭게 추가된 모든 컬럼이 not null 제약이 존재하네요.
커밋 로그를 보니 기존 데이터가 있다는 가정을 누락하신 것 같아요 😢 
default 값을 추가하거나, null을 허용한 뒤에 적절한 조치를 취하면 어떨까요?

2024-11-15 03:00 UTC, testrace commented on src/main/resources/schema.sql
> +    selected boolean not null,
선발보다는 승인과 관련된 네이밍은 어떨까요?

2024-11-22 07:08 UTC, Ryumina-edu commented
최근에 일이 조금 바빠져서 리뷰 요청이 늦어진 점 죄송합니다!
남은 리뷰도 잘 부탁드립니다 😄 👍

2024-11-24 04:35 UTC, testrace approved these changes
안녕하세요 미나님 😃 
피드백 반영 잘해주셨네요 👍 
수강신청 미션은 여기서 마무리 하도록 하겠습니다.
그 동안 고생 많으셨습니다!

2024-11-24 04:35 UTC, testrace commented on src/main/java/nextstep/courses/domain/session/enrollment/Students.java
> +            throw new NoSuchElementException("[id:" + nonExistStudent.get() + "] 존재하지 않는 수강생입니다.");
유효성을 검증과 더불어 상태를 직접 변경하는 구조도 고려해 보시면 좋을 것 같아요

2024-11-24 04:35 UTC, testrace commented on src/main/java/nextstep/courses/service/SessionService.java
> +        studentRepository.updateDisapproved(sessionId, userId);
승인취소 기능도 도메인 객체로 로직을 수행한 후 저장해도 좋을 것 같아요

2024-11-24 04:35 UTC, testrace commented on src/main/resources/schema.sql
> +    approval_status VARCHAR(30) default 'DISAPPROVED',
기본 값을 추가해주셨네요 👍

2024-11-24 04:35 UTC, merged