Step2
next-step/java-lms pull request #68
Opened 2023-05-24 14:17 UTC by jadenChoo

수강 신청 기능 요구사항을 나름대로 반영하긴 했는데 step2에서 요구하는 수정방향이 이 방향이 맞는지가 조금 애매합니다.
혹시 다른 방향으로 수정해야한다면 말씀바랍니다.

2023-05-24 14:54 UTC, shared-moon requested changes
안녕하세요!
2단계 미션 진행 중 요구사항이 안 맞는 부분이 있어 확인 후 리뷰 재요청 부탁드려요 :)

2023-05-24 14:54 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/Course.java
> +    private LocalDateTime startedAt;
>과정(Course)은 기수 단위로 여러 개의 강의(Session)를 가질 수 있다.

이런 요구사항이 있습니다. Session이라는 도메인을 새로 만드셔야 할 것 같아요 :)

2023-05-26 13:49 UTC, jadenChoo commented on src/main/java/nextstep/courses/domain/Course.java
> +    private LocalDateTime startedAt;
오.. 요구사항을 놓쳤었군요.

2023-05-27 01:05 UTC, shared-moon approved these changes
안녕하세요!
2단계 미션 잘 진행 해 주셨네요 :)
코멘트를 좀 남겨 두었는데, 확인 후 다음 미션 진행 해 주세요!
고생 많으셨습니다 :)

2023-05-27 01:05 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/Session.java
> +        if (currentStudents > maxStudents) {
해당 조건을 체크할 수 있는 메서드가 밑에 있는 것 같아요 ?

2023-05-27 01:05 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/Status.java
> +    preparing, opening, ended
enum의 요소들은 대문자로 써주시는게 좋아요, 상수 선언처럼요 :)

2023-05-27 01:05 UTC, shared-moon commented on src/test/java/nextstep/courses/domain/CourseTest.java
> +    @Test
테스트에는 `@DisplayName`으로 설명을 적어주는 걸 추천드려요

2023-05-27 01:05 UTC, shared-moon commented on src/main/java/nextstep/courses/domain/Session.java
> +    public void patchStatus(String status) {
입력 파라미터를 Status로 해주시는 게 좋을 것 같아요 :)

2023-05-27 01:05 UTC, merged

2023-05-28 04:26 UTC, jadenChoo commented on src/main/java/nextstep/courses/domain/Session.java
> +    public Session() {
지금보니 테스트할때만 사용하고있네요. 제거할게요