feat: Step2 - 수강신청(도메인모델)
next-step/java-lms pull request #70
Opened 2023-05-24 14:53 UTC by biblekimm

수강신청 2단계 PR 드립니다.

2023-05-25 09:30 UTC, nokchax requested changes
안녕하세요, 성경님!
수강신청 도메인 설계 구현 고생 많으셨습니다.
피드백 남겼으니 확인 부탁드려요 🙇

2023-05-25 09:30 UTC, nokchax commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +        }).isInstanceOf(RuntimeException.class);
RuntimeException 으로 확인하면 정말 의도한 예외가 발생했는지 알기 힘들지 않을까요?
정확히 예상한 예외가 맞는지 테스트할 필요가 있어보여요

2023-05-25 09:30 UTC, nokchax commented on src/main/java/nextstep/courses/domain/Session.java
> +    private LocalDateTime endDate;
시작일은 종료일을 넘어갈 수 없다 등의 조건도 있지 않을까요?

2023-05-25 09:30 UTC, nokchax commented on src/main/java/nextstep/courses/domain/Session.java
> +    private int maximumNumberOfStudents;
시작일 종료일과 마찬가지고, 이쪽도 서로 연관되어 있는 필드네요

2023-05-25 09:30 UTC, nokchax commented on src/main/java/nextstep/courses/domain/Session.java
> +    private LocalDateTime updatedAt;
createdAt과 updatedAt는 여러 도메인에 사용되고 있는데요, 이를 추출하여 상속하여 쓰면 어떨까요?

2023-05-25 09:30 UTC, nokchax commented on src/main/java/nextstep/courses/domain/Session.java
> +    Session(int id, String title, SessionStatusType statusType, int maximumNumberOfStudents) {
세션을 생성하면 해당 세션의 상태는 기본적으로 준비중 아닐까요?

2023-05-25 09:30 UTC, nokchax commented on src/main/java/nextstep/courses/domain/Session.java
> +    public int register() {
등록을 어느 사람이 하는지 알 수 없네요, 등록을 하기 위해선 유저가 필요하지 않을까요?

2023-05-25 09:30 UTC, nokchax commented on src/main/java/nextstep/courses/domain/Session.java
> +            throw new RuntimeException("정원이 초과되어 신청하실 수 없습니다.");
RuntimeException 은 지나치게 포괄적인 의미를 지닌 예외입니다.
적절한 예외를 찾아 던져주거나, 새로운 예외를 정의해보세요~!

2023-05-25 09:30 UTC, nokchax commented on src/main/java/nextstep/courses/domain/Session.java
> +        if (statusType != SessionStatusType.RECRUITING) {
값을 비교하지 말고 statusType에게 물어보면 어떨까요? 
예를 들면 아래와 같겠네요
```
 statusType.canRegister()
```

2023-05-25 09:30 UTC, nokchax commented on src/main/java/nextstep/courses/domain/Sessions.java
> +}
Sessions 를 래핑하여 얻는 이득이 있을까요?

2023-05-26 23:19 UTC, biblekimm commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +class SessionTest {
실패 케이스 추가해보았습니다. 확인 부탁드립니다.

2023-05-26 23:19 UTC, biblekimm commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +        }).isInstanceOf(RuntimeException.class);
구체적인 Exception으로 정의했습니다. 감사합니다.

2023-05-26 23:19 UTC, biblekimm commented on src/main/java/nextstep/courses/domain/Course.java
> +    private Sessions sessions;
세션 추가하는 메서드 구현했습니다. 감사합니다.

2023-05-26 23:20 UTC, biblekimm commented on src/main/java/nextstep/courses/domain/Session.java
> +public class Session {
관련 있는 필드들 객체로 추출해보았습니다. 확인 부탁드립니다.

2023-05-26 23:20 UTC, biblekimm commented on src/main/java/nextstep/courses/domain/Session.java
> +    private LocalDateTime endDate;
validation 추가 했습니다. 감사합니다.

2023-05-26 23:20 UTC, biblekimm commented on src/main/java/nextstep/courses/domain/Session.java
> +    private String chargeYN;
ENUM으로 추출했습니다. 감사합니다.

2023-05-26 23:21 UTC, biblekimm commented on src/main/java/nextstep/courses/domain/Session.java
> +    private String coverImageUrl;
래핑하여 검증 로직 추가했습니다. 감사합니다.

2023-05-26 23:21 UTC, biblekimm commented on src/main/java/nextstep/courses/domain/Session.java
> +    private LocalDateTime updatedAt;
controlField 추출했습니다. 감사합니다.

2023-05-26 23:22 UTC, biblekimm commented on src/main/java/nextstep/courses/domain/Session.java
> +    Session(int id, String title, SessionStatusType statusType, int maximumNumberOfStudents) {
생성자를 통해서 기본값 중비중으로 세팅할 수 있게 구현해보았습니다. 확인 부탁드립니다.

2023-05-26 23:22 UTC, biblekimm commented on src/main/java/nextstep/courses/domain/Session.java
> +    public int register() {
유저 정보 받아서 등록할 수 있게 수정했습니다. 감사합니다.

2023-05-26 23:24 UTC, biblekimm commented on src/main/java/nextstep/courses/domain/Session.java
> +            throw new RuntimeException("정원이 초과되어 신청하실 수 없습니다.");
구체적인 예외로 정의했습니다. 감사합니다.

2023-05-26 23:25 UTC, biblekimm commented on src/main/java/nextstep/courses/domain/Session.java
> +        if (statusType != SessionStatusType.RECRUITING) {
반영했습니다. 감사합니다.

2023-05-26 23:26 UTC, biblekimm commented on src/main/java/nextstep/courses/domain/Sessions.java
> +}
Session들을 대상으로 확인이나 비교할 정보가 있을때, 예를들면 무료/유료 강의 수 같은 Session들의 통계를 내볼 때 활용할 수 있을 것 같습니다. 그런데 현재의 요구사항에서는 활용할 일이 없어 보이긴 합니다. 그렇다면 굳이 래핑할 필요가 없을까요?

2023-05-27 14:41 UTC, nokchax commented on src/main/java/nextstep/courses/domain/Sessions.java
> +}
사람에 따라 오버엔지니어링으로 보시는 분들이 계십니다.
저는 미리미리 해두는 편이지만, 생각해 보셨으면 좋을 것 같아 코멘트 남겼었어요

2023-05-27 14:59 UTC, nokchax approved these changes
안녕하세요, 성경님!
피드백 잘 적용해 주셨습니다.
테스트도 꼼꼼히 잘 짜주셨네요 👍 
이번 단계는 이만 머지할게요 다음 단계 진행해주세요 🙇

2023-05-27 14:59 UTC, merged