[수강신청 미션 Step1]
next-step/java-lms pull request #79
Opened 2023-05-25 13:28 UTC by woonys

안녕하세요, 수강 신청 미션1 리뷰 요청드립니다.

2023-05-27 03:13 UTC, dave915 requested changes
재운님 안녕하세요! 1단계 구현 잘 해주셨네요 👍 
몇가지 피드백 남겼습니다. 확인 부탁드릴게요 :)

2023-05-27 03:13 UTC, dave915 commented on src/main/java/nextstep/qna/service/QnAService.java
> +        question.ensureAllAnswersOwnedByUser(loginUser);
question 을 삭제 할 수 있는지 검증 하는 메소드들 같은데요!
막상 question.delete 내부에서는 검증 로직이 없네요 😭

만약 다른 개발자가 question 을 삭제하는 로직을 구현하려고 할때 deleted 만 호출하는 실수를 할 수 있을 것 같아요.

2023-05-27 03:13 UTC, dave915 commented on src/main/java/nextstep/qna/service/QnAService.java
> +        question.deleteHistoriesFromAnswers(deleteHistories);
질문을 전체 삭제하려면 
question.delete();
question.deleteHistoriesFromAnswers(deleteHistories);
이렇게 두 메소드를 호출 해야하는데요. 

question.delete(); 만 호출해서 삭제 되게 하면 어떨까요? 
Answers를 삭제하지 못하면 Question도 삭제하지 못하니까요 🤔

2023-05-27 03:13 UTC, dave915 commented on src/test/java/nextstep/qna/domain/QuestionTest.java
> +    public void shouldThrowCannotDeleteException_ifOwnerIsNotLoginUser() {
@DisplayName 을 사용해서 테스트 내용을 설명해주면 더 좋을 것 같아요 :)

2023-05-29 11:17 UTC, woonys commented on src/main/java/nextstep/qna/service/QnAService.java
> +        question.ensureAllAnswersOwnedByUser(loginUser);
피드백 감사합니다 :) 서비스 레이어에 있던 검증 로직을 question.delete() 내부로 이관했습니다.

2023-05-29 11:17 UTC, woonys commented on src/main/java/nextstep/qna/service/QnAService.java
> +        question.deleteHistoriesFromAnswers(deleteHistories);
@dave915 피드백 감사합니다 :) 마찬가지로 deleteHistoriesFromAnswers(deleteHistories) 로직을 delete() 내부로 이관했습니다.

2023-05-29 11:18 UTC, woonys commented on src/test/java/nextstep/qna/domain/QuestionTest.java
> +    public void shouldThrowCannotDeleteException_ifOwnerIsNotLoginUser() {
@dave915 피드백 감사합니다. 해당 내용 추가했습니다.

2023-05-29 23:55 UTC, javajigi approved these changes
피드백 반영 넘 잘 했네요. 💯 
추가로 피드백할 부분도 보이지 않고, 다음 단계를 경험해 봤으면 하는 바람으로 제가 대신 merge해요.

2023-05-29 23:55 UTC, merged