Step2 - 수강신청(도메인 모델)
next-step/java-lms pull request #8
Opened 2023-05-17 14:30 UTC by oneny

자동차 경주, 로또, 사다리 미션처럼 먼저 도메인 모델을 했는데 Course에 Sessions 객체를 추가하는 것까지 하는 것이 맞나 싶습니다..ㅎㅎㅎ

지금까지 배웠던 래퍼 클래스를 많이 활용해봤는데 피드백 주시면 적극 반영하겠습니다! 감사합니다! :)

2023-05-18 14:40 UTC, mskangg requested changes
2단계 미션도 잘 구현해주셨네요!

> 지금까지 배웠던 래퍼 클래스를 많이 활용해봤는데 피드백 주시면 적극 반영하겠습니다! 감사합니다! :)

래퍼 클래스를 만드시려고 약간의 오버엔지니어링을 한것처럼 보이는데, 도움 될 만한 몇가지 피드백 드렸습니다!
개발엔 정답이 없으니 고민하신 내용 적어주시면 감사하겠습니다 🙇

2023-05-18 14:40 UTC, mskangg commented on src/main/java/nextstep/courses/domain/Session.java
> +    sessionStatus.validateAcceptingStatus();
`validateAcceptingStatus` 메서드명으로만 보면 AcceptingStatus 를 검증하는 메서드로 보여요! (상태가 잘못됐는지 확인하는 의도로 보여짐)
이런 접근방식도 좋지만, `validate`같은 메서드는 객체를 생성할 때 보통 사용합니당

```suggestion
    if(!sessionStatus.canEnroll()){
        throw new IllegalArgumentException();
    }
```

`Session`의 강의 상태는 수강 신청할수 없니? -> 예외
이런 방식으로 접근해보시는건 어떠신가요?

물론 재원님이 틀렸다는것은 절대 아닙니다! 😄 
다양한 접근방법이 있다는 리뷰를 드리고 싶었어용

2023-05-20 05:22 UTC, oneny commented
말씀해주신대로 NextStepUsers에 validateUserEnrollment를 피드백 주신대로 리팩토링하던 중 이 메서드를 private으로 만들고 여기서 maxUserEnrollment를 관리하면 Session에서 관리하는 책임을 나눌 수 있지 않을까 생각해서 추가로 다시 리팩토링해봤습니다.

그 뒤로 좀 더 보니 비슷한
```java
this.startDate = new SessionDate(startDate);
this.startDate.validateClosedDate(closedDate);
```
이 부분도 뭔가 개선할 수 있을거 같아 생각해보고  하나의 클래스에서 관리하는 것이 더 낫다고 판단해서 SessionDate를 SessionPeriod로 만들어봤습니다! 잘 맞게 했는지 모르겠지만요...ㅎㅎ

다시 피드백 요청부탁드립니다! 피드백 주시면 적극적으로 반영하도록 하겠습니다! 감사합니다! :)

2023-05-21 02:28 UTC, mskangg approved these changes
2단계 잘 진행해주셨어요 💯 
추가적으로 몇가지 피드백 드렸는데, 다음 단계에 적용해주셔도 될것 같습니다!
그럼 다음 미션도 화이팅 🔥

2023-05-21 02:28 UTC, mskangg commented on src/main/java/nextstep/users/domain/NextStepUsers.java
> +    canEnrollUser();
```suggestion
    if (!canEnrollUser()){
      throw new IllegalArgumentException(MAX_ENROLLMENT_MESSAGE);
    }
```

can, has, is 와 같은 네이밍은 boolean 리턴을 받게 메서드를 설계합니당 :)

2023-05-21 02:28 UTC, mskangg commented on src/main/java/nextstep/courses/domain/Session.java
> +  }
change라는것도 사실 set과 다를게 없어보이네요 🤔 

```java
  PREPARING("준비중"),
  ACCEPTING("모집중"),
  ENDING("종료");
```
이러한 상태를 메서드로 표현해보는 방식은 어떠신가요? 🤔 

```java
session.ending();

public void ending() {
    this.sessionstatus = SessionStatus.ENDING;
}
```

이러한 방식으로 메서드를 설계하고, 추후에 강의를 종료할때 생기는 비즈니스가 생긴다면 `ending` 메서드에만 추가하면 될 것 같아요!

2023-05-21 02:28 UTC, mskangg commented on src/main/java/nextstep/courses/domain/SessionPeriod.java
> +public class SessionPeriod {
좋네요 💯

2023-05-21 02:28 UTC, merged