2단계 - 수강신청(도메인 모델)
next-step/java-lms pull request #83
Opened 2023-05-25 15:09 UTC by GangBean

- 1단계 코멘트 남겨주신 부분 적용해보았습니다~
- 2단계 Session 도메인 클래스 TDD로 구현했습니다.

2023-05-25 15:16 UTC, GangBean commented
근데 요청드리고 보니 드는 의문인데.. 해당 미션이 전체 레이어를 구현하는 미션인걸까요?? ㅎㅎ

2023-05-26 12:23 UTC, parkeeseul requested changes
2단계 미션 잘 진행해 주셨네요! 
몇 가지 코멘트 남겨 두었으니 확인 부탁드립니다 😄 
즐거운 주말 보내세요 🔥

2023-05-26 12:23 UTC, parkeeseul commented on src/main/java/nextstep/courses/domain/Session.java
> +    private final LocalDateTime endDate;
강의 기간이라는 객체로도 나타낼 수 있을 것 같은데 어떻게 생각하시나요? 😄

2023-05-26 12:23 UTC, parkeeseul commented on src/main/java/nextstep/courses/domain/Session.java
> +public class Session {
다음과 같은 요구사항이 있는데 확인 부탁드려요 😄 
`과정(Course)은 기수 단위로 여러 개의 강의(Session)를 가질 수 있다.`

2023-05-26 12:23 UTC, parkeeseul commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +    void 수강신청_모집중_최대인원초과() {
`@DisplayName()` 을 활용해 테스트 설명을 작성해 보면 어떨까요? 😄 
`최대인원을 초과할 경우 수강신청을 할 수 없다.`

해당 테스트 메서드 이외의 다른 테스트 메서드들에도 테스트 설명을 작성해 주면 좋을 것 같아요 😄

2023-05-26 12:23 UTC, parkeeseul commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +            .build();
각 테스트 메서드에서 테스트에 필요한 데이터가 비슷하게 중복되는 것 같은데 중복을 제거해 보면 어떨까요? 😄

2023-05-26 12:24 UTC, parkeeseul commented
> 근데 요청드리고 보니 드는 의문인데.. 해당 미션이 전체 레이어를 구현하는 미션인걸까요?? ㅎㅎ

-> 주어진 요구사항을 DB테이블 설계 없이 도메인 모델부터 구현해 보시면 됩니다 😄

2023-05-26 23:19 UTC, GangBean commented on src/main/java/nextstep/courses/domain/Session.java
> +public class Session {
Course 도메인에 기수역할의 Cohort와 여러개의 강의인 sessions를 추가했습니다.

2023-05-26 23:21 UTC, GangBean commented on src/main/java/nextstep/courses/domain/Session.java
> +    private final LocalDateTime endDate;
강의기간 역할의 객체를 따로 분리하는게 강의기간의 유효성을 판단하는 등 유연한 기능 추가시 유리할 것같습니다. SessionDuration 클래스를 새로 만들었습니다.

2023-05-26 23:39 UTC, GangBean commented on src/main/java/nextstep/courses/domain/Session.java
> +public class Session {
관련해 추가하다 보니 생긴 질문이 있습니다 ㅎㅎ

Course 도메인이 미리 생성되어 있어서 기존 설계를 깨뜨리지 않는 선에서 멤버변수만 추가를 한 상태인데, 가변객체로 설계가 되어있더라구요. 가변객체로 설계되어야할 필요가 있는걸까요??
그리고 createdAt이나 updatedAt 같은 멤버변수가 존재하는걸 봐선 엔티티 클래스의 역할(DB row와 1:1 대응되는 객체)를 하는걸로 보이는데, 엔티티 클래스와 도메인 클래스는 같은 걸로 봐야하는걸까요??

2023-05-27 00:02 UTC, GangBean commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +    void 수강신청_모집중_최대인원초과() {
넵 테스트 설명 추가했습니다!

2023-05-27 00:26 UTC, GangBean commented on src/test/java/nextstep/courses/domain/SessionTest.java
> +            .build();
테스트 클래스에 멤버변수로 중복되는 값 설정했습니다.

2023-05-27 13:44 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨네요.
몇 가지 추가 코멘트 남겨 두었으니 확인해 보시고
추가적인 수정 사항은 다음 단계와 함께 반영 부탁드립니다.
다음 단계 진행해 주세요 😄

2023-05-27 13:44 UTC, parkeeseul commented on src/main/java/nextstep/courses/domain/Session.java
> +public class Session {
> Course 도메인이 미리 생성되어 있어서 기존 설계를 깨뜨리지 않는 선에서 멤버변수만 추가를 한 상태인데, 가변객체로 설계가 되어있더라구요. 가변객체로 설계되어야할 필요가 있는걸까요??

-> Course 내부에 있는 Session의 상태가 변경될 수 있는 점을 말씀하시는게 맞으실까요?
지금 상태에서 불변/가변은 큰 차이가 없을 것 같고, 가변객체로 설계해야 할 필요는 없다고 생각합니다.
다만 JPA를 사용하거나 역할과 책임이 많아질수록 불변으로 작성하는 것은 어려울 수 있으니 참고해서 코드를 작성하시면 좋을 것 같아요 😄 


> 그리고 createdAt이나 updatedAt 같은 멤버변수가 존재하는걸 봐선 엔티티 클래스의 역할(DB row와 1:1 대응되는 객체)를 하는걸로 보이는데, 엔티티 클래스와 도메인 클래스는 같은 걸로 봐야하는걸까요??

-> 2단계 미션에서는 도메인 모델을 구현하는 미션으로 따로 엔티티 클래스와 도메인 클래스를 구분하고 있지는 않습니다.
또한 생성일이나 수정일을 기준으로 어떠한 비즈니스 로직이 생길지 모르기 때문에
생성일과 수정일 필드가 존재한다고 엔티티라고 판단하기는 어려울 것 같아요 😄

2023-05-27 13:44 UTC, parkeeseul commented on src/test/java/nextstep/courses/domain/session/SessionTest.java
> +            .build();
해당 로직도 비슷하게 테스트 코드에서 중복되고 있는데요
메서드로 분리해서 고정이 아닌 status와 같은 값들을 매개변수로 받아
session을 생성하면 중복로직을 줄일 수 있을 것 같네요 😄

2023-05-27 13:44 UTC, parkeeseul commented on src/main/java/nextstep/courses/domain/session/Session.java
> +    private final SessionDuration sessionDuration;
`Session.sessionDuration` vs `Session.duration`
어떻게 생각하시나요? 😄

2023-05-27 13:44 UTC, parkeeseul commented on src/main/java/nextstep/courses/domain/user/Name.java
> +    private final Long id;
모든 객체에 아이디가 존재하고 있네요.
이유가 있으신가요? 🤔 

혹시 DB적용을 염두해 두신 걸까요?
모든 객체는 디비 테이블과 매핑 될까요?

2023-05-27 13:44 UTC, parkeeseul commented on src/main/java/nextstep/courses/domain/user/Name.java
> +public class Name {
Name이란 객체를 따로 분리해 주신 이유가 있으신가요?

2023-05-27 13:44 UTC, merged