Step3 완료
next-step/java-lms pull request #86
Opened 2023-05-26 08:46 UTC by player-geun

안녕하세요 원철님😀 step3 완료했습니다. 리뷰 잘 부탁드립니다❗️질문사항 한 가지 남겨놓도록 하겠습니다 :)

상태를 받는 것보다는 스스로 상태를 결정 짓는 것은 어떨까요?

```
void open() {
  this.status = SessionStatus.OPEN:
}
```

저는 해당 피드백을 외부의 사용자가 잘못된 값을 설정하는 것을 방지하기 위함이라고 생각했습니다. 그렇다면 SessionStatus에 잘못된 상태가 삽입되지 못하게 하는 방어로직을 담은 정적 팩토리 메서드를 통해 상태를 생성하면, 상태를 외부에서 받아도 잘못된 상태값에 대한 문제를 해결하고 중복된 로직을 줄일 수 있다고 생각합니다. 해당 의도가 맞으셨을까요??

2023-05-26 09:12 UTC, heowc requested changes
빠르게 3단계를 진행해주셨네요~

바로 머지하고려고 했지만 약간 아쉬운 부분이 있어 확인 해보고자 코멘트 드려보았습니다.
확인해보시고 코멘트 or 수정 부탁드려요~ 🙏 

--------

> 저는 해당 피드백을 외부의 사용자가 잘못된 값을 설정하는 것을 방지하기 위함이라고 생각했습니다. 그렇다면 SessionStatus에 잘못된 상태가 삽입되지 못하게 하는 방어로직을 담은 정적 팩토리 메서드를 통해 상태를 생성하면, 상태를 외부에서 받아도 잘못된 상태값에 대한 문제를 해결하고 중복된 로직을 줄일 수 있다고 생각합니다. 해당 의도가 맞으셨을까요??

그런 부분보다는 상태를 변경하는 행위를 나 스스로가 아닌 타 객체에게 의존하는게 되는 것이 좋은 방향일까? 결국 setter가 좋냐/나쁘냐에 대한 물음과 동일하다고 생각되는데요.
그런 부분에서 상태는 스스로 변경해야 하고 이를 변경할 수 있도록 의도가 드러난 메소드가 존재하는 것이 좋다고 생각했습니다. 어떻게 생각하시나요? 🤔

2023-05-26 09:12 UTC, heowc commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionRepository.java
> +@Repository("SessionRepository")
빈 이름을 추가하신 이유가 궁금합니다 🤔

2023-05-26 09:12 UTC, heowc commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionRepository.java
> +                session.getCapacity().getNumber(), session.getCapacity().getNumberMax(), session.getCreatedAt());
`BeanPropertyRowMapper` 라는 것도 있는데 이를 활용해보셔도 좋을 것 같아요 🤔 
- https://github.com/benelog/spring-jdbc-tips/blob/master/spring-jdbc-core.md

2023-05-26 09:12 UTC, heowc commented on src/main/java/nextstep/courses/service/SessionService.java
> +        Session session = sessionRepository.findById(id);
없는 id 일때는 npe가 발생하지 않을까요?

2023-05-26 09:12 UTC, heowc commented on src/test/java/nextstep/courses/infrastructure/SessionRepositoryTest.java
> +    void crud() {
테스트를 메소드 단위로 분리해보는 것은 어떨까요? 
테스트 케이스는 하나의 기능만 테스트를 하는 것이 유지보수에도/가독성 측면에서도 좋지 않을까요? 🤔

2023-05-26 09:22 UTC, player-geun commented on src/main/java/nextstep/courses/infrastructure/JdbcSessionRepository.java
> +@Repository("SessionRepository")
`SessionRepository` 의 구현체로 바로 빈을 생성하기 위해 이렇게 진행했습니다!

2023-05-28 12:14 UTC, player-geun commented
안녕하세요 원철님😀 피드백 반영했습니다❗️

테스트 코드의 분리의 경우, 분리를 하는 경우 첫번째 테스트 로직은 성공적으로 실행되는데 이후 외래키 참조 무결성 제약조건에 대해 에러가 발생합니다. 클래스 단위에 @Rollback(false)를 붙이면 해결이 되는데, 왜 되는지는 모르겠어서 일단 이 부분 제외하고 피드백 모두 반영했습니다.

![image](https://github.com/next-step/java-lms/assets/87115015/bca466a1-1b50-4067-bac6-739e4d769268)

도저히 문제가 해결되지 않아 해당 에러가 왜 발생하는지 알려주시면, 해당 부분 수정하도록 하겠습니다!

2023-05-29 04:39 UTC, heowc commented
> 안녕하세요 원철님😀 피드백 반영했습니다❗️
> 
> 테스트 코드의 분리의 경우, 테스트 코드의 순서를 임의로 정할 수는 없으니 Session의 save를 @beforeeach를 통해 진행했습니다. 분리를 하는 경우 첫번째 테스트 로직은 성공적으로 실행되는데, 이후 @beforeeach에서 save를 하는 중에 외래키 참조 무결성 제약조건에 대해 에러가 발생합니다. 클래스 단위에 @Rollback(false)를 붙이면 해결이 되는데, 왜 되는지는 모르겠어서 일단 이 부분 제외하고 피드백 모두 반영했습니다.
> 
> ![image](https://user-images.githubusercontent.com/87115015/241559011-bca466a1-1b50-4067-bac6-739e4d769268.png)
> 
> 도저히 문제가 해결되지 않아 해당 에러가 왜 발생하는지 알려주시면, 다음 step에서 해당 부분 수정하도록 하겠습니다!
> 
> ```
>     @BeforeEach
>     void setUp() {
>         courseRepository = new JdbcCourseRepository(jdbcTemplate);
>         sessionRepository = new JdbcSessionRepository(jdbcTemplate, courseRepository);
>         Course course = new Course(1L, "TDD, 클린 코드 with Java", 1L, LocalDateTime.now(), null);
>         courseRepository.save(course);
> 
>         session = new Session(1L, course, new SessionImage("a", "/"),
>                 new SessionCapacity(0, 10), "TDD, 클린코드", SessionType.PAY,
>                 SessionStatus.READY, LocalDateTime.now(), null);
> 
>         sessionRepository.save(session);
>     }
> ```

`@JdbcTest` 테스트의 경우, 테스트마다 트랜잭션이 있고 실질적으로 데이터베이스 반영이 되지 않고 롤백됩니다.

- https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.testing.spring-boot-applications.autoconfigured-jdbc
- > By default, JDBC tests are transactional and roll back at the end of each test. See the [relevant section](https://docs.spring.io/spring-framework/docs/6.0.9/reference/html/testing.html#testcontext-tx-enabling-transactions) in the Spring Framework Reference Documentation for more details.

그렇기 때문에 말씀하신 것처럼 명시적으로 롤백되지 않게끔 하는 방법도 있고, 그 이외에 문서 명시된 방법 등등 여러가지 방법이 있습니다.

이와 같이 하는 이유는 무엇일까요? 🤔 

- 아마도 테스트간의 간섭을 막기 위함일 것 같아요. 그래서 선택적으로 간섭이 생기는(메소드 순서 등) 문재를 고려해야한다면 선택적으로 사용하도록 가이드하는 부분이지 않을까 싶습니다 😄

2023-05-29 04:40 UTC, heowc approved these changes
피드백 반영 감사합니다 👍

다만 테스트 관련된 부분은 다음 단계를 통해 수정해주시면 좋을 것 같아요 😄 
다음 단계를 진행해주세요~

2023-05-29 04:40 UTC, merged