[step4] 수강신청(요구사항 추가) + step3 피드백 반영
next-step/java-lms pull request #99
Opened 2023-05-27 08:46 UTC by SeokkAng

안녕하세요~

4단계 - 수강신청(요구사항 추가) PR입니다.

진행하면서 step3에서는 강의 상태는 준비중, 모집중, 종료 3가지 상태를 가졌는데요.

step4로 넘어가면서 강의 진행 상태가 준비중, "진행중", 종료 3가지로 변경되고
모집 상태(비모집중, 모집중)로 상태 값을 조회시 기존에 데이터가 없으면 NO_INFO("없음(step3버전)") 를 사용할 수 있도록 했습니다.

강사가 승인, 거절을 할 수 있도록 하였고, 초기값은 REQUEST("신청")로 설정되도록 했습니다.

step3에서 피드백 주신 부분도 같이 수정했습니다!

마지막 과제인데 그동안 너무 감사했습니다! 👍 👍 

이번 과제 피드백도 잘 부탁드립니다!!

2023-05-28 04:13 UTC, seokhongkim requested changes
강석님, 4단계 미션 잘 구현하셨습니다. 👍 
궁금한 점과 수정이 필요한 부분에 코멘트 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2023-05-28 04:13 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/Session.java
> +    public void enroll() {
`enroll`과 `enrollSession`이라는 이름이 나타내는 기능이 비슷한 것처럼 보이네요.
강의의 상태를 모집중으로 변경하는 것이니 `startEnrollment` 와 같이 강의 모집을 시작하는 것으로 변경해보면 어떨까요?

2023-05-28 04:13 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/ApprovalStatus.java
> +    private static final Map<String, ApprovalStatus> approvalStatusMap = Map.of(REQUEST.getApprovalStatus(), REQUEST, APPROVAL.getApprovalStatus(), APPROVAL, REJECTION.getApprovalStatus(), REJECTION)
`REQUEST`라는 코드로 저장하지 않고 "신청", "승인", "거절"이라는 값을 DB에 저장하신 이유가 있을까요?

2023-05-28 04:13 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/SessionEnrollmentStatus.java
> +    public boolean canEnrollment() {
`NO_INFO`인 경우에 `canEnrollment`가 false를 반환하여 수강 신청을 할 수 없을 것으로 보이네요.
step3 기준으로 강의 상태가 진행중이면 `NO_INFO`일 때 수강 신청을 할 수 있어야 하지 않을까요?

2023-05-28 04:13 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/ApprovalStatus.java
> +    public static ApprovalStatus find(String approvalStatus) {
step3에서 구현한 버전에는 `ApprovalStatus` 값이 없을 것으로 보입니다.
값이 없는 경우에 대한 처리도 필요하지 않을까요?

2023-05-28 04:13 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/SessionStatus.java
> +    OPEN("진행중"),
step3에서 DB에 저장되어 있는 키가 "모집중"이었을텐데, 이 키를 변경하면 기존 데이터를 조회할 때 문제가 되지 않을까요?

2023-05-28 04:13 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +        // 기존 데이터들은 ApprovalStatus 정보가 없어서 ApprovalStatus.REQUEST(신청)로 마이그됨
데이터 마이그레이션을 하지 않고도 잘 실행되도록 하려면 어떻게 구현해야 할까요?

2023-05-28 04:13 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +        nsUsers.forEach(session::enrollSession);
1. 이미 등록한 사용자가 또 수강 신청을 하면 어떻게 될까요?
2. 수강 신청은 사용자가 로그인 후 직접 신청하는 경우가 많을 거라고 생각합니다. 그렇다면 `users`와 같이 리스트로 요청이 오기보다는, 단건으로 요청이 들어오지 않을까요?

2023-05-28 04:13 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +    public void enroll(long sessionId, List<String> users) {
`SessionServiceImpl`에도 동일한 기능이 있는데 둘 중 하나는 삭제하면 어떨까요?

2023-05-28 04:13 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +        sessionRepository.save(session);
`saveSessionUser`를 호출해야 수강 신청 내역을 저장할 것으로 보이네요!

2023-05-28 04:13 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/Session.java
> +        sessionUsers.addEnroll(new SessionUser(this, ApprovalStatus.REQUEST, nsUser, now, now));
수강 신청에 승인 단계가 추가되어서, 최대 인원보다 많은 인원이 수강 신청을 할 수 있고 그 중 일부만 승인하는 형태로 변경이 될 것으로 보입니다.
`SessionUsers`에서 인원을 검증하는 로직이 수정되어야 하지 않을까요?

2023-05-28 04:13 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +            sessionUser.approve();
수강 신청을 승인하는 과정에서 최대 수강 인원을 확인하는 로직이 필요할 것으로 보이네요!

2023-05-29 08:18 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/SessionEnrollmentStatus.java
> +    public boolean canEnrollment() {
아 제가 놓쳤습니다. 감사합니다!

2023-05-29 08:22 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/SessionStatus.java
> +    OPEN("진행중"),
아 제가 4단계 이해를 잘못한거 같아요.
기존 상태가 모집중이 없어지고 진행중으로 바뀌고
모집 상태(모집, 비모집)이 새로 추가된건줄알고 변경했습니다...

2023-05-29 08:39 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +        // 기존 데이터들은 ApprovalStatus 정보가 없어서 ApprovalStatus.REQUEST(신청)로 마이그됨
상태에 기존 데이터가 없을때 NO_INFO("없음")으로 처리했습니다.

2023-05-29 08:52 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +        sessionRepository.save(session);
session::enrollSession 여기에서 saveSessionUser를 사용중입니다!

2023-05-29 09:15 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +        nsUsers.forEach(session::enrollSession);
user 단건으로 변경하고 이미 등록한 사용자면 "이미 등록한 사용자 입니다." 라는 문구만 뜨게하고 
아니면 추가하도록 했습니다!

요구사항에 중복처리 관련 내용이 없어서 그냥 진행하다보니 users로 진행한것 같습니다. 
피드백 감사합니다.

2023-05-29 09:16 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +    public void enroll(long sessionId, List<String> users) {
아 넵넵! 감사합니다!

2023-05-29 16:44 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/Session.java
> +        sessionUsers.addEnroll(new SessionUser(this, ApprovalStatus.REQUEST, nsUser, now, now));
최대 인원보다 많은 인원을 받고 넘어가면 REJECTION 표시하여
나중에 승인 과정에서 REJECTION인 상태인것을 제외하여 APPROVAL 상태로 만들어 저장하도록 했습니다.

2023-05-29 16:44 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +            sessionUser.approve();
넵 위에서 처리하였습니다!
감사합니다!

2023-05-29 17:48 UTC, SeokkAng commented
@seokhongkim 
안녕하세요!
꼼꼼한 피드백 감사합니다!
피드백 주신부분 수정하고 테스트하였습니다!

2023-05-30 10:48 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +        sessionRepository.save(session);
<img width="606" alt="스크린샷 2023-05-30 오후 7 47 14" src="https://github.com/next-step/java-lms/assets/44194568/c31b333a-2f9f-4fc5-98eb-68aeaedc053b">

코드와 IDE를 확인했을 때 해당 메서드를 사용하는 곳이 없는 것으로 보이는데, `enrollSession` 내부에서 호출하는 게 맞나요? 혹시 누락된 커밋이 있는지 확인 부탁드려요.

만약 `enrollSession`에서 해당 메서드를 사용하고 있다면, 도메인 내부에서 레포지토리 코드를 사용한다는 것인데 양방향 의존성이 발생하는 것은 아닐까요?

2023-05-30 10:51 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/Session.java
> +        sessionUsers.addEnroll(new SessionUser(this, ApprovalStatus.REQUEST, nsUser, now, now));
최대 인원보다 많은 인원을 받을 때 `REJECTION` 상태로 저장하신 이유가 있을까요?
선착순으로 수강 신청을 한다는 내용은 없으므로, 모두 신청한 상태로 저장한 후 강사가 직접 `APPROVAL` 또는 `REJECTION` 상태로 변경할 수 있을 것 같아서요.
수강 신청을 하는 시점에 다른 상태로 저장한다면, 동시에 수강 신청을 하는 경우 최대 인원보다 많은 인원이 신청중 상태로 저장될 수 있는데, 이에 대한 고려를 해야 할 것으로 보입니다.

2023-05-30 11:04 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/ApprovalStatus.java
> +    private static final Map<String, ApprovalStatus> approvalStatusMap = Map.of(REQUEST.getApprovalStatus(), REQUEST, APPROVAL.getApprovalStatus(), APPROVAL, REJECTION.getApprovalStatus(), REJECTION)
`name()`을 이용해서 코드로 저장할 수도 있는데, 한글로 저장하신 이유가 있는지 궁금해서 여쭤봤습니다. :)

enum의 코드는 잘 변경하지 않는 반면, 설명 문구는 화면에 출력하는 경우도 있어서 종종 변경하는 일이 발생했던 경험이 있습니다.
db에 저장하는 값이라면 필드의 이름을 좀 더 명시적으로 사용해서 임의로 변경할 수 없도록 하고, 테스트에서도 검증하면 좋겠습니다.

이외에 db에 코드로 저장하는 이유 중 하나는, JPA를 사용하는 경우 `@Enumerated(EnumType.STRING)`을 이용하여 `name` 값으로 저장하도록 설정할 수 있는데, 특정 필드의 값으로 저장하려면 별도의 컨버터를 구현해서 사용해야 하는 불편함이 있다는 점도 있습니다.

2023-05-30 11:15 UTC, seokhongkim requested changes
강석님, 4단계 미션 코멘트 잘 반영하셨습니다. 👍 
수정한 코드에 추가로 코멘트 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2023-05-30 11:15 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +            System.out.println(ALREADY_ENROLLED_USER);
수강 신청에 실패한 경우 다른 밸리데이션과 동일하게 예외를 발생시켜보면 어떨까요?

2023-05-30 11:15 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +            sessionUser.approve();
위에 추가한 로직은 `SessionUser` 목록에서 승인 상태인 사용자 목록을 조회해서 승인하는 것으로 보이네요.
`Session`의 `SessionUsers`에 있는 `maxEnrollment` 값을 통해 수강 승인이 가능한지 확인이 필요하지 않을까요?

2023-05-30 11:15 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/Session.java
>      public void enrollSession(NsUser nsUser) {
`Session`에 모집중/비모집중 상태가 없는 경우에는 모두 `NO_INFO`로 저장되어야 동일한 강의에 대해 수강 신청자의 상태도 동일하게 유지되지 않을까요?
즉, 3단계에서 구현된 코드에서 수강 신청이 시작되었다면, 해당 강의에 수강 신청을 하는 사용자의 상태는 모두 동일하게 저장되어야 하지 않을까요?

2023-05-30 11:15 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
>          }
`reject`의 구현을 보니 `users` 목록을 인자로 전달받는데, 이 값을 사용하지 않고 수강 신청을 한 사람중 승인된 사람을 모두 `reject` 상태로 변경하네요.
1. 55번 라인의 `sessionUsers.getSessionUsers().forEach(SessionUser::approve);` 코드에서 수강 신청한 모든 사람을 승인 상태로 변경하는 이유가 있을까요?
2. `users`로 전달된 사용자만 `reject`해야 하는데, 모든 사용자에 대해 `reject`하는 로직도 수정이 필요해 보입니다.

2023-05-30 12:33 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/ApprovalStatus.java
> +    private static final Map<String, ApprovalStatus> approvalStatusMap = Map.of(REQUEST.getApprovalStatus(), REQUEST, APPROVAL.getApprovalStatus(), APPROVAL, REJECTION.getApprovalStatus(), REJECTION)
아하! 개인적인 경험과 추가 설명 너무 감사드립니다!

2023-05-30 12:40 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +        sessionRepository.save(session);
엇.. 아래 링크에서는 보이는데 왜 반영이 안됐을까요...
코드 커밋도 잘 되어있는거 같은데 이상하네요 ㅠㅠ
https://github.com/next-step/java-lms/pull/99/commits/e421be1d0051279cf33f21418d59d5d02057c3ee#diff-871d5050c883cda19bd9ab1ff1159a830be82fb7074170b3a7e0e1748ac22e43

말씀처럼 saveSessionUser를 호출하도록 수정했습니다!

2023-05-30 13:31 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +            sessionUser.approve();
REJECTION만 제외하고 
SessionUsers를 만들면서 maxEnrollment를 통해 수강 승인이 가능한지 검증로직 추가했습니다!

2023-05-30 13:39 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/Session.java
>      public void enrollSession(NsUser nsUser) {
아 그렇네요..!
3단계 처럼 기존 상태가 없이 null인 경우 NO_INFO로 저장되도록 수정했습니다..!

놓친게 많네요ㅠㅠ

피드백 감사합니다!!

2023-05-30 14:19 UTC, SeokkAng commented
@seokhongkim 
안녕하세요!
제가 놓친것들이 많아서 봐주시기 힘들었을거 같은데 꼼꼼한 피드백 너무 감사합니다 ㅠㅠ
말씀해주신 피드백 모두 적용했습니다!!

마지막까지 다시 한 번 감사합니다. 👍 👍

2023-05-30 15:11 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
>          }
앗 제가 approve하면서 뭔가 잘못 한것 같습니다..!
전달된 user만 처리하도록 해당 부분 수정했습니다!

2023-05-31 09:02 UTC, seokhongkim requested changes
강석님, 코멘트 잘 반영하셨습니다. 👍 
마지막으로 로직상 확인해보시면 좋을 것 같은 내용이 있어 코멘트 남겼습니다.
코멘트 확인 부탁드립니다. 🙂

2023-05-31 09:02 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +        sessionRepository.save(session);
<img width="1286" alt="스크린샷 2023-05-31 오후 5 59 20" src="https://github.com/next-step/java-lms/assets/44194568/2cd19933-d718-4a5c-9449-0176150f138d">

해당 링크에도 `enrollSession` 내부에서 `saveSessionUser`를 사용하는 코드는 없는 것 같은데, 혹시 제가 잘못된 페이지를 보고 있는걸까요? 😢 `saveSessionUser`를 호출하고 있는 코드를 캡쳐해서 첨부해주시면 어떨까요?
현재 푸시된 코드를 받아봐도 `saveSessionUser`를 호출하는 코드는 없는 것으로 보입니다.

2023-05-31 09:02 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/Session.java
>      public void enrollSession(NsUser nsUser) {
이 코멘트는 `enrollSession` 메서드의 구현에 대한 부분인데, 생성자에서 `sessionEnrollmentStatus`가 없는 경우에 대한 처리를 하신 것으로 보입니다.
수강 신청을 했을 때 `SessionUser`의 상태에 대한 내용입니다. :)

2023-05-31 16:24 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +        SessionUsers sessionUsers = new SessionUsers(sessionUserList, maxEnrollment);
넵! 고민해보겠습니다.
감사합니다!!

2023-05-31 16:46 UTC, SeokkAng commented
@seokhongkim 
안녕하세요!
마지막까지 꼼꼼한 리뷰 정말 감사합니다!

위의 말씀해주신 피드백 수정하였습니다.

[마지막 피드백](https://github.com/next-step/java-lms/pull/99#discussion_r1211328539)에서 
saveSessionUser 호출을 했었는데, 다시 보니깐 안보이네요...
해당 부분 추가했습니다! 

감사합니다!

2023-05-31 16:47 UTC, SeokkAng commented on src/main/java/nextstep/courses/domain/SessionUserServiceImpl.java
> +        sessionRepository.save(session);
saveSessionUser 호출을 했었는데, 다시 보니깐 안보이네요...
해당 부분 추가했습니다!
감사합니다!

2023-06-01 08:54 UTC, seokhongkim approved these changes
강석님, 4단계 미션 코멘트 잘 반영하셨습니다. 👍 
4단계 PR 머지하겠습니다.

마지막 강의가 있고 교육이 끝나는 날인데, 마지막까지 미션 진행하느라 수고 많으셨습니다.
다가오는 주말 즐겁게 보내시길 바랍니다. 🙂

2023-06-01 08:54 UTC, seokhongkim commented on src/main/java/nextstep/courses/domain/Session.java
> +                .reduce(Boolean::logicalAnd)
하나라도 데이터가 있는 경우 `enrolledUser`일 것으로 보이니, `logicalOr`를 사용해야 하지 않을까요? :)

`sessionUsers.getSessionUsers()`로 데이터를 꺼내서 값을 확인하는 것보다, `sessionUsers`에게 `contains(nsUser)`와 같이 물어보는 것은 어떨까요?

2023-06-01 08:54 UTC, merged